:PROPERTIES:
:ID:       4e8771d5-15d7-42b2-8c2f-e16ad02e9fc5
:END:
#+title: Semantic Adaptivity and Social Networking in Personal Learning Environments

Joseph Corneli

August 23, 2009

* Introduction

Perusing the literature, one may quickly discover how many dimensions
are relevant to personalized learning. Here is an incomplete list,
that illustrates the richness and complexity of this area:

- Stakeholders :: students, instructors, educational institutions, content providers, technology providers, accreditation bodies [1]
- Learning modes :: asynchronous or synchronous, co-located or distributed, individual or collaborative, electronic-only or blended [1]
- Fundamental needs :: subsistence, protection, affection, understanding, participation, leisure, creation, identity, freedom [2]
- Knowledge elements :: concepts, topics, objectives, outcomes [3]
- General features of learners :: knowledge, interests, background, goals, traits [3]
- Cognitive styles :: field-dependent or independent, impulsive or reflective, conceptual or inferential, thematic or relational, holist or serialist [3]
- Learning styles :: modeled many different ways, cf. for example Felder [4], cited in [3]
- Learning skills :: self-discipline, ability to work alone, good time management, independence, readiness, the ability to plan [5]
- Emotional states :: joy/distress, pride/shame, admiration/reproach, etc. [6], cited in [3]
- Observable variables :: hints asked per question, time taken for each attempt, average time between problems, etc. [3]
- Model type :: Overlayed, layered, Bayesian network, concept map, etc.

In the face of this complexity, I suggest we begin by looking at
something very simple: the link “ACB”. This semantic link or triple is
equivalent to the labeled arrow C running from A to B in a “concept map”
or “bubble diagram”, except that C is a cell as well as an arrow, and
“ACB” is a structural unit. (RDF triples by any other name; see Section
2.2 of [8].) When we model this way, we quickly begin to see more than
one layer of annotations; the link is our gateway into the rhizomic
world ([9], [10]) of semantic hypertext [11]. In particular, we see, or
begin to see, byproducts of processes, and externalities of
transactions.

Semantic networks formed from triples are prime ground for studying
learning from the viewpoint of symbolic interactionism [12], since they
make explicit the meanings, interactions, and interpretive processes
with which learners are engaged. Interactive, textual, and social, such
networks form input suitable for ethnographic research and ethnography-informed development work in the domain of personalized learning ([13],
[14], cited in [15]).

* Discussion.

Semantic networks of this sort convey a sense of consequences:


#+begin_src
                          tranported by truck
(the berenjena in Mexico −−−−−−−−−−−−−−−−−−−→ the eggplant in Massachusetts)
PRODUCES
−−−−−−−→ smog.
#+end_src

In an example related to education ([7], Chapter 10):

#+begin_src
(Given the problem of finding the average of three things

         (###)
 writing -----
           3
−−−−−−−−−−−−−−−−→ the answer)

SUBLIMINALLY REENFORCES

−−−−−−−−−−−−−−−−−−−−−−−−−→ good use of parentheses and sums in general.
#+end_src

Describing the dimensions of learning experiences and interactions as
semantic networks, we avail ourselves of an opportunity to study the
resources and processes used by learners, and the effects and
side-effects of these processes, in a systematic and semi-transferable
fashion.

The close similarity of semantic networks and conceptual maps indicates
that many of the same intuitive-use features, including features
supporting self-directed learning [5], will be directly beneficial to
learners who are navigating complex resource arrangements. In addition,
the job of interpreting and adapting to user behavior will take place on
richer epistemological ground when input data contains explicit
semantics (no matter how sloppy), and not just one-layer tags to which
semantics are supplied later (as in [16]). If we are to overcome the
difficulties and limitations in uptake of the semantic web, and reap the
benefits of structure, then sloppiness and informality must come first,
and precise distillations, later.{1}

Ideally we would find ways to integrate every learner's personal
context, experience, values, and instincts (not to mention their
preferred user interface), into one platform that makes helpful and
coherent recommendations based on patterns it finds among the data it
collects, utilizing a combination of peer interactions and automatic
inference. As system designers, we are ourselves participants in a
learning process. The fact that the system too will “learn” by
interacting with themes that repeat with variations, by testing its
current abilities on new data and getting feedback on the quality of the
results, and by being brought to its point of failure and overcoming
that failure with assistance, serves to underscore the fact that we can
learn a lot about learning in the course of this study.

Whoever the learner is, personalization should capture value and reduce
waste and frustration. Sometimes the extra value falls to society as a
whole: Recaptcha is a popular web service that exemplifies extraction of
extra value from distributed routine labor [18]. Sometimes gains will go
directly to the learner, in terms of time saved, skills gained, or an
enhanced sense of meaning. By connecting learning needs and relevant
engagement opportunities, we may realistically hope for widely accruing
benefits; this is the vision behind student involvement with “real-world
problems” in the liberal arts [19] or sciences [20].

A key theme in this proposal is that all learning takes place in the
real world, so that, following the rules of open systems, there will
always be extra value to capture. If we understand the semantics of
different modes of learner engagement, and the associated products,
externalities, and arbitrage opportunities, we will be able to create
useful, effective, personalization that enhances both the personal and
social value of learning.

*Agenda.* /(Phase I.)/ I propose to begin by making semantic maps of
three domains: (1) personalized learning environments in general
(starting with a network version of the survey given above); (2) the
major target domain OpenLearn{2}; and (3) PlanetMath.org{3}, a non-profit community-based mathematics website, on whose board of directors
I serve.

Over the past several years I have developed an open source
triples-based software system, Arxana, which stands ready to facilitate
this work [21]. Studying Domain (1) will expose other approaches, and a
comparison of approaches should show how best to extend and deploy the
triples-based network approach in building and studying personalized
learning environments. Domains (2) and (3) possess very different user
communities and inherent semantics; a comparative study along the
dimensions of (1) will be the groundwork for subsequent phases of PLE
development in these domains.

/(Phase II.)/ I propose to deploy Arxana in an open source demo in
Domains (2) and (3), in a form suitable for use in building learning
objects, curricula suitable for self-directed study, and personalized
learning plans.

System prototyping in Domain (2) will proceed in concert with the ROLE
Project{4} and, in particular, will follow evaluation criteria specified
by that project{5}. The general outline of the work is: (i) can we bring
learners to their personal point of difficulty; (ii) help them
explicitly identify and describe this difficulty; and (iii) help them
obtain contextualizing information that enables them to surmount the
difficulty? Ruling out non-useful helps will often be an important step
in finding the useful ones; both subjective feedback (“was this
helpful?”), and objective measures of learner performance, will show
what's working.

System prototyping in Domain (3) will proceed in concert with work by
Ross Moore{6}, Frank Quinn{7}, and the Noösphere development team{8}, to
develop tools for authoring self-grading problem sets, and methods to
assess and improve the quality of connection between the elements of
PlanetMath's corpus. When topics connect to exercises and applications, preliminary materials, and resources for further learning, the
result will be a tool that students can use for self-directed study in
mathematics. Further, our tool will be able to track individual
performance ([7], Chapter 11) and will have a sense of what has worked
for other learners in similar situations, so that we can provide the
benefits of personalization.

/(Phase III.)/ I propose to conclude the project by integrating my
findings into a web frontend, that works transparently with other
web-based learning platforms, and that facilitates mixing, annotating,
and connecting learning resources. In some respects similar to
iGoogle{9}, in the sense that it brings different modular interactive
resources and data feeds to the user, the tool should cut across modules
in its annotation and connection layer. Indeed, the combination of
connection and modularity is the key to commons-based peer production
[22], an approach that will help subsequent developments in personalized
learning that build on our efforts achieve social and financial
sustainability.

* Notes

{1} “Tags are easy to create, as users are free to use any word or
phrase they please, without restrictions. This simple and highly usable
mechanism has caused Social Web applications to be very popular with
users. The formal metadata representation employed by the Semantic Web,
on the other hand, makes it far more difficult to create annotations.
Although semantic metadata has enormous potential, its limitations in
terms of usability are proving a significant barrier which discourages
users and prevents the technology from becoming more widely
established.” [17]

{2} OpenLearn, [[http://openlearn.open.ac.uk/][http://openlearn.open.ac.uk/]]

{3} PlanetMath.org: Math for the people, by the people,
[[http://planetmath.org][http://planetmath.org]]

{4} Responsive Open Learning Environments (ROLE),
[[http://www.role-project.eu][http://www.role-project.eu]]

{5} Deliverable M48, [[http://www.role-project.eu/Deliverables][http://www.role-project.eu/Deliverables]]

{6} Towards tagged PDF, [[http://www.tug.org/tug2009/abstracts/moore.txt][http://www.tug.org/tug2009/abstracts/moore.txt]]

{7} The EduTeX Wiki,
[[http://edutex-wiki.tug.org/wiki/index.php?title=Main_Page][http://edutex-wiki.tug.org/wiki/index.php?title=Main_Page]]

{8} Noösphere, [[http://code.google.com/p/noosphere/][http://code.google.com/p/noosphere/]]

{9} iGoogle, [[http://www.google.com/ig][http://www.google.com/ig]]

* Bibliography

[1] Wagner, N., Hassamein, K., and Head, M. (2008). Who is responsible
for E-Learning Success in Higher Education? A Stakeholders' Analysis.
Educational Technology & Society, 11(3), 26--36

[2] Manfred A. Max-Neef with Antonio Elizalde, Martin Hopenhayn (1991).
Human scale development: conception, application and further
reflections. Apex Press. (Appendix to Chapter. 2. “Development and Human
Needs”, p. 18.)

[3] Peter Brusilovsky and Eva Millán. (2007). User Models for Adaptive
Hypermedia and Adaptive Educational Systems, in P. Brusilovsky, A.
Kobsa, and W. Nejdl (Eds.), The Adaptive Web, LNCS 4321, 3--53

[4] Felder, R. (1988). Learning and teaching styles. Journal of
Engineering Education 78(7), 674-681

[5] Chao Boon Kheng Leng Teo and Robert Gay (2006). Concept map
provision for E-learning. Int. J. Instructional Technology Distance
Learning, 3(7), 17--32, [[http://www.itdl.org/Journal/Jul_06/article02.htm][http://www.itdl.org/Journal/Jul_06/article02.htm]]

[6] Ortony, A., Clore, G. L., Collins, A. (1988). The Cognitive
Structure of Emotions, Cambridge University Press

[7] Frank Quinn (2009), Essays on Mathematics Education (July 2009
Draft), [[http://www.math.vt.edu/people/quinn/education/Book0.pdf][http://www.math.vt.edu/people/quinn/education/Book0.pdf]]

[8] Frank Manola and Eric Miller (2004), RDF Primer, W3C,
[[http://www.w3.org/TR/2004/REC-rdf-primer-20040210/][http://www.w3.org/TR/2004/REC-rdf-primer-20040210/]]

[9] Gilles Deleuze and Félix Guattari (1980). Mille Plateaux. Paris: Les
Editions de Minuit (translation, Brian Massumi (1987). A Thousand
Plateaus, University of Minnesota Press)

[10] Umberto Eco (1984). Semiotics and the philosophy of language,
Indiana University Press

[11] Kathleen Burnett (1993). Toward a theory of hypertextual design,
Postmodern Culture 3(2),
[[http://www.iath.virginia.edu/pmc/text-only/issue.193/burnett.193][http://www.iath.virginia.edu/pmc/text-only/issue.193/burnett.193]]

[12] Blumer, Herbert (1969). Symbolic Interactionism: Perspective and
Method. University of California Press

[13] Christopher Pole and Marlene Morrison (2003). Ethnography for
Education. Open University Press

[14] Christine Hine (2000). Virtual Ethnography. Sage Publications Ltd

[15] David Scott and Marlene Morrison (2007). Key Ideas in Educational
Research, Continuum International Publishing Group

[16] Sofia Angeletou (2008). Semantic Enrichment of Folksonomies,
Technical Report kmi- 08-06, Knowledge Media Institute, The Open
University

[17] Peter Edwards, Richard Reid, Alison Chorley, Feikje Hielkema,
Rudradeb Mitra, and Edoardo Pignotti (2009), Building a Social Semantic
Web for eScience, in Proceedings of the AAAI 2009 Spring Symposium on
Social Semantic Web: Where Web 2.0 meets Web 3.0,
[[http://www.csd.abdn.ac.uk/~pedwards/research/pubs/aaai-sss2009.pdf][http://www.csd.abdn.ac.uk/~pedwards/research/pubs/aaai-sss2009.pdf]]

[18] Luis von Ahn, Benjamin Maurer, Colin McMillen, David Abraham,
Manuel Blum (2008). reCAPTCHA: Human-Based Character Recognition via Web
Security Measures, Science, 321(12), 1465--1468

[19] Elizabeth Coleman (2007). The Bennington Curriculum: A New Liberal
Arts, [[http://www.bennington.edu/go/about-bennington/a-new-liberal-arts][http://www.bennington.edu/go/about-bennington/a-new-liberal-arts]]

[20] National Science Foundation, Research Experiences for
Undergraduates: Program Announcement,
[[http://www.nsf.gov/nsf/nsfpubs/nsf96102/nsf96102.htm][http://www.nsf.gov/nsf/nsfpubs/nsf96102/nsf96102.htm]]

[21] Joseph Corneli (2009). Arxana,
[[http://metameso.org/files/unstable-arxana.pdf][[http://metameso.org/files/unstable-arxana.pdf]]

[22] Joseph Corneli and Aaron Krowne (2005). A Scholia-based Document
Model for Commons-based Peer Production, in M. Halbert (Ed.): Free
Culture and the Digital Library Symposium Proceedings. Atlanta, Georgia:
MetaScholar Initiative at Emory University, 240--253
