:PROPERTIES:
:ID:       f83051b3-95b5-4471-b03d-eeeccda51d6d
:END:
#+title: (Inter-)Personal Doughnut
#+filetags: :HL:BP:

* Problem

Informed by [[id:56ce8d31-d3d6-4493-bb41-b07d810afbcc][Causal Layered Analysis]], at the workshop we were ready to
work across levels — but did we have the /correct/ set of levels for the
‘public space & public health’ setting front-of-mind?

* Solution Strategy

Something that came up in the discussions around the workshop and
PLACARD method was our prominent focus on /the wellbeing of
participants/.  We could frame this in a rough analogy with Doughnut
Economics, HOWEVER the framing would be different in this small-scale
format.

BECAUSE ‘health’ is inherently a complex topic — e.g., considering a
“bio-psycho-social” or “bio-psycho-social-eco” model — there are
multiple moving parts.  If we want to talk about health effectively in
future versions of the workshop, we might want to rethink aspects of
the workshop itself using /these/ components; e.g., the “roles” that we
use in Phase II could potentially be rethought this way.

Since we cannot be guaranteed to have teams of participants with
expertise evenly divided along the bio/psycho/social/eco components of
health, THEREFORE, it could be useful to survey some of the other
frameworks that are out there that could be relevant to this
reframing, so that we could get creative about reconfiguring them.
Examples might include [[id:827ae14c-27d3-4483-93a9-d4005c5231a8][Human needs]] (like [[https://en.wikipedia.org/wiki/Manfred_Max-Neef%27s_Fundamental_human_needs][Manfred Max-Neef's
Fundamental human needs]]) and values (like Schwartz’s [[https://en.wikipedia.org/wiki/Theory_of_Basic_Human_Values][Theory of Basic
Human Values]]).

#+begin_quote
According to Schwartz, individual values are responses to three
universal requirements of human existence, namely needs of people as
biological organisms, of agreement in social actions, and of survival
and well-being of groups.
#+end_quote

In the context of our workshop, it looks like the [[id:59798017-b0af-473e-bdcd-108a8ef1e06d][Productive tensions]]
might take a doughnut-like shape, since, for each, we neither want too
much of one dimension nor too much of the other.

SPECIFICALLY, we want to consider the bio-psycho-social-eco aspects of
health for each aspect of the ‘habitable zone’.  Therefore, it doesn’t
really make sense to /layer/ bio/psycho/social/eco the way we do
litany/system/worldview/myth.  Even if the four dimensions of health
could themselves be convincingly nested — and aligned with Raworth’s
model — in our context, they seem to run ‘orthogonal’ to the CLA
dimensions.  That said, it does seem useful for our purposes to
analogise the CLA layers with Raworth’s layers.  Generalising
Raworth’s model, a culture might have /an overproduction of
externalities/ and a deficit of /integrative adaptive strategies/.  These
could be straightforwardly aligned with Innayatullah’s litany and myth
layers.

Potentially the thoughts here could lead to a sequel to "Patterns of
Patterns" where we look at a "framework of frameworks".

We could look at how these factors show up around limits to active
participation in (both) [[id:57f06710-a96c-4cbc-bcc7-57d3d3e550c4][Public Space & Public Discourse]].

It’s also interesting to imagine that a [[id:d32e37dd-6649-4465-a932-ea51183b1e79][Perfect City]] might be built on
the ‘doughnut’ model.
