#+title: Teach arbitrary coding
#+roam_tags: LRD

This would be an abstraction over teaching basic programming and
knowledge graphs.

* Feature: Production system

We’ve started to build a simple production system that can be used to
detect errors in subtraction (reimplementing some classic work). We
were thinking that something similar could be used to detect other
kinds of errors (so, for debugging, teaching), and to support other
kinds of reasoning processes (e.g., turning Q’s into A’s in a
question-answering system).

We previously did a little exploratory work, with similar intent, using
polygraphs as input, in the workshop paper
/Modelling the Way Mathematics Is Actually Done/.

** Demo application: Reimplementing classic rules to model subtraction

We looked at a classic paper about “subtraction on Mars” and it seems
that reimplementing it might be the best way to go.

* Contributes to :noexport:
:PROPERTIES:
:ID:       98bd73a0-035b-434c-aa2e-ea0e3e6ec15d
:END:
- [[file:20200814210243-business_development.org][BUSINESS DEVELOPMENT]]

