#+TITLE: Background

* Nourse
** Mobility difficulty
But without no medical treatment
** Over population
And environmental degradation; reducing the population by 2/3 wouldn’t be a bad idea.
** Middleman
Source for underground
** Sterilisation
Price for medical service, to limit population
** Computer court
Automated justice
** Neuropentagram
Observe humans to replace them
** Kate
Middle-manager
** Shanghai Flu
Mild symptoms discourage people seeking treatment but it has a second phase that produces meningitis.
** Health Control
Knows all about underground medicine
** Spreading the word
Averting the crisis
** Statistics
Potential catastrophe
** Bureaucracy
Linked with the government
** The lower end of the labour market
Necessary for a functioning society
** Would you submit to an injection?
Given the circumstances
** Surveillance state
How much is this costing?
** Unnecessarily dangerous surgeries
In order to fool the machine
** Naturists
A cult
** Police helicopters
Part of the surveillance state
* Foucault
** Truth, Power, Self
The main interest in life and work is to become someone else that you were not in the beginning.
* Burroughs
** Rioting continues
** Contaminated water supply
** Illicit drugs
** Background
How, in terms of what is actually presented on screen, can we acquaint
those living in the [present] with [the future’s] background, with
what is common knowledge to anyone living in the [future]? [: : : ]
How can the background be shown solely in terms of what people say,
experience, and do on screen?
** Cartoons
A series of cartoons from The Watch Dog show the plight of Mr. In The
Middle.
** Narrator
“He riffles through stills from the movie like a deck of cards,”
** Absent filmmakers
(This shot is identical to dream shot as he trips, falls and turns to
face pursuer.)
** Amazon pills
In 1956 a contraceptive drug developed by the Amazon Indians was
submitted to an American drug company for testing and eventual
distribution.  One dose prevents pregnancy for seven years. Drug
companies rejected the drug, since it would cut their profits.
** Increase in succeptibility to cancer
The accelerated cancer virus is revealed as a form of space alien
attack that preys on a populace willing to attack itself.
** Racial bigotry
** Mafiosos
Mafiosos lean out of their Cadillacs to spit in the taxpayer’s
face. ‘Who you, worka fora living? I speet in your crumb face’
** Cyborg
** Someone took my darling and turned her inside out
And turned her into something I’ll never figure out
It wasn’t her decision to leave the human race
** B23
** Space beings
“look different to everyone and are a state of mind, a possession of
human bodies and minds, rather than separate entities”
** Roberts
Roberts serves steaks, french fries and flapjacks with beer. Billy
eats ravenously
** The Hand
** Parrot
** Unruh’s Disease
characterized by an itching burning erogenous rash in the genitals and
surrounding areas, accompanied by an uncontrollable sexual
frenzy. Side effects include bizarre changes in pigmentation during
intercourse.
** Heroin
Heroin was legalized for addicts in 1980
** Pictures
Each picture has a run of live film. They come alive as Billy looks at
them.
** Screens
Two story lines that can run alternately or on two screens. The story
that we have been following up to this point... the other story taken
from the book, The Bladerunner.
** Bar brawl
Roberts hits the man in the midriff with his fist, then brings a
hammerfist to the side of his neck. Roberts and his two friends make
the door. Billy is on his feet. He sidesteps one man, catches another
with a nose chop. Three others stand between him and the door. He
trips one, uses a bar stool as a pivot to swing past the other
two. Someone puts out a leg. He trips and falls, turning as he goes
down.
** An epidemic of smallpox
** The King of Subways
has his headquarters in Queens Plaza, a dazzling construction of
subway cars, change booths, turnstiles, so that part of the structure
is always in motion
** Result
the eccentric, the adventurer, long banished to limbo by the coalition
of the big drug companies and the FDA, reappear.
** Underground population
Overpopulation has led to ever-increasing governmental control over
the private citizen ... However, this has not produced the brainwashed
standardized human units postulated by such linear prophets as George
Orwell. Instead, a large percentage of the population has been forced
underground. How large, no one knows. These people are numberless.
** Escape value
‘a very necessary escape valve’
** The future
man has no future unless he can throw off the dead past and absorb the
underground of his own being
* Dick
** Off world
