#+TITLE: BBC 28 March 2021

* HOSPITAL

Truth, Power, Self: The main interest in life and work is to become someone else that you were not in the beginning.

Because of their health improvements people are able to spend more time on this effort. But there's someone here who is connected to the art thief. The reason he's stealing the art is to move away from the fame-based be-a-better-you scenario, to try and see what contribution you can make to the world.

His name is Parrot. He represents the underground as opposed to government ideas of health and wellbeing.

Today, the hospital is packed full of healthy people.  The healthy people are the doctors.

Although this was in the past... over-population and environmental degradation are such that reducing the population by 2/3 wouldn’t be a bad idea.

* CITY

Bill goes to the museum near the hospital.

He bumps into an art thief.

The art thief has retired from space mining, after an injury.

The lower end of the labour market is necessary for a functioning society — the art thief is the lowest of the low.

[Ext.] The King of Subways
has his headquarters in Queens Plaza, a dazzling construction of
subway cars, change booths, turnstiles, so that part of the structure
is always in motion (The art thief has been there before.)

These days, the subway tunnels are mostly used by electric scooters.

The art thief tries to grab an electric scooter but... the art thief gets picked up by the person from the hospital.

Bill is near the exit of the underground car park, they are at the other end, and he makes a mad dash to try and get to the barrier, to speak to the parking attendant, so that he doesn't let them out — there's a race against time.

The art thief and his compadre, Parrot, are out, on the underground scooter track, but now a water pipe has broken over the track and has flooded the tunnel.  Basically now the painting of the duck was floating on the water but everything around the duck has faded away and has revealed something...

Nobody underground realises that the sky is turning purple.

* HOME

Molly is having a bubble bath

She really misses her rubberduck.

Molly gets a call from Bill while he witnesses the art thief.

She gets out the bath tub and most of the water is spilled. 

Possible history: Contaminated water supply

Billy's voice is shaking: "Someone is stealing a picture of a duck"

Molly chuckles for 7 minutes.

[In the background, On the TV: Cartoons] A series of cartoons from 'The Watch Dog' show the plight of "Mr. In The Middle".

Meanwhile Molly notices that the color of the tiles on the floor where the water splashed are going somewhat lighter. But she sort of ignores this because she's now going to meet Bill.

For some reason she can't quite put her finger on, Molly is still chuckling.

Although she doesn't pay much attention to this, she is feeling VERY eager to see Bill...

Molly realises that she can't understand why she can't stop laughing, and her skin is feeling stingy where she's been in the bath, but it's not entirely unpleasant. She realises that there's something that she's absorbed from the water, and that she's high as a kite. And she's suddenly seeing the solution to the world's problems, and she realised that she's been a bit depressed b/c of not having children. But suddenly she doesn't mind because she's having all these amazing ideas. But she's also aware of the policy discussion happening at the world stage, and the government has been becoming more authoritarian, she's becoming paranoid with good reason because she thinks the government has been putting something in the water. She thinks it may have to do with new elements in the periodic table associated with space mining.

Later a contamination crew is brought in to clean up in the house — after Molly is gone.

* GOVERNMENT

World policy level discussions happen here.

There has been a lot of discussion - should they really let the trainee take care of the watersupply? 
