#+TITLE: Emacs Research Group, Season Zero: What we did together with Emacs in 2 hours a week for a year
#+Author: Noorah Alhasan, Joe Corneli, Raymond Puzio, Leo Vivier
#+DATE: [Emacsconf 2021]

* OUTLINE

- PRELUDE
  - EmacsConf 2020
  - Emacs Research Group convenes!
- BACKGROUND AND TECHNOLOGY
  - crdt.el
  - BBB
- DEMO
- PROCESS
  - Project Action Review (PAR)
  - Causal Layered Analysis (CLA)
  - Design patterns and next steps
- OUTCOMES
  - “Patterns of Patterns” paper for PLoP 2021
  - PLACARD workshop
- CONCLUSION
  - You should consider creating your own small research communities similar to ours!

* PRELUDE

[ Just a picture of us talking? ]

- Leo Vivier
- Noorah Alhasan
- Ray Puzio
- Joe Corneli

- The four of us met at EmacsConf 2020 with a common interest in Emacs and research.
- We’ve met almost every week since then, because we wanted to keep the conversation going.
- In this short talk, we share information about the methods we use,
  making a case for other people getting together and creating their
  own small research communities similar to ours.
* BACKGROUND AND TECHNOLOGY

We wanted an Emacs-centric solution for real-time meetings.

Tech stack:

- Emacs
- crdt.el
- Org mode!
- Git
- Firn
- BBB

* DEMO
* PROCESS
** How we organise our meetings

| DD Month YEAR — Emacs Research Group                                 | 120m |
|----------------------------------------------------------------------+------|
| Check-ins                                                            | 20m  |
| Things to keep in mind                                               |      |
| Topic 1                                                              | 40m  |
| Break                                                                | 5m   |
| Topic 2                                                              | 35m  |
| PAR                                                                  | 15m  |
| Check-out (exceptional or not, include any scheduling announcements) | 5m   |

** Project Action Review (weekly)
#+begin_src
1. Review the intention: what do we expect to learn or make together?
2. Establish what is happening: what and how are we learning?
3. What are some different perspectives on what’s happening?
4. What did we learn or change?
5. What else should we change going forward?
#+end_src
** Causal Layered Analysis (every six weeks)
#+begin_src
1. Litany
2. System
3. Worldview
4. Myth
#+end_src
** Design Patterns (as needed, and linked with TODO items)
#+begin_src
1. Context
2. Problem
3. Solution
4. Next steps
#+end_src

* OUTCOMES

** Patterns of Patterns (PLoP 2021)

#+begin_quote
The purpose of this paper is to show how we can combine and adapt
methods from elite training, future studies, and collaborative design,
and apply them to address significant problems in social networks.
— https://arxiv.org/abs/2107.10497
#+end_quote

...
- Methods
  - Project Action Review
  - Causal Layered Analysis
  - Design Pattern Languages
  - PLACARD: A Synthesis of PAR, CLA, and DPL
- Context of the Research
  - Design Pattern Language literature and practices
  - Emacs Research Group
...
** PLACARD Workshop roles
#+begin_src
1. Kaiju Communicator — Problems emerging in a scenario
2. Historian — How we got there
3. Designer — Design patterns and possible next steps
4. Analyst — Analysis of the activity including deeper meanings
#+end_src
** Initial user studies

Guests included:

 - Alex Murphy MSc in Data Analytics, beginning Emacs user
 - Mark Dawson of M-x Research
 - Qiantan Hong, developer of crdt.el

Building on these conversations we would like to do more interviews,
and eventually be able to say:

- ‘If you are someone who does X, these are the packages that would work for you’

* CONCLUSION

You should consider creating your own small research communities
similar to ours!
