#+TITLE: EmacsConf 2021 Speakernotes
#+Author: Noorah Alhasan, Joe Corneli, Raymond Puzio, Leo Vivier
#+roam_tag: HI
#+FIRN_UNDER: erg
# Uncomment these lines and adjust the date to match
#+FIRN_LAYOUT: erg-update
#+DATE_CREATED: <2021-10-30 Sat>

* Tech notes

#+begin_src
;; Ssh to your server (unless your computer has a static IP)
ssh joe@178.79.174.58
;; Start Emacs
emacs -Q -nw crdt.el/crdt.el
;; Source
M-x eval-buffer (could be automated with the above)
;; Create the content
M-x share-buffer
;; Share joining instructions:  M-x crdt-connect RET metameso.org default port <pass>
#+end_src

* Agenda                                                                :85m:
** EmacsConf: Storyboarding                                            :35m:
*** ----------------------------------------
*** INTRODUCTIONS                                                      :2m:
#+begin_quote
Hi I’m Noorah Alhasan, I’m a member of the ERG group, and a PhD student at UT Austin studying climate policy.
I’m Raymond Puzio, I learned about Emacs back around high school and have been using it since then; I’ve been active in Emacs meetups, and I use it in research in science.
I’m Joe Corneli, I also started using Emacs in high school, now I use it for a lot more things than I did.  My research background is in mathematics and online communities.
#+end_quote

*** PRELUDE                                                            :1m:
#+begin_quote
The four of us met at EmacsConf 2020 with a common interest in Emacs
and research.  We’ve met almost every week since then, because we
wanted to keep the conversation going.  In this short talk, we share
information about the methods we use, making a case for other people
getting together and creating their own small research communities
similar to ours.

Here’s the outline of our talk: We’ll tell you technologies we use in
our meetings, and demo a part of our meeting, as well as explain the
processes that we use when conducting our meetings to have a deeper
understanding of what we’re talking about.  Finally, we’ll talk about
what came out of these meetings: we wrote a paper for PLoP 2021 and we
designed a workshop using the knowledge we created together.  This has
brought us to the importance of collaboration, and we have some
lessons about how you can create a research community similar to ours.
#+end_quote

*** BACKGROUND + TECHNOLOGY                                            :2m:
**** Emacs Research Group
#+begin_quote
You’ll have noticed that we all have different research backgrounds.
We think that transdisciplinarity is important for solving big
problems.  If you’re going to have people from different research
backgrounds talking to each other, they need some scaffolding in both
tools and methods to help them have good conversations.  Of course, as
Emacs users, we wanted Emacs at the centre of that.  Being in a
meeting taking real-time notes with Emacs realises a dream that some
of us have been entertaining (and experimenting with) for a while.
The package crdt.el by Qiantan Hong makes this easy.  We take notes on
our meetings using Org Mode.  Since we’ve seen this before in talks on
reproducible research, Leo’s the maintainer of Org Roam, it’s
particularly natural choice.  For one thing, it allows us to quickly
put our notes online using Git and the static site generator Firn.
Lastly, of course, we need a real-time meeting tool and for that
purpose we use BBB in our weekly sessions (in fact, the same server
used by EmacsConf, thanks again to Leo).  All of these tools are
free/libre/open source (though BBB has some intensive hardware
requirements).

#+end_quote

*** PRERECORDED DEMO                                                   :2m:
#+begin_quote
Here’s a short prerecorded snippet from one of our recent meetings so
that you can get a sense of how our meetings look and feel.
#+end_quote

*** PROCESS                                                             :2m:

**** Organising metaphor
#+begin_quote
In the demo you saw a very improvised free-flowing conversation.  In
order to have this kind of conversation and still get things done, we
need a pretty rigorous structure in place at the bigger scale of the
meetings.  This involves both a timetable for the meetings, and some
review and planning processes [!].
#+end_quote

**** Timetable
#+begin_quote
Leo: The meetings generally follow a structure of informal checkins
followed by any announcements, at most two topics (with a break in the
middle) and a review of what happened at the end, followed by a quick
checkout.  The whole thing takes two hours in total.  We meet weekly,
and the consistency is really important for how the group works.
#+end_quote

***** Project Action Review
#+begin_quote
Joe: At the end of every meeting we ask and answer a series of
questions adapted from the ‘After Action Review’ developed by the US
Army in their training programs, and used in some business contexts.
The adaptation here came out of the Peeragogy project which I’ve been
involved with since 2012, and it’s designed to be less hierarchical
than the AAR.  By writing down and sharing these reviews we create a
resource for further peer learning later down the line.
#+end_quote

#+begin_src 
EXAMPLE
1. Review the intention: what do we expect to learn or make together?
2. Establish what is happening: what and how are we learning?
3. What are some different perspectives on what’s happening?
4. What did we learn or change?
5. What else should we change going forward?
#+end_src

***** Causal Layered Analysis
#+begin_quote
Joe: Every six weeks or so, we analyse the action reviews using a
four-layer framework to better understand the underlying themes that
surface in the reviews, and develop the deeper motivations for our
ongoing work together.  This helps us get a big-picture sense of where
we are going that we keep up to date at a slower pace than the weekly
meetings.  This also helps us tie our work into a broader context and
gives us some hope that over time we can contribute to solving big
problems.  Transdisciplinarity is important, but we need to know how
what we’re doing fits into the bigger context.
#+end_quote

#+begin_src 
EXAMPLE
1. Litany
2. System
3. Worldview
4. Myth
#+end_src

***** Design Patterns and Next steps
#+begin_quote
Ray: Going back to solving larger problems: when we carry out the analysis
we don’t just think about what happened in the previous meetings, but we
also take the longer view, thinking about things like structuring a
community of collaborators, or building platforms for scientific research.
We want to think about how what we’ve been doing fits into broader
historical patterns and trends.  In the past, the pattern is a historical
pattern; in the present we contextualise what we’ve learned; towards the
future we augment our big-picture analysis with next steps.  This helps us
keep things on track.  (We keep our patterns collated with a developing
design pattern language from the Peeragogy project.)


#+end_quote

#+begin_src 
EXAMPLE
1. Context
2. Problem
3. Solution
4. Next steps
#+end_src
*** OUTCOMES                                                             :2m:
**** We looked at user experience and development together to see how the process went together and where the gaps are
- Specifically looking at how maintainers and users can relate well
- This touches back to the beginner experience
**** We had some guest sessions
- We did have guests, some of whom we’re still coordinating with
- We have in mind some future sessions (like bringing together an experienced Vimmer with an Evil maintainer)
**** We compared Emacs with other platforms, not just at the technical level but at the user experience level
- Trying to understand how and why people use things (like RStudio and Roam Research)
- We’ve got some intermediate results
**** Coming up with methods that other people can use for organizing their own meetings
- This has several strengths to it
- One argument for it is that we put together a paper even though we all come from different methods, with different trainings, and somehow miraculously got together and build a shared language that allowed us to produce this paper.
- We combined not just methods but also people and their different.  Our tools got us talking /to/ one another, but our methods got us talking /with/ one another.
**** The PLoP paper: Patterns of Patterns 
#+begin_quote
We wrote a paper for the Pattern Languages of Programs conference that
sums up the way we work in ERG, together with co-authors from the
Peeragogy project.  We contextualise our work relative to other
communities.
#+end_quote

#+begin_src 
Abstract: The purpose of this paper is to show how we can combine and
adapt methods from elite training, future studies, and collaborative
design, and apply them to address significant problems in social
networks. We focus on three such methods: we use Action Reviews to
implement social perception, Causal Layered Analysis to implement
social cognition, and Design Pattern Languages to implement social
action. To illustrate the methods in combination, we first develop a
case study, showing how we applied them to bootstrap a distributed
cross-disciplinary research seminar. We then use Causal Layered
Analysis to explore the ways in which the design pattern discourse has
been evolving. Building on these analyses, we elaborate several
scenarios for the future use of design patterns in large-scale
distributed collaboration. We conclude that the combination of methods
is robust to uncertainty -- by supporting adaptations as circumstances
change -- and that they can help people coming from different
backgrounds work together. In particular, we show how methods drawn
from other domains enrich and are enriched by design patterns; we
believe the analysis will be of interest to all of the communities
whose methods we draw upon.
#+end_src

**** Workshop design included in the paper and we think it may have a convincing future 
- The workshop design helps us understand real-time roles
- The roles are linked with the methods described above

#+begin_src 
EXAMPLE
1. Kaiju Communicator — Problems emerging in a scenario
2. Historian — System of how we got there
3. Analyst — Analysis of the activity
4. Designer — Next steps
#+end_src

**** Overall PAR of Season Zero
#+begin_quote
Here’s how we’d sum up our work so far, and how we see the next steps.
#+end_quote
***** 1. Review the intention: what do we expect to learn or make together?
- NA: What are the questions we haven’t answered yet?
***** 2. Establish what is happening: what and how are we learning?
- RP: What are the reasons we’re doing this at all?  If we’ve been doing it for a year,
- We’re not going to claim that we’ve solved those problems, but if we keep going, and we get people inspired to work on this with us or on their own.
***** 3. What are some different perspectives on what’s happening?
***** 4. What did we learn or change?
***** 5. What else should we change going forward?

*** CONCLUSION                                                         :1m:
#+begin_quote
We’ve decided that "going public", for now, means sharing this talk.
#+end_quote

