#+TITLE: EmacsConf 2021 Speakernotes
#+Author: Noorah Alhasan, Joe Corneli, Raymond Puzio, Leo Vivier
#+roam_tag: HI
#+FIRN_UNDER: erg
# Uncomment these lines and adjust the date to match
#+FIRN_LAYOUT: erg-update
#+DATE_CREATED: <2021-10-30 Sat>

* Tech notes

* Agenda                                                               :85m:
** EmacsConf: Storyboarding                                            :35m:
*** ----------------------------------------
*** PRELUDE                                                             :1m:
#+begin_quote
I’m Leo, and you’ll have had me introduced at the beginning of the
conference; you might know me from Org Roam; I studied literature at
University.

I’m Raymond Puzio, I first learned about Emacs and Lisp at an
enrichment program for high school students.  When studying physics at
the university, I used Emacs and TeX to write mathematical documents.
Later on, I became active in Lisp and Emacs user groups where, among
other things, I learned about org mode for reproducible research.
Nowadays, I am working on synthesizing emacs and other programs into
an end-to-end platform for scientific research and collaboration.

I’m Joe Corneli, I also started using Emacs in high school in a course
on C programming and now I’m technically a computer scientist.  My
research background is in mathematics and online communities.

Hi, I’m Noorah Alhasan, I’m a member of the ERG group, and a PhD
student at UT Austin studying climate policy.
#+end_quote

#+begin_quote
Noorah: The four of us met at EmacsConf 2020 with a common interest in
Emacs and research.  We’ve met almost every week since then, because
we wanted to keep the conversation going.  In this short talk, we
share information about the methods we use, making a case for other
people getting together and creating their own small research
communities similar to ours.

Here’s the outline of our talk: We’ll tell you technologies we use in
our meetings, and demo a part of our meeting, as well as explain the
processes that we use when conducting our meetings to have a deeper
understanding of what we’re talking about.  Finally, we’ll talk about
what came out of these meetings: we wrote a paper for PLoP 2021 and we
designed a workshop using the knowledge we created together.  This has
brought us to the importance of collaboration, and we have some
lessons about how you can create a research community similar to ours.
#+end_quote

*** BACKGROUND + TECHNOLOGY                                              :2m:
**** Emacs Research Group
#+begin_quote
Leo: You’ll have noticed that we all have different research
backgrounds.  We think that transdisciplinarity is important for
solving big problems.  If you’re going to have people from different
research backgrounds talking to each other, they need some scaffolding
in both tools and methods to help them have good conversations.  Of
course, as Emacs users, we wanted Emacs at the centre of that.  Being
in a meeting taking real-time notes with Emacs realises a dream that
some of us have been entertaining (and experimenting with) for a
while.  The package crdt.el by Qiantan Hong makes this easy.  We take
notes on our meetings using Org Mode.  Since we’ve seen this before in
talks on reproducible research; also since I am the maintainer of Org
Roam, it’s particularly natural choice.  For one thing, it allows us
to quickly put our notes online using Git and the static site
generator Firn.  Lastly, of course, we need a real-time meeting tool
and for that purpose we use BBB in our weekly sessions (in fact, the
same server used by EmacsConf).  All of these tools are
free/libre/open source (though BBB has some intensive hardware
requirements).

#+end_quote

*** PRERECORDED DEMO                                                     :2m:
#+begin_quote
Joe: Here’s a short prerecorded snippet from one of our recent
meetings so that you can get a sense of how our meetings look and
feel.
#+end_quote

*** PROCESS                                                              :2m:

**** Organising metaphor
#+begin_quote
Noorah: In the demo you saw a very improvised free-flowing
conversation.  In order to have this kind of conversation and still
get things done, we need a pretty rigorous structure in place at the
bigger scale of the meetings.  This involves both a timetable for the
meetings, and some review and planning processes [!].
#+end_quote

**** Timetable
#+begin_quote
Leo: The meetings generally follow a structure of informal checkins
followed by any announcements, at most two topics (with a break in the
middle) and a review of what happened at the end, followed by a quick
checkout.  The whole thing takes two hours in total.  We meet weekly,
and the consistency is really important for how the group works.
#+end_quote

***** Project Action Review
#+begin_quote
Ray: At the end of every meeting we ask and answer a series of
questions adapted from the ‘After Action Review’ developed by the US
Army in their training programs, and used in some business contexts.
The adaptation here came out of the Peeragogy project which I’ve been
involved with since 2012, and it’s designed to be less hierarchical
than the AAR.  By writing down and sharing these reviews we create a
resource for further peer learning later down the line.
#+end_quote

***** Causal Layered Analysis
#+begin_quote
Joe: Every six weeks or so, we analyse the action reviews using a
four-layer framework to better understand the underlying themes that
surface in the reviews, and develop the deeper motivations for our
ongoing work together.  This helps us get a big-picture sense of where
we are going that we keep up to date at a slower pace than the weekly
meetings.  This also helps us tie our work into a broader context and
gives us some hope that over time we can contribute to solving big
problems.  Transdisciplinarity is important, but we need to know how
what we’re doing fits into the bigger context.
#+end_quote

***** Design Patterns and Next steps
#+begin_quote
Ray: Going back to solving larger problems: when we carry out the
analysis we don’t just think about what happened in the previous
meetings, but we also take the longer view, thinking about things like
structuring a community of collaborators, or building platforms for
scientific research.  We want to think about how what we’ve been doing
fits into broader historical patterns and trends.  In the past, the
pattern is a historical pattern; in the present we contextualise what
we’ve learned; towards the future we augment our big-picture analysis
with next steps.  This helps us keep things on track.  (We keep our
patterns collated with a developing design pattern language from the
Peeragogy project.)
#+end_quote

* PROJECTS                                                              :2m:
** Summary
#+begin_quote
Leo: Here are some of the projects we’ve been working on.
- Specifically, we’ll tell you about a paper we wrote, a workshop that
  we piloted, and a user study that we’ve started.
- And we’ll say a little more about the context we’re working in.
#+end_quote

** Patterns of Patterns (PLoP 2021)                                 :LITANY:
#+begin_quote
Noorah: We coauthored a paper that touches on all of the topics we mentioned
earlier, and presented it at the leading conference on Design Patterns
for programs and programming.  One of the case studies in the paper
sums up the way we work in ERG.  The paper puts ERG in context with
other peer learning communities, and we aim describe our way of
working in a way that others would find accessible and potentially
useful.
#+end_quote
** PLACARD Workshop roles                                           :SYSTEM:
#+begin_quote
Noorah: We are also developing an interactive workshop based on the ideas in
the paper, which we piloted at the PLoP conference.  Our intent with
the with the workshop was to build a method for rapid problem solving,
which could, at least in principle, expand beyond the workshop setting
to distributed networks.  The workshop involves made-up roles—like a
kaiju communicator who helps understand problems as they arise.  We
realised that it has given us a lot of wealth for thinking about the
roles we take on in our real-world workshops.
#+end_quote
** Initial user studies                                          :WORLDVIEW:
#+begin_quote
Ray: Free software may be lacking on ‘user’ aspects: people often program
to scratch their own itches, and assume others will do the same.

- We looked at user experience and development together to see how the
  process went jointly and where the gaps are.
- We compared Emacs with other platforms, not just at the technical
  level but at the user experience level as well.
- We had some guest sessions, where we’ve started gathering user
  stories.

Building on these conversations we would like to do more research in all these
and eventually be able to say:

- ‘If you are someone who does X, these are the packages that would
  work for you’
#+end_quote
** Broader context                                                    :MYTH:
#+begin_quote
Ray: Our PLoP paper and the plans it contains become a /template/ for
some of the other things we want to work on as we go forward.  If we
imagine things in 2–3 years, what would it take to realise that vision
in the paper?

- Thinking about the future: this is one of the main reasons why we
  want to share these ideas and invite other people into this way of
  working: there’s no way we can achieve everything in our vision all
  by ourselves.
- What we’ve been focusing on in Season Zero is methods that other
  people can use for organizing their own research groups.
#+end_quote
* CONCLUSION
#+begin_quote
We decided to share this talk so that folks can learn from our
community.  Our goal has been to share how we’ve been doing things and
we hope this information is useful for you in your own communities and
collaborations.
#+end_quote

