:PROPERTIES:
:ID:       0f9e1955-845f-419d-bb55-70051d5df2c3
:END:
#+title: Rebalance social services
#+filetags: :HL:BF:

* Problem summary

Some behaviours require policing, however, if the balance is incorrect, then self-expression suffers.  Similarly, other welfare-related services should be supplied in balance with local needs, though they often are not.

* Solution strategy

Police and other social services exist to deal with problems which are not addressed on their own, HOWEVER in the right environment, criminality, disease, etc., either go away entirely or shrink to a minimum.

BECAUSE there is a limited amount of funding for public services, communities are now faced with dilemmas like closing the library to pay for the park, or removing bus services to pay for police, etc.; and, in fact, the police are already having to deal with a range of social problems which aren’t strictly within their remit, as are teachers and other service providers.  Whereas there used to be a /community policeman/ who could act with discretion, police officers now are oftentimes are not members of the communities they are meant to serve.  Other service provision can feel similarly remote and disconnected.

THEREFORE, what’s needed are more people in the community who provide good examples of — and paradigms for — action, more immediately and directly.  One strategy to pursue would be to arrange it so that the organisations that provide welfare services are connected with each other.  Much in the way that food co-ops can serve the alimentary needs of a community, other more integrated systems could be devised to tackle the structural issues that made apparent by current regimes of underfunding and disorganisation.  For example, Houston, Texas, significantly reduced homelessness by developing a continuum of care approach.  Other societal challenges might be addressed similarly.

SPECIFICALLY, it may be possible, in Bristol, to create a /radical public space/ that is taken care of by local people, which provides a range of relevant services.  Some good examples of community centres already exist, though they aren’t yet widespread into all of the communities that need them.  This could be an example of [[id:570f3d11-d1f6-4ffb-87ed-c815e7efe624][Communal spaces]].  However, there’s more than just a ‘space’ aspect to such a place.  Organisations like Médicins Sans Frontièrs show that experts are willing to activate around identified needs: can varied expertise be integrated in a similar way to address complex local challenges?

This strategy relates to the concept of /facilitator load/ that Abby talked about in the Bristol workshop.  As such we have an experience inside the workshop of (potentially) too many things to think about and an over-extended service provision.  This relates to the concept of [[id:80a6488b-af62-4340-b542-eecb6b922343][Volatility]].
