#+Title: Analyst’s Handbook
#+BIBLIOGRAPHY: /home/joe/flaws/main.bib
#+LATEX_HEADER: \usepackage{natbib}

* Introduction to Causal Layered Analysis
<<CLA_patterns>>

Sohail Inayatullah developed Causal Layered Analysis (CLA) as a
research methodology for examining a topic of concern at four layers
that he refers to as the /litany/, /system/, /worldview/ and /myth/.  In
developing a CLA, none of the four layers is privileged over the
others, nor are they examined in isolation.  Rather, one moves between
them, examining how they relate to one another.  One can then
integrate these insights to form a more comprehensive basis for
understanding what is happening in the present and for anticipating
the future.  The tables below describes each of the four layers
according to the following schema:

- *Contents*: /What is found in this layer?/
- *Analysis*: /Techniques for analysis of this layer./
- *Literature*: /Instances of texts which are typically operative at this layer./

To further illustrate the four layers and show how such an analysis
might proceed, we present two examples in the following sections.

#+CAPTION: Litany
| Contents | Observable facts, events, and quantitative trends.|
| Analysis | Minimal processing of data. |
| Literature | News reports, tax filings, chit-chat. |

#+CAPTION: System
| Contents   | The social, economic, political, and historical forces which shape events. |
| Analysis   | Technical explanations and interpretation of data within a given paradigm. |
| Literature | Editorials and policy institute reports.                                   |

#+CAPTION: Worldview
| Contents   | Core values and attitudes which motivate choices and actions.                                                                                                                                       |
| Analysis   | Uncover deep assumptions and study the mental and linguistic constructs which undergird how people interact with each other and their surroundings.  Compare and critique paradigms and discourses. |
| Literature | Works of philosophy and critical theory.                                                                                                                                                            |

#+CAPTION: Myth
| Contents   | The symbols and tales which give meaning to life.                                      |
| Analysis   | Study symbols and narratives, and the myths and rituals within which they participate. |
| Literature | Poetry, art, anthropology, Jungian analysis.                                           |

* Ashmolean example

** Litany
An (gasp!) Evil Genius has occupied the Ashmolean museum.  All
entrances are barred shut, noone can get in or out.  For a few weeks
this persists---despite efforts at blockading the premises and
shutting off utilities, somehow the occupiers are not being starved
out and are not letting up.  The press and the authorities are baffled
as how and why this is going on!  It seems that the occupiers are not
interested in making public statements or demanding ransom or anything
of the sort---apparently all they want to do is to have the museum to
themselves and camp out there.  After a few week, documents from the
museum and detailed plans and images of artefacts from the museum
circulate on the web and museum-quality replicas of artefacts from the
Ashmolean appear in third-world countries.

** System
Advances in scanning and printing technology make it possible to
produce copies of artefacts indistinguishable form the original.
Moreover, since the information is stored and transmitted digitally,
anyone with a suitable printer anywhere can make themselves a copy.  A
system of tunnels allowed the occupiers to evade the blockade and keep
themselves supplied.  The security system originally designed to keep
terrorists from damaging the priceless treasures was instead used to
protect the "terrorists" against the "authorities" "besieging" the
museum.

** Worldview
At the bottom of this, there is a clash of worldviews.  What is an
artefact: Is it an object which plays a role in rituals and gift
networks?  Is it a source of data for scientific investigations of the
past?  Is it a part of an artistic and cultural heritage?  Who should
own the artefact: The heirs of the people who originally made it?
Those with the power and wealth to acquire it?  Those who have the
facilities to curate and study it?  Where is the value: Is it
spritual?  Is it social?  Is it economic?  Is it scientific?  Is it
artistic?  Does it specially inhere in the original or can a copy
share in the value under certain circumstances?

** Myth
There is a corresponding clash/clang of myths.  We have the myths of
the people who made the artefact and the metaphors which it expressed
for them.  We have the "manifest destiny" and "white man's burden"
myths of the colonizers who collected the artefacts and sent them to
the museum.  We have the more secular myths of people who admire,
study and care for the artefacts in the museum today, treasuring them
as expressions of the human spirit which continue to serve as a source
of meaning and inspiration.

* Applying CLA thinking to critiquing the Cooling the Commons patterns

The 41 patterns they have developed include examples like \textsc{The Night-Time Commons}
which:

#+begin_quote
… might shift daytime activities into cooler night times. Some places
already have these patterns: night markets and night-time use of
outdoor spaces. If locally adapted versions of these patterns
encourage people to adopt new habits, other patterns will be
needed. These will include, for example, ways to remind those cooling
off outdoors in the evening that others might be trying to sleep with
their naturally ventilating windows open. Such interlinked patterns
point to the way pattern thinking moves from the big scale to the
small.
#+end_quote

Reading this, we were concerned that, while the Cooling the Commons
patterns do acknowledge “horizontal complexity”—namely, through
interlinked patterns—the process does not deal with the “vertical
complexity” coming from the fact that diurnal rhythms are deeply
embedded in biology and culture. People have cultural beliefs about
the activities that are appropriate for different times of day. Public
and domestic rituals are organized about the daily cycle. Times of day
have symbolic associations. As far as we could tell, these authors
focused on more or less technical issues at the systems level, and did
not acknowledge these issues at the worldview and myth levels. A more
comprehensive approach might, for instance, re-examine rituals to see
which of them relate to the phenomenon of sunrise versus the act of
getting up and starting the day, and then figuring out how to adapt
these rituals to a new schedule. A suitable research strategy might be
to study how practices changed in the past, as with the introduction
of industrialization and its clockwork regimentation of the day.

* The end                                                           :ignore:

#+begin_export latex
\bibliographystyle{plain}
\bibliography{./main}
#+end_export
