* Flaws of the smart city via CLA

* Flaws of the smart city via CLA: Litany
(Gasp!) An Evil Genius has occupied the Ashmolean museum.  All
entrances are barred shut, noone can get in or out.  For a few weeks
this persists---despite efforts at blockading the premises and
shutting off utilities, somehow the occupiers are not being starved
out and are not letting up.  The press and the authorities are baffled
as how and why this is going on!  It seems that the occupiers are not
interested in making public statements or demanding ransom or anything
of the sort---apparently all they want to do is to have the museum to
themselves and camp out there.  After a few week, documents from the
museum and detailed plans and images of artefacts from the museum
circulate on the web and museum-quality replicas of artefacts from the
Ashmolean appear in third-world countries.
* Flaws of the smart city via CLA: System
Advances in scanning and printing technology make it possible to
produce copies of artefacts indistinguishable form the original.
Moreover, since the information is stored and transmitted digitally,
anyone with a suitable printer anywhere can make themselves a copy.  A
system of tunnels allowed the occupiers to evade the blockade and keep
themselves supplied.  The security system originally designed to keep
terrorists from damaging the priceless treasures was instead used to
protect the "terrorists" against the "authorities" "besieging" the
museum.(edited)
* Flaws of the smart city via CLA: Worldview
At the bottom of this, there is a clash of worldviews.  What is an
artefact: Is it an object which plays a role in rituals and gift
networks?  Is it a source of data for scientific investigations of the
past?  Is it a part of an artistic and cultural heritage?  Who should
own the artefact: The heirs of the people who originally made it?
Those with the power and wealth to acquire it?  Those who have the
facilities to curate and study it?  Where is the value: Is it
spritual?  Is it social?  Is it economic?  Is it scientific?  Is it
artistic?  Does it specially inhere in the original or can a copy
share in the value under certain circumstances?
* Flaws of the smart city via CLA: Myth
There is a corresponding clash/clang of myths.  We have the myths of
the people who made the artefact and the metaphors which it expressed
for them.  We have the "manifest destiny" and "white man's burden"
myths of the colonizers who collected the artefacts and sent them to
the museum.  We have the more secular myths of people who admire,
study and care for the artefacts in the museum today, treasuring them
as expressions of the human spirit which continue to serve as a source
of meaning and inspiration.
