#+TITLE: 🐉 vs 🐒: KAIJŪ Communicator Handbook

* FLAWS OF THE SMART CITY: CONTENTS

Designed by Design Friction — VERSION 1.3 — October 2016

Built on works from Adam Greenfield, Dan Hill and Anthony Townsend.

Released under the CC-BY-NC-SA license.

** 4 RULES

Guardian Angel, Evil Genius, Blank, Blank

** 16 ACTIONS

Gamify, Visualize, Make accessible, Humanize, Track, Reduce, Contain,
Tinkering, Slow Down, Co-Brand, Oversimplify, Disconnect, Animalize,
Weaponize, Blank Card, Blank Card

** 16 PLACES

Shopping Streets, Public Park, Convenience Store, Kiosk, Main Square,
Public Toilet, Social Housing, City Hall, Public Library, Parking Lot,
Train Station, Museum, Place Of Worship, Highway, Blank Card, Blank
Card

** 16 ISSUES

Loss Of Privacy, Proprietary Ecosystem, Embedded Vulnerability,
Infrastructure First, Missing The Human Scale, Centralized Power,
Decontextualized, Greenwashed, Algorithmic Religion, Key To The City,
Data Blind Spots, Unempowered Citizens, Coded Obsolescence,
Authoritarian Setup, Blank Card, Blank Card


* THE ISSUES CARDS

A «Issue» card describes one of the common flaws encountered in the
existing or planned Smart Cities.  Each card shortly documents the
core of the issue and stakes related to this flaw.

* THE ACTIONS CARDS

A «Action» card describes one of the interventions that could happen
in the urban space. They can worsen as well as fix the issue. Each
action leads to a reaction, so remember to find the right balance
between positive and negative impacts.

* THE RULES CARDS

A «Rule» card defines the setup of the game. You can either play with
the basic rules or create your own.

* THE PLACES CARDS

A «Place» card defines a location in the urban space that could be
affected by the flaws of the Smart City. Some of these places are
already part of programs connecting cities, whereas others appear to
be grey areas, neglected in the effort in improving the urban
infrastructure.

* ¶ RULES

* 📖 #1 GUARDIAN ANGEL

You are the guardian angel of the Smart City. In each issue, you see a
flaw that can be repaired.

In this mode, you have to imagine how the action may solve the issue
in relation with the specific place of the city you have chosen. Your
solution has to generate positive externalities for the whole society.

* 📖 #2 EVIL GENIUS

You are one of the most prolific evil geniuses in town. In each issue,
you see a potential flaw that, if exploited, could unleash chaos in
the streets.

In this mode, you have to imagine how the action may aggravate the
issue when linked with this particular place of the city. Your
solution has to generate negative externalities for the entire
community or for a specific population.

* 📖 #3 BLANK RULE

* 📖 #4 BLANK RULE

* ¶ ACTIONS

* ⚙ #1 GAMIFY

Make it a game.  Set achievements.  Earn points and badges.  Impose
the reign of fun.  A gamified solution can foster motivation and
involvement as well as constraining citizens’ behavior by telling them
what has to be done and what is considered a success.

* ⚙ #2 VISUALIZE

As social and physical environments are getting more and more complex,
they may lack legibility.  Making it visual succeeds when words fail
to represent intricacies or to catch the attention of an audience.
Visualizing reveals hegemonic processes and can highlight unexpected
hidden interactions.  But is it good to make everything transparent?

* ⚙ #3 MAKE ACCESSIBLE

While digital and physical touchpoints are becoming more diverse
across our life and our experience of the city, the simple fact of
ensuring access is a first step towards equity.  Then, there is the
question of levels of access. Is it only about to be able to see
something, to go somewhere or also to be able to have an impact on a
situation?

* ⚙ #4 HUMANIZE

Make it more human.  This could mean to add a sense of community,
desires or sensitive feedback, but also an ounce of irrationality,
unpredictable emotions and antisocial behavior.  It definitely could
bring a new layer of unavoidable complexity.

* ⚙ #5 TRACK

Using digital devices and connected objects leaves traces. They are
persistent artifacts of both our digital and physical presences in the
hybrid urban spaces.  These traces can be tracked and then
recorded. Tracking and aggregating them may lead to anticipation and
control.

* ⚙ #6 REDUCE

Big buildings, big infrastructure and big ambitions. Things tend to
grow, but the human scale remains unchanged. They are the symbol of
our desire for an infinite expansion.  Is it worth to see things a bit
smaller?

* ⚙ #7 CONTAIN

New territories mean new identities, new identities mean new barriers
and new borders. Containment has for long become a strategy to set
points of reference, lines to not cross and elements to restrain.
What or who will you contain?  For what purpose?

* ⚙ #8 TINKERING

Nowadays, things are programmed to go straightforward, not meaning
they head for the right direction.  You might help to set things right
by hacking, tweaking, interfering and adding some glitches in the
current processes. Start from the existing blocks and reconfigure them
with your own adjustments.

* ⚙ #9 SLOW DOWN

Everything is going faster.  This is not even a cliché anymore.
Immediacy has become both a technological and a cultural expectation
for connected things. What could be the outcomes if some processes
were slowed down?

* ⚙ #10 CO-BRAND

Good news, you are a brand.  Bad news, everything has become kind of a
brand.  Marketing and brand content are pervasive and persuasive. As
brands are joining forces in some unique ventures, what could be the
next unexpected association in town?

* ⚙ #11 OVERSIMPLIFY

Simplification is a necessity, but also a defense mechanism when
having to handle a complex situation.  Oversimplification may be
driven by a lack of time, attention or rigor.  Downside, it could lead
to a wrong perception of reality.  But seriously, who likes to deal
with complex situations?

* ⚙ #12 DISCONNECT

Cut it off from the network, from people, from space or from time.
Think disconnection as an act of resistance or as an unwanted and
endured situation.  It is time to unplug things and people from the
grid.

* ⚙ #13 ANIMALIZE

Forget about civilization.  Unleash nature.  Release wildness.  Make
it instinctive and primitive.  Bring the animal back in the game.

* ⚙ #14 WEAPONIZE

Basically, it is all about turning something into a weapon, on purpose
or not. Then, it grows into an instrument of power, reshaping
established relations.  Just remember, a weapon serves two goals,
defense and attack.  Which one would it be?

* ⚙ #15 BLANK ACTION

* ⚙ #16 BLANK ACTION

* ¶ PLACES

* 📍 #1 SHOPPING STREET

Before malls, there were shopping streets. Welcome to open-air
streetside stores, offering both local products and global brands.
Competition is harsh, some stores will survive while some others
disappear without leaving any trace.

* 📍 #2 PUBLIC PARK

A green spot for recreational use and a conservation area for flora
and fauna. Some of them even have nice playgrounds and highly
allergenic pollen.

* 📍 #3 CONVENIENCE STORE

For all the last-minute grocery shoppers out there.  Affordable
products for everyday emergencies, longer opening hours, and a unique
charm.

* 📍 #4 KIOSK

The smallest unit for commercial or informational purposes in the
urban environment.  Kiosks are also known to be hideouts for ill-used
public touch screens.

* 📍 #5 MAIN SQUARE

Usually, located not very far away from the town hall and getting
really crowded on celebration days.  Also known as the best place in
town for protests and demonstrations.

* 📍 #6 PUBLIC TOILET

Not the most glamorous place in the city, but still one of the most
badly needed.  Public toilets provide a large range of hygienic
issues, from bad smells to drug use. However, they are also a place of
curious rituals such as posting classified or personal ads.

* 📍 #7 SOCIAL HOUSING

Affordable housing provided by State or non-profit organizations.  In
the old days, it was a progressive solution supporting social equity.
Today, it is likely to be viewed as a neglected piece of the urban
infrastructure, only depicted as a synonym for social troubles.

* 📍 #8 CITY HALL

Where decisions are made.  It hosts the representative governance of
the city.  It can reflect both the embodiment of a personified power
and the place where transparency, accountability and collaboration
stand for actionable values.

* 📍 #9 PUBLIC LIBRARY

A place where everyone can access knowledge for free and without
having one’s personal data sold.  There are even rules to follow
there, a bit old-fashioned if you ask.

* 📍 #10 PARKING LOT

Cars are still part of the urban landscape, with or without drivers.
So are parking lots, being set in plain sight or buried underground.
And what about a parking for bikes?

* 📍 #11 TRAIN STATION

The main urban transportation hub, but also a small-scale city.  It
appears to be an inextricable mesh of accelerations and pauses, served
by commercial services and supported by efforts to maintain a rational
and efficient system.

* 📍 #12 MUSEUM

Storing and showing artifacts which are not always coming from the
past.  More than any other place in the city, museums are facing
questions about the transformation of spaces into lines of code as
well as the challenges of digitizing physical artifacts.

* 📍 #13 PLACE OF WORSHIP

As it was one of the foundations of antic cities, the architecture of
places of worship keeps being a constant crossover between
functionalism and spirituality.  Temples, churches or mosques have
been built as places for serenity, but age-old conflicts turned them
into lightning rods for anger.

* 📍 #14 HIGHWAY

Public ways, mostly roads, accessible for everyone.  These lanes are
shared between an eclectic range of modes of transportation modes such
as cars, drones, bikes, horses and even pedestrians.  Yesterday ruled
by laws, tomorrow by computer code.

* 📍 #15 BLANK PLACE

* 📍 #16 BLANK PLACE

* ¶ ISSUES

* ⚡ #1 LOSS OF PRIVACY

By embedding sensors in the streets, the Smart City is under constant
surveillance; monitored by public forces and private interests.  Being
able to track and record activities has erased the notion of anonymity
promised by the urban structure and the crowd. Targeting marginality
with these tracking systems is allowing to get rid of, physically and
digitally, a specific population in a specific area.

* ⚡ #2 PROPRIETARY ECOSYSTEM

Smart City logic is oriented on a proprietary philosophy.  Using
closed standards, it carefully picks whom to deal with among a list of
designated institutional and business organisations or NGO.  This is a
locked environment led by market forces and strict partnerships, not
by a collective experience.  Don’t expect the permission to hack, to
tweak or to fork the smart systems.

* ⚡ #3 EMBEDDED VULNERABILITY

By integrating technologies into the urban fabric, it is bringing an
intrinsic fragility to infrastructure initially protected from this
vulnerability.  In addition to the inherent risks of cyber-attacks,
the absence of flexibility in the hardware and the lack of
interoperability between the digital standards are leading to fatal
errors.  In every meaning of the word.

* ⚡ #4 INFRASTRUCTURE FIRST

Smart City programs envisage the city as a concrete structure only.
Soft textures of the city, such as subculture or invisible public are
conscientiously forgotten. A Smart City is focused on efficiency as a
final goal, not as a means to develop common goods. But a city goes
beyond a simple ensemble of commodities and for sure deserves more
than the promises of security, convenience or efficiency.

* ⚡ #5 MISSING THE HUMAN SCALE

Designing the city smarter often means observing people behaviors from
a bird’s-eye view, without focusing on the everydayness and the
individual. It is missing the messiness of humanity, which will
inevitably jam the quest for a perfect logical urban system. City
builders are still learning that dealing with humans is all about
unpredictability, wildness, irrationality or digital illiteracy.

* ⚡ #6 CENTRALIZED POWER

Smart Cities feature the rise of situation rooms and control centers.
These closed places provide a topdown control of the infrastructure,
seeing the city through a dashboard.  This centralized control and
planning of urban facilities fail to stimulate incremental innovation
by third parties. It can be considered governance by control rather
than by community involvement.

* ⚡ #7 DECONTEXTUALIZED

From catalogs to streets, Smart Cities offer generic technologies
without really caring about their adaptation to a precise
context. Technological propositions from the Smart City provide
cultural codes which are not necessarily fitting together with local
values.  If Smart Cities visions are rooted in a culture, it seems it
is in a generic western lifestyle.

* ⚡ #8 GREENWASHED

Greenwashing is an operational strategy in the Smart City sales pitch.
With cities built from scratch and riddled with energy consuming
devices, self-sustainability should be more than ever a primordial
challenge.  The promises of smart grids don’t stand in front the
increase use of rare earth elements and their nonecological extraction
in faraway lands.

* ⚡ #9 ALGORITHMIC RELIGION

Data-based decision culture takes roots into the over-reliance on
digital technologies to solve social issues.  Algorithms may be
reassuring, but also create distance between policy makers and
citizens; since data don’t foster empathy.  Algorithms are not
neutral, they embed ideologies and values from their creators. There
is also a lack of transparency about which algorithms are used for
decision-making.

* ⚡ #10 KEY TO THE CITY

This is both a governance and a democracy issue. Who is in charge in
the Smart City? Elected representatives, technocrats, algorithms, or
private partners?  A Smart City is strongly dependent from its
contractors and from outsourcing the updates of the urban tech
infrastructure. It might lead to a lack of control in the
liberalisation of and privatisation of public services.

* ⚡ #11 DATA BLIND SPOTS

Data can’t see everything.  Even with a tight mesh of sensors, some
urban activities are slipping away. Data also carry internal biases
since they are a cultural construction, shaped by the choices made
during the collecting and parsing processes of data. Looking for
perfect knowledge is an unreachable goal, data providing only a biased
and incomplete view of society.

* ⚡ #12 UNEMPOWERED CITIZENS

Automation of the urban infrastructure is taking away responsibilities
from citizens.  Constraining behaviors with new kinds of reward or
rule systems envisages citizens as consumers only.  Smart City also
fails at the necessary training of citizens to ethical stakes implied
by tech in the city, preventing them from reclaiming control or
assessing the smart infrastructure.  So, what about smart citizens?

* ⚡ #13 CODED OBSOLESCENCE

Smart Cities are not so different from classical computers.  They are
going to need vital updates for their software and hardware
parts. Facing the challenge of getting old at the age of fast
technological evolution, Smart Cities should start to stockpile spare
parts to fix their future issues at the risk of becoming obsolete
quicker than ever.

* ⚡ #14 AUTHORITARIAN SETUP

The use of militarized technologies such as drones or sensors to make
streets safer could also undermine resistance or protests against a
local government. While security is becoming the main goal to fulfill,
digital defensible spaces and crowd control strategies find an echo in
the central management of city resources. Someone has already had his
finger on the urban kill switch.

* ⚡ #15 BLANK ISSUE

* ⚡ #16 BLANK ISSUE

* ¶ THE BIG IDEA

Flaws of the Smart City is a critical kit to explore the dark faces of
the so-called Smart Cities.

As any hardware or software piece, the connected cities embed flaws
and this kit aims to fix these weak spots or to exploit them to set
chaos.  The Flaws of the Smart City cards have been imagined in the
first place for designers, urbanists, public servants and even small
guys from big tech companies involved in the smart city business.

The content of the kit has been built on the thoughts and works from
Dan Hill (City of Sound), Adam Greenfield (Against the Smart City) and
Anthony Townsend (Smart Cities, Big Data, Civic Hackers, and the Quest
for a New Utopia).

* ¶ RULES OF ENGAGEMENT

This is a workshop-tailored kit. It has been created to foster
conversations during brainstorming sessions, to envisage provocative
concepts and to build scenarios for debates.

There are three main decks of cards:

- Issues, listing current and emerging flaws of smart city projects.

- Places, listing both common and forgotten urban spaces.

- Actions, listing interventions that could influence places and issues.

Here is an example of settings for a workshop using this kit:

1. Choose a city which will be used as a social, cultural, geographical and economical context for the exercise. It can be your hometown or a random location far away.

2. Select a game mode (see the cards of rules).

3. Assemble a card of each deck (Issue + Place + Action) and use them as a base for brainstorming. Imagine, speculate and define the new services or products related to the Flaws of the Smart City.  Add a flavour of fiction, embed ideas in everyday stories and tell how it will change urban environment as well as the society.

4. Variation: you may decide to split the discussion group according to two roles, one part focusing on causes and actions, the other focusing on reactions and consequences.

5. Document and share ideas or discussions triggered by this workshop.

* ¶ CREDITS

Designed by Design Friction — VERSION 1.3 — October 2016
Built on works from Adam Greenfield, Dan Hill and Anthony Townsend.
Released under the CC-BY-NC-SA license.

The cards from the Flaws of Smart City kit use the following icons:

- Book designed by Murali Krishna from the thenounproject.com

- Location designed by Ema Dimitrova from the thenounproject.com

- Lightning Bolt designed by Joe Mortell from the thenounproject.com

We encourage you to bring your own adjustments to the existing
material or to design new cards! We would also love to hear how you
used the kit and to know more about the outcomes, feel free to drop us
a line at info@design-friction.com or @design_friction on Twitter.

* APPENDIX: Previous pilot: KAIJŪ INTRODUCTION TO PEERAGOGY

Our workshop will introduce attendees to peeragogy: an interconnected
collection of techniques for peer learning and peer production. The
learning mind-set and strategies we are uncovering can be applied by
students, teachers, groups of friends, communities of practice,
hackerspaces, organizations, wikis, and/or networked collaborations
across an entire society! In this workshop we put peeragogy into
action as we break into small groups and play "Flaws of the Smart
City", a futures studies game that imagines scenarios for the
evolution of urban environments. After playing, each group will do a
Project Action Review to reflect on lessons learned. Subsequently, the
groups will present their PARs to the wider audience so everyone can
learn from their experience and extract patterns. Finally, all
attendees will "hive edit" a 500 to 1,000 word writeup of the workshop
that will be included in the upcoming fourth edition of the Peeragogy
Handbook.
* APPENDIX: SIXTY MINUTE WORKSHOP TIMELINE

- 3 Minutes 30 Seconds :: Video Intro to Peeragogy c/o Howard Rheingold [[https://www.youtube.com/watch?v=5cPNwpK1ctg][https://www.youtube.com/watch?v=5cPNwpK1ctg]]

- 6 Minutes 30 Seconds :: Overview of the workshop timeline and succinct description of the methods we will experiment with today — Project Action Review, Causal Layered Analysis, Design Patterns — as well as the rules of Flaws of the Smart City, allowing time for brief Q&A

- 30 Minutes :: Play Flaws of the Smart City in small teams

- 5 Minutes :: Each team does a Project Action Review

- 5 Minutes :: Each group presents their PAR about how their game went, we take notes into the CLA template

- 10 Minutes :: Hive-edit the CLA into a 500 to 1,000 word writeup of the experience to be included in the Peeragogy Handbook, including any design patterns that you noticed
* APPENDIX: WORKSHOP DESCRIPTION

#+begin_quote
The term kaijū translates literally as "strange beast". — Wikipedia
#+end_quote

Since we started working together in the Peeragogy Project in 2012, we
have used many methods to pursue our shared goal of learning more
about peer learning and peer production by practicing them together!
We modified the US Army’s After Action Review (2002) to create the
Project Action Review, as a way to cultivate shared mindfulness. We
have fed our reflections into futurologist Sohail Inayatullah’s Causal
Layered Analysis (1998) to create varied answers to the question ‘What
is our vision for change and how is progress measurable?’. Along the
way, we also experimented with patterns, poetry, and play. In this
one-hour workshop we will demonstrate the power of these and other
peeragogical methods with audience volunteers. To begin with, we make
the ‘audience’ disappear and replace it with a ‘concerned public’!

After a brief introduction to the methods mentioned above we will dive
into playing a game called *FLAWS OF THE SMART CITY* developed by the
Design Friction collective. We are now no longer watching a talk: we
are residents of a city that has begun to take on a mind of its own,
mediated by a Guardian Angel or an Evil Genius — or perhaps a giant
lizard with psychic powers, if you so choose.

We, as the concerned public, begin to relax into what we are doing
enough to not be distracted by other things. We do not have any
ulterior motives outside of the game. For example, when we are playing
Flaws of the Smart City, we are not particularly worried about paying
rent or publishing papers. We are not particularly worried about what
our tablemates think about us: it is a fun game but it is not that
serious. More or less we are embracing the phenomenon of being alive,
here and now.  To bring these ideas home through another sensory
channel, we suggest the song “[[https://www.youtube.com/watch?v=Y--5IlljO78][Shuffering and Shmiling]]” by Fela Kuti as
a background soundtrack for the game-playing portion of the workshop.

When we wrap up the game, each group will do a *PROJECT ACTION REVIEW*,
addressing these questions:

1. Review the intention: what do we expect to learn or make together?
2. Establish what is happening: what and how are we learning?
3. What are some different perspectives on what’s happening?
4. What did we learn or change?
5. What else should we change going forward?

We will then report back and take notes into a shared outline,
following the *CAUSAL LAYERED ANALYSIS* template provided by Inayatullah
(op. cit., p. 820):

- The first level is the ‘litany’—quantitative trends, problems, often exaggerated, often used for political purposes—(overpopulation, eg) usually presented by the news media.

- The second level is concerned with social causes, including economic, cultural, political and historical factors (rising birthrates, lack of family planning, eg).

- The third deeper level is concerned with structure and the discourse/worldview that supports and legitimates it (population growth and civilizational perspectives of family; lack of women’s power; lack of social security; the population/consumption debate, eg.).

- The fourth layer of analysis is at the level of metaphor or myth. These are the deep stories, the collective archetypes, the unconscious dimensions of the problem or the paradox (seeing population as non-statistical, as community, or seeing people as creative resources, e.g.).

Lastly, we will co-edit this outline into a mixed media product —
perhaps including narrative, poetry and images — reflecting on the
process we have just experienced through the lens of a concept
borrowed from religious studies (Batchelor, 2015): asking how does
Peeragogy differ from other approaches? As regards the mixed medium
presentation and experience as a whole, we take inspiration from the
poet and visual artist Marcel Broodthaers (quoted by Wyma, 2016):

#+begin_quote
“I am now able to express myself on the edge of things, where the
world of visual arts and the world of poetry might eventually, I
wouldn’t say meet, but at the very frontier where they part.”
#+end_quote

Towards this end, we will strive to introduce the concept of a DESIGN
PATTERN and exhibit them — in any reasonable format — in our writeup.

 - A path as a solution to reach a goal (Kohls, 2010)

 - Patterns are shared as complete methodic descriptions intended for
   practical use by experts and non-experts (Leitner, 2015)
* APPENDIX: WORKS CITED

Batchelor, Stephen. (2015) After Buddhism: Rethinking the dharma for a
secular age. Yale University Press.

Design Friction. (2016) Flaws of the Smart City. URL: [[http://www.flawsofthesmartcity.com/][http://www.flawsofthesmartcity.com/]]

Inayatullah, Sohail. (1998) “Causal layered analysis:
Poststructuralism as method”. Futures, Volume 30, Issue 8, October
1998, pp. 815-829.

Kohls, C. (2010) The structure of patterns. In Proceedings of the 17th
Conference on Pattern Languages of Programs - PLOP, Vol. 10, pp. 1–10.

Kuti, Fela. (1978) “Shuffering and Shmiling”. Coconut PMLP 1005
distributed by Phonogram Inc.

Leitner, H. (2015) Pattern theory: introduction and perspectives on
the tracks of Christopher Alexander. HLS Software.

US Army. (2002). “Training the Force”. FM 7-0.

Wyma, Chloe. (2016) “Breaking Down Broodthaers: Three Keys to Understanding His Essential MoMA Retrospective” Artspace. URL: [[https://www.artspace.com/magazine/news_events/exhibitions/marcel-broodthaers-at-moma-53532][https://www.artspace.com/magazine/news_events/exhibitions/marcel-broodthaers-at-moma-53532]]
