:PROPERTIES:
:ID:       902d27f7-26c7-488b-baa7-5b973a850359
:END:
#+title: Transfer control to participants
#+filetags: :HL:AP:

* Problem summary

Participants may be able to do more of the facilitation during or
after the workshop, and over-active facilitation would only get in
their way.

* Solution strategy

We come into the workshop expecting to be facilitators HOWEVER look
for opportunities whenever participants are taking a lead in the
conversation, identifying problems, drawing mindmaps, etc., and help
them practice these skills.

BECAUSE the workshop is designed to build skills and connections that
are put into practice later, and we only have a short period to work
with, we should highlight the skills that participants are bringing to
the table.

A typical pattern in coaching is to build from participants’
strengths, THEREFORE we need to identify those strengths within the
workshop.

SPECIFICALLY in the Anticipation pilot, participants were willing to
take charge of making mindmaps early on.  However, their feedback
mainly applied to things that the organisers could consider later,
rather than next steps for the participants or anticipation community.
Revising the PAR to ask about changes that the participants themselves
might like to take forward, but that remains somewhat superficial.  It
would be better to build the mindful ownership of methods earlier on,
e.g., perhaps with a mini-action-oriented PAR after each phase ("what
have we been doing, and who needs to continue these actions?").  This
will make the scenarios more concrete (e.g. by imagining specific
actors and roles they might take on).
