:PROPERTIES:
:ID:       92e18906-d0e6-4e73-a9cf-fbdad931f3cf
:END:
#+title: Roadmap
#+filetags: :HL:WS:

* Summary

*Context* a group needs to coordinate its activities over a period of
time. *If* the landscape is complex and not completely knowable BUT
adjustment to action based on feedback is possible; *Then* use an
explicit mechanism to share information about goals, obstacles, methods,
and resources.

* Instructions

** Overall process

- *Review Phase I and Phase II*:
  - [[id:f5a1bc15-5abb-44d6-8f7a-e254974c9002][Project Action Review]]
- *Repeat with variations, as needed.*
- *Respond to participants in the pilot workshops, and keep building energy*
- *Carry out meta-review periodically:*
  - [[id:56ce8d31-d3d6-4493-bb41-b07d810afbcc][Causal Layered Analysis]]
- Adjust workshop methods based on what we learned
- *Develop supportive methods and technology to scaffold ongoing work by communities*
  - [[id:2b1ca06d-486e-4398-a2c9-a4a9e303eaa3][Community Tech]]
- "Dogfood" this process by developing methods and technology that we ourselves find useful

*** Specific actions arising

- [ ] Alana from Bristol pilot wants to follow up; others may as well!
- [ ] Worth dropping a line to attendees of the Anticipation 2022 where they can be traced to say ‘thank you’

** Materials

- Shared experience of facilitators
- This archive of working methods

*** Previous Runs of This or Related Workshops
**** 2022 November 18, Anticipation 2022 "Going Meta"
**** 2022 November 3rd pilot in Bristol on Public Space and Public Health, Arnolfini Arts
**** 2021 PLoP
**** 2021 Connected Learning Summit
**** 2021 Oxford Brookes University Creative Industry Festival
**** 2019 Anticipation Conference in Oslo “Fictional Peeragogical Anticipatory Learning Exploration”
**** 2014 OpenEdJam with ‘zine http://is.gd/openedjam


** Intended outcome
We want to help communities grow and solve complicated problems that they would not readily solve without the kinds of interventions we’re offering.

* Phase III Feedback

** Let’s make and maintain our own roadmap

- Recognise that we are living inside "Phase III"
- Make sure that we have things well prepared
- We do have a =yasnippet= based workflow for running the *meetings*, could we do something similar with the workflow for the *workshop*?
- Use a common agenda file for the Abby project; it will live somewhere we can all access & track tasks.
  - A potential implementation is at =~/exp2exp.github.io/src/erg/agenda.org= — that’s worth a look as a starter pack.
  - However, we could do something similar in a more distributed way, e.g., the following will create an agenda for all =TODO= items files within this repo that have the :WS: file tag.  There are only two such items so far.
  - We could, similarly, make additional mixes for different managerial views into the repo.

#+begin_src emacs-lisp
(defun org-scrum-board (&optional filter)
  (interactive)
  (let ((org-todo-keywords
         '((sequence "TODO(t)" "|" "DONE(y)"))))
  (org-todo-list "TODO")
  (when filter
    (org-agenda-filter-apply `(,filter) 'regexp))))

(defun org-scrum-board-workshop ()
  (interactive)
  (let ((org-agenda-sorting-strategy '((todo todo-state-up category-keep tag-up)))
        (org-agenda-files '("~/exp2exp.github.io/src/"))
        (org-agenda-title "Workshop Roadmap"))
    (org-scrum-board ":WS:")))

(global-set-key (kbd "C-c R e") 'org-scrum-board-workshop)
#+end_src

** Let’s make and maintain our overall taxonomy

- Terms like “scenario” and “role” aren’t entirely clear, much less specifics like “Kaijū Communicator”: can we clear this up with a taxonomy?
- We’ll need to add some additional terms (like “disorder” or “meta”) per workshop run, but good to have a start with the core lexicon, then we could see how the other terms relate

* Phase III Evolution

- Having refactored things as a collection of Org Roam files, and reexported them as a linear document, we’re starting to have a "map" of the domain.
- Demo task tracker, above.  But, are these the right set of tasks?

