#
:PROPERTIES:
:ID:       0cc6700c-1018-4309-8a5b-44359e171abe
:END:
#+TITLE: Hyperreal Enterprises: Notes on Anticipation Pilot
#+OPTIONS: H:3 num:t toc:nil ':t broken-links:mark
#+LATEX_HEADER_EXTRA: \usepackage[a4paper,bindingoffset=0.2in,left=1in,right=1in,top=1in,bottom=1in,footskip=.25in]{geometry}
#+LATEX_HEADER_EXTRA: \usepackage[dvipsnames]{xcolor}
#+LATEX_HEADER_EXTRA: \usepackage{fontspec}
#+LATEX_HEADER_EXTRA: \usepackage[math-style=french]{unicode-math}
#+LATEX_HEADER_EXTRA: \usepackage{mathtools}
#+LATEX_HEADER_EXTRA: \setmathfont[math-style=upright]{DejaVu Sans Mono}
#+LATEX_HEADER_EXTRA: \setmonofont[Color=blue]{Ubuntu Mono}
#+LATEX_HEADER_EXTRA: \newfontfamily{\mm}[Color=red]{DejaVu Sans Mono}
#+LATEX_HEADER_EXTRA: \setmainfont[BoldFeatures={Color=ff0000},Ligatures={Common,TeX}]{Cormorant Garamond}
#+LATEX_HEADER_EXTRA: \newcommand{\hookuparrow}{\mathrel{\rotatebox[origin=c]{90}{$\hookrightarrow$}}}
#+LATEX_HEADER_EXTRA: \usepackage{fix-abstract}
#+LATEX_HEADER_EXTRA: \definecolor{pale}{HTML}{fffff8}
#+LATEX_HEADER_EXTRA: \definecolor{orgone}{HTML}{83a598}
#+LATEX_HEADER_EXTRA: \definecolor{orgtwo}{HTML}{fabd2f}
#+LATEX_HEADER_EXTRA: \definecolor{orgthree}{HTML}{d3869b}
#+LATEX_HEADER_EXTRA: \definecolor{orgfour}{HTML}{fb4933}
#+LATEX_HEADER_EXTRA: \definecolor{orgfive}{HTML}{b8bb26}
#+LATEX_HEADER_EXTRA: \definecolor{gruvbg}{HTML}{1d2021}
#+LATEX_HEADER_EXTRA: \newenvironment*{emptyenv}{}{}
#+LATEX_HEADER_EXTRA: \usepackage{sectsty}
#+LATEX_HEADER_EXTRA: \sectionfont{\normalfont\color{red}\selectfont}
#+LATEX_HEADER_EXTRA: \subsectionfont{\normalfont\selectfont}
# #+LATEX_HEADER: \subsubsectionfont{\normalfont\selectfont}
#+LATEX_HEADER_EXTRA: \paragraphfont{\normalfont\selectfont}
#+LATEX_HEADER_EXTRA: \subsubsectionfont{\normalfont\selectfont\color{black!50}}
#+LATEX_HEADER_EXTRA: \newfontfamily{\zhfont}{FandolSong}% or whatever
#+LATEX_HEADER_EXTRA: \DeclareTextFontCommand{\textzh}{\normalfont\zhfont}
#+LATEX_HEADER_EXTRA: \newfontfamily{\cinfant}{Cormorant Infant}
#+LATEX_HEADER_EXTRA: \newfontfamily{\csc}{Cormorant SC}
#+LATEX_HEADER_EXTRA: \newfontfamily{\cunicase}{Cormorant Unicase}
#+LATEX_HEADER_EXTRA: \newfontfamily{\cupright}{Cormorant Upright}
#+LATEX_HEADER_EXTRA: \newfontfamily{\cormorant}{Cormorant}
# #+LATEX_HEADER_EXTRA: \usepackage{xpatch}
# #+LATEX_HEADER_EXTRA: \usepackage{etoolbox}
# #+LATEX_HEADER_EXTRA: \xpatchcmd\href{\begingroup}{\begingroup\cormorant}{}{\fail}
#+LATEX_HEADER_EXTRA: \let\oldhyperref\hyperref
#+LATEX_HEADER_EXTRA: \renewcommand\hyperref[2][]{\oldhyperref[#1]{{\cunicase#2}}} 
#+LATEX_HEADER_EXTRA: \makeatletter\newcommand{\url@cuprightstyle}{\def\UrlFont{\cupright}}\makeatother
#+LATEX_HEADER_EXTRA: \usepackage[style=apa,natbib=true,backend=biber,uniquename=false,uniquelist=false]{biblatex}
#+LATEX_HEADER_EXTRA: \bibliography{../src/erg/erg.bib}
#+BIBLIOGRAPHY: ../src/erg/erg.bib


\begin{abstract}
  \noindent This document is a brief initial analysis of our Open Future Design pilot workshop on November 15rd 2022 at Anticipation 2022, Arizona State University.  Attendees were:
  \begin{itemize}
    \item Charles Jeffrey Danoff {\cupright<danoffcharles@gmail.com>},
    \item Joseph Corneli {\cupright<joseph.corneli@hyperreal.enterprises>},
\end{itemize}
\end{abstract}

\setcounter{tocdepth}{2}
\tableofcontents
\urlstyle{cupright}

# IMPORT
* Open Future Design workshop: Introduction
:PROPERTIES:
:tag: :HL:WS:
:CUSTOM_ID: b7b42aa2-c57c-4bcc-bc45-be9b63972be7
:END:

** Overview

Our /Open Future Design/ (OFD) workshop is mirrored by a strategy called
"PLACARD" that distributed teams can use to scaffold social
perception, cognition and action.[fn:: fullcite:patterns-of-patterns]  This method
combines design patterns with future scenario planning and review
processes.  The OFD workshop is, essentially, the first run through a
cycle that groups can repeat on their own.  The workshop introduces
new collaboration methods and shows how they are effective.
Applications range from building new platforms for collaborative
design and citizen science, to assisting on-the-ground innovation
projects.

** Outcomes and Evaluation

*** Intermediate artifacts

- Mindmaps created with participants.
- Group insights, in the form of shared futures.

*** Output

- A constellation of interrelated design patterns that is produced by a diverse group of experts, based on shared futures.

*** Outcomes

- Long-term community engagement and buy-in based on agreed upon design patterns.
- Time-savings, unified structure, and further multilateral relationships formed (improving upon the standard default of individual meetings with stakeholders).
- Potential next steps include new communities of practice, and new initiatives (e.g., grant proposals, working groups).

*** Limitations

- Interrater reliability is initially low, though this may improve as
  our collection of design patterns grows.

*** Narrative Example

On November 17rd, 2022 we ran a pilot in Mesa, AZ with the theme
"Going Meta, Anticipating Anticipation".  This brought together 10
people with varied expertise on these themes for a structured
discussion.  In the first phase, we discussed the theme, and potential
scenarios for development (...).  We then zoomed in on a couple of
these scenarios in separate and fleshed them out in small groups
(...).  Then followed a share-back round in which the two groups could
listen to one another (...) In a follow-up round of analysis, the
facilitators looked at notes from the workshop and found new ‘design
patterns’ that enable workshop participants to solve the problems they
identified.  (Details follow.)

* Share back

We’re at the end of our time together, let’s share back any crucial
points with a full-group PAR.

* Transfer control to participants


** Problem summary

Participants may be able to do more of the facilitation during or
after the workshop, and over-active facilitation would only get in
their way.

** Solution strategy

We come into the workshop expecting to be facilitators HOWEVER look
for opportunities whenever participants are taking a lead in the
conversation, identifying problems, drawing mindmaps, etc., and help
them practice these skills.

BECAUSE the workshop is designed to build skills and connections that
are put into practice later, and we only have a short period to work
with, we should highlight the skills that participants are bringing to
the table.

A typical pattern in coaching is to build from participants’
strengths, THEREFORE we need to identify those strengths within the
workshop.

SPECIFICALLY in the Anticipation pilot, participants were willing to
take charge of making mindmaps early on.  However, their feedback
mainly applied to things that the organisers could consider later,
rather than next steps for the participants or anticipation community.
Revising the PAR to ask about changes that the participants themselves
might like to take forward, but that remains somewhat superficial.  It
would be better to build the mindful ownership of methods earlier on,
e.g., perhaps with a mini-action-oriented PAR after each phase ("what
have we been doing, and who needs to continue these actions?").  This
will make the scenarios more concrete (e.g. by imagining specific
actors and roles they might take on).

* Design for community uptake

** Problem

If we only focus on the skills of the people in the room, our
creativity will be limited, as will the eventual impact.  So, we
should design new patterns should be thought about with broader
users/contributors/beneficiaries in mind.  Our patterns may influence
how they end up relating to each other.

** Solution

We can’t assume that the community is cohesive at the outset. HOWEVER
if we begin to understand how the community works, we can get a sense
of the system that we are intervening in.  Some seemingly simple
questions could have complicated answers, like “Who’s in and who’s
out?”

BECAUSE of the limitations as to scope and scale of a one-day
workshop, we do well to think of it as a smaller scale model of the
surrounding dynamics.  We intend to both learn about these dynamics
(analytically) and develop new interventions (synthetically).  Since
we’re thinking about patterns, many of these will describe patterns of
interaction.

We’re not building a community from scratch, in any case, though the
sense of collective identity or agency for people in the room may be
limited.  THEREFORE, design the patterns that we develop so that their
uptake is relatively straightforward.  Use an accessible metaphor to
build a small-scale pattern language per each constituent pattern
(e.g., ‘Open future design’ used a water metaphor; ‘Sharing our
stories’ could use a library metaphor or similar).  Notice that there
are a couple other existing ‘metaphors’ that could define the large
scale dynamics of our interaction, e.g., we might think about the
whole day as the creation of a documentary (iDocs) or like a startup
incubator for new community interventions.  The framing metaphors will
impact on how invested people are in the day’s activities; different
participants may have different expectations, and for that aspect, the
simplest thing to do is to ask them.

SPECIFICALLY We’re defining our values as a research group and company
doing open source work.  We need to stay clear with everyone that
we’re not extracting more than we’re giving.  At the workshop, we can
ask about ideas that are needed to prototype something quickly that we
can share with the wider community; and, at each stage in the
workshop, reflect together on what’s needed to move the conversation
forward.
