:PROPERTIES:
:ID:       4dd04725-1d9e-4256-866a-3cee2066e687
:END:
#+title: 02 May 2021 — Sfumato
#+FIRN_UNDER: Writing
#+FIRN_LAYOUT: typescript
#+DATE_CREATED: <2021-05-02>

The removal of first and second person pronouns from the text is
considered, on the view that this helps to bring the frame of
reference into the text itself.  The necessity of ‘a reader’ and an
interaction with the text is then considered, even though ‘the reader’
has been stripped of their pronouns.  It’s more that we are looking
within the text at the forms of resonance.  These are referred to
using the metaphor of /Bénard cells/, as forms that emerge under
energetic flux.  This starts to move in the direction of a
conflagaration of the modern world (here I have in mind /Miracleman/).
The relationship between pronouns and ‘genre’ is discussed and both
are dismissed in one gesture.  However, the thought process then
begins to take form around existing structures.  There’s some
dithering between the conflagration of the modern world and a simple
change of perspective (referencing earlier text in which we would be
happier to think about the end of the world than the end of
capitalism, or whatever).  Thinking in terms of a ‘negative space’ of
the text is deemed important for identifying emergent structure: in
especially the ‘negative space’ that represents things that we were
not willing to look at further.  Connections to other literary and
philosophical technologies that seem similar are mentioned.
