:PROPERTIES:
:ID:       6a6dddb4-1630-4338-bc65-ce88593965e5
:END:
#+title: 03 May 2021 — Collective writing
#+FIRN_UNDER: Writing
#+FIRN_LAYOUT: typescript
#+DATE_CREATED: <2021-05-03>

I consider the relationship between discourse
and individual writing and thinking.  The things
that seem interesting to a collective are opposed
to the things that seem interesting to an individual,
and the latter seem to come off rather poorly.  This is
because whatever an individual writes without working
closely together with others is more likely to be
a ‘reaction’ than to be a coherent interaction.
The power of collective thought seems to have been
underdeveloped over time; a ‘biosemiotics’ of ideas
would require us to be comfortable working with the
landscape in which ideas exist so that we could
track them.  The importance of this form of literacy
increases in response to the prevalence of collective problems.
Discourse also suffers, since it is not seen as the site
of creativity (which is assumed to be the preserve of individuals).
The way forward could be to learn new strategies for listening.
Lastly, a comparison is made with Turing’s notion of machine
thinking, indeed, ‘collective writing’ is positioned as the vanguard
of the machine thinking method.
