:PROPERTIES:
:ID:       7cb156f0-584b-45be-bee1-07534629faf7
:END:
#+title: 05 May 2021 — Breakdown of language
#+FIRN_UNDER: Writing
#+FIRN_LAYOUT: typescript
#+DATE_CREATED: <2021-05-05>

The evolution of system models is considered, with reference to
systems that include phase change.  Language development is such an
example.  The obstacles to language development abound in the form of
/old languages/, which stand for familiar patterns.  The relationship
between language and human beings is complicated by the fact that
language is an elegant and powerful control system.  Human
relationships are subverted to the maintenance, care, and feeding of
language systems.  The ‘breakdown of language’ does not mean the
‘breakdown of communication’ but methods for opening up what’s behind
or underneath the language, or alternatively finding the things that
didn’t seem to be linguistic and surfacing the language hidden
therein.  Again, the fact that language simplifies thought works
against us in such endeavours.  However if we think about the
historical development of /computational-informatic/ systems in this
connection, then we see firstly how language has become the dominant
type of organisation on the planet.  Our ability to think about things
in this sort of abstraction is severely limited, so it is potentially
helpful to use ‘absurd’ framings (e.g., compare the development of
computer technology to the development of perspective in painting).
While we can’t expect that this sort of theorisation will develop in a
strictly logical way, we can observe the ‘minor language’ of
connections and work with it in modes that are potentially distinct
from the workings of ‘majority language’.  Lastly, the view that the
machine thinking method has already been prototyped and is up and
running on a human substrate is postulated: computer hardware should
not only be considered in its machinic form.
