#+TITLE: Wiki
#+roam_tags: MAI AN
#+CATEGORY: MAI

#+COMMENT: OLD CONTENT:
#+COMMENT: The public facing version of these notes is available on a simple
#+COMMENT: “brain dump” web interface, at https://notes.exploretoexploit.com/posts/.

The public facing version of these notes is available on a simple web
interface, created by firn: [[https://exp2exp.github.io/][https://exp2exp.github.io/]]. This mirrors
the contents of our Org Roam directory.  Editing is explained below.

We can also view the contents of Org Roam in a linear form as PDF
document... or view the currently active tasks using Org Agenda.  In
the future we may want to have several different “upstream” locations,
based on several different small-scale wikis, all feeding into this
one location.  That’s not hard to set up.  Contents can also be
browsed in a graphical form either with the built in =org-roam-graph=
functionality, or by installing Org Roam Server and running
=org-roam-server-mode=.

We can potentially improve on all of this further, bulding something
like [[https://metacademy.org/][Metacademy]].  For now, we describe how to use this simple Org Roam
based wiki.  A few sub-pages provide technical details needed for a
one-time startup.

- [[file:wiki_access.org][Wiki: Access]]
- [[file:wiki_org_roam_setup.org][Wiki: Org Roam setup]]
- [[file:wiki_pairing.org][Wiki: Pairing]]

Now on to some of the more day to day topics, issues, and concerns!

* Tags

Some of the nodes have =#+roam_tags= from the following set:

| *code* | *meaning*          |
|------+------------------|
| HL   | High level       |
| CDN  | Can do now       |
| LRD  | Longer R&D cycle |
| HD   | Has dependencies |
| RR   | Research Review  |
| RO   | Research Output  |
| OTS  | Off the shelf    |
| MAI  | Maintain         |
| SH   | Stakeholder      |
| AN   | Annex            |

Some of the files also have a =#+CATEGORY= set.

* Linearizing

A method for turning the wiki into a more-or-less linear document is
supplied in the =manual= subdirectory, see [[https://github.com/exp2exp/exp2exp.github.io/blob/master/src/manual/org-roam-manual.el][org-roam-manual.el]].

According to Scrum, a key idea with a ‘backlog’ is to go from the
most-doable work in progress to the least-doable and potentially
vague.  The linearization described here was constructed with that
inspiration in mind — but it probably is too slushy to achieve the
objective.

** BACK org-roam-manual.el could be improved for generating slices according e.g. roam tags

** BACK Backlog linearisation relative to the long-form text

Another way to look at the backlog is to [[https://gist.github.com/holtzermann17/1c5b333a905b312f21da66db246159a6#back-hyperreal-enterprises-roadmap][view all of the TODO items]]
from across the wiki.  It would be absolutely worthwhile to sort these
=TODO= items based on their doability, and try to reorganize the
document-oriented linearisation along the same lines.  (Joe said some
more about managing =TODO= items in narrative terms within the notes on
[[file:week_19_april_2021.org][Week 19 April 2021]].)

* Publishing to the web

Publishing with Firn is simple: you just commit, and HTML content will
be built via github actions.  If you want to preview contents locally,
you can instead do:

#+begin_src
firn build
firn serve
#+end_src

Then commit and push.

** BACK refine special block exporting with Firn

In regular Org mode, it’s possible to [[https://superuser.com/questions/726201/how-can-i-apply-easy-formatting-to-org-mode-blocks][define your own blocks]] which
then export to a div with the given block name.  Here’s an example:

#+begin_monoblock
This is some text.
#+end_monoblock

With Firn, we did [[https://github.com/theiceshelf/firn/issues/68][some initial work]] to set things up so that such
blocks would also be exported: however this needs to be revisited and
tested.

#+begin_example
This is some text.
#+end_example
