#+TITLE: Organisational infrastructure
#+roam_tags: HL AN TO
#+CATEGORY: ORG

This section is mildly-technical appendix.  It looks at our
organisational infrastructure itself, including simple things like the
technologies we use for communication, and more involved things like
“how we communicate” more broadly.  (This is a good candidate for
splitting off into its own separate wiki, if for no other reason than
that it takes up a lot of space in the generated PDF.)

* Stakeholders
Probably worth understanding that the stakeholders come in circles or
layers (like an onion).  The people who use the infrastructure are key
stakeholders.  But, the people who use the work that they produce are
another set of stakeholders.  And then there are a bunch of people who
are doing ‘similar’ things who could be stakeholders.

- [[file:stakeholders.org][Stakeholders]]

* Schedule and activities

- [[file:stubs/develop_a_suitable_collaborative_writing_workflow_for_a_specific_shared_output.org][Develop a suitable collaborative writing workflow for a specific shared output]]

Presently we are meeting 20 minutes a day at 4PM UK time, 11AM
Eastern, on Discord for a “coffee chat”.

Previously we tried to maintain a schedule of longer meetings (UK
evenings):

- *Monday*: Seminar
- *Wednesday*: Workshop
- *Friday*: Studio

That seemed to be too many meetings.  Whatever we do about regularly
scheduled meetings, we might want to look at how to best pursue of
*topics of mutual interest* such as:

- *Readings* on rewriting rules and production systems, and higher-dimensional graph-like things
- *Business development* around open source, knowledge management, etc.
- *Reviewing* the value add of Wiki ways of thinking and working, which we have a pretty broad range of experience with
- *R&D* around ‘lenses’ in ACT: structure for bi-directional transformations, to enable changes in a projection

So far, this Roadmap has gathered information on some of the topics
that have been discussed, but not all of the things that we could see
ourselves working on together.

As another activity we may want to get scheduled one or more sessions
focused on business stuff.

* Project orientation

Some of this will be different depending on whether we think of this
as a “business”, or as “a business of some specific nature”: primarily
centring on “who does this business do business with?”

- *Status* - where is the project right now?
 - Right now /this overall project/ is in a “project development” mode.
 - What are the (multiple) /success indicators/ or /proof points/ or /failure indicators/ for each of the projects? (E.g., going to the casino with $20, you might quit when you get below $10, you might leave when you get above $50.) E.g., need of customers for X, our credibility in X?
 - For the various sub-projects: one relevant thing is “how long is it before thing is likely to make money?” (AKA, “Cross-over.”) Or “what else is needed for this to make money?”
 - In particular: maybe take a couple months to see how things are going with a given sub-project? This gives evidence of what we can produce when we work together. We might then ask, who else would care to pay for this?
 - We have listed 4 active projects (https://miro.com/app/board/o9J_kmPNvaQ=/); maybe the blog is another one.
- *Roles and Responsibilities* - /who is handling the standard project roles, and what are they responsible for doing?/
 - Each individual sub-project is likely to have different requirements (e.g., some may need 2 people, some will need 1, etc.)
 - If there’s more than one person involved it becomes a parallel architecture
- *Goals* - /What will this project achieve?/
 - “If I do something valuable, the money will come later.”
 - Some of them we might be willing to take the risk of investing time and energy based on whether it looks directly useful to us.
 - Some, like a course, we may need the information about whether it’s likely to be taught.
 - Some could become a paper or the building block of a business: these can be small demo projects.
 - Alternatively, in a consulting mode, our role becomes understanding customer goals and helping rationalise work to fulfil them.
- *Resource Requirements* - /What (people, money, things) are needed to accomplish this project?  Where do they come from?/
 - We each individually need some money, but it’s not totally clear that the /company/ needs some money.
 - If we wanted to replace any one of us with an employee, then we’d have to have some funding source.
 - If the number of person-hours for the goal is quite high, then it’s unlikely for the goal to be achieved without funding.
 - E.g., what would we need to be able to do consulting?
- *People* - /Who are the people working on this project? Who can I ask for more information? How can I best get in touch with them?/
 - If we were to be doing consulting, then it becomes about serving specific customer needs.
- *Approach* - /What is the overall strategy for accomplishing this project?/
 - Whatever we choose (e.g., consulting vs product development) we should choose it based on some data and analysis.
 - Wherever we are now, the question is what’s needed to move ahead.

- *Workplan and Timeline* - What are the specific tasks needed to accomplish our goals? When might they happen? Who / what / when (in agile, we specify two).
 - Joe needs some job soon!
 - To do consulting we’d need to figure out customer need and credibility
 - To make progress on the AI directions we need some version of all the things up and running!
- *Communication Norms* - how have the project participants agreed to stay in touch? what, where and how often are regular meetings? Special ceremonies?
 - In 2 months we’ll have 2 more months of experience.  So we could then assess things.
 - In advance of that, we might start to understand the expections about how we would gather the data.
 - It should be pretty much fun, and if it’s not we’re kind of doing it wrong?
 - On an ongoing basis we should be able to check whether what we’re doing is effectively addressing the goals we have
- *Sponsor* - /the person who requires the output of the project and has allocated the resources for it (aka Customer in agile)/
 - So far we’re all sponsoring our own work on sweat equity
 - While also trying to be helpful & respectful to each other
 - EF was the sponsor at one time
 - Joe provided chips and dip but the event was strictly BYOB... as long as we’re here we’ll make the best out of.  Polka time!
- *Project Manager* - the person responsible for the drumbeat and tempo of the project, and for its administrative details, including good project management hygiene
- *Lead* - the person responsible to the Sponsor for making sure the project is accomplished and to the Team for making sure they are able to accomplish the project
 - Ray: project to build bridges between participants (e.g., systems bio, category theory, stats); this is related to the “transdisciplinary design” course
 - Joe: I’m less technically sophisticated
- *Team* - people working on the project
 - Everyone will have some constraints (like need $40K per year if it takes more than 20 hours per week)

** Project Management Hygiene

- set SMART goals (Specific, Measurable, Achievable, Relevant and Time-based)
 - (See also: *Coaching and Mentoring*.)
- understand tasks required to accomplish goals, then set realistic timeline
- create project plan in wiki
- regular, frequent check-ins to iterate plan (goal, priorities, etc.) if necessary
- after-action reviews at the end of project, including reflection/writeup of positives and deltas
- experienced, well-oiled teams requires less strict project management hygiene
- new, less-organized, or heterogenous teams require more attention to careful project management hygiene

** BACK Make a list of actual topics of interest: revise HL pages to match
If we were simply doing “content production” — then we might think of
a list of chapters to write, or podcasts to produce, or something like
that.  Maybe those ways of thinking and working don’t apply
comfortably here.  What we do have, currently, is a list of “high
level topics” which can be found by searching for the =HL= tag.  We also
have tons of channels — most of them more-or-less abandoned — in the
Discord.  Even though a list of topics won’t help a whole lot,
revising the =HL= items might give us a better sense of what our shared
objectives *or other forms of common ground* are.

** BACK Make a project analysis of active projects
(This could refer to Peter Kaminski’s *project orientation* concept.)
- [[file:hel/make_a_project_analysis_of_active_projects.org][Make a project analysis of active projects]]
- [[file:stubs/maintain_plans_for_the_quarter_ahead.org][Maintain plans for the quarter ahead?]]

* Technology

Does https://github.com/orgs/exp2exp/projects/1 conflict, replace, or
serve a different function compared with Org mode agenda items?

** DONE Figure out Github project(s) vs Org todos               :joe:cameron:

We won’t use Github stuff right now.  That’s better for dealing with a
public-facing contribution workflow when we have actual open source
things running with contributors.

* Next steps                                                      :noexport:
:PROPERTIES:
:ID:       17468abb-5c17-458e-a053-72e6356bbad5
:END:

- [[file:20200811185435-obs_recordings.org][OBS recordings]]
- [[file:20200810135619-discord_server.org][Discord server]]
- [[file:20200814193042-code_sharing_platform.org][Code sharing platform]]
- [[file:20200814195259-blog.org][Blog]]
- [[file:20200912223428-wiki.org][Wiki]]
- [[file:20201003164100-forum.org][Forum]]
