:PROPERTIES:
:ID:       ff606adf-3ec7-49a3-a7b7-3c12847ac35e
:END:
#+TITLE: Hyperreal Enterprises: Roadmap
#+CATEGORY: ROADMAP
#+filetags: :HL:AN:

* Preface
:PROPERTIES:
:ID:       0caba40b-2561-4143-b2b1-55f3ddc3201b
:END:

This document synthesises a [[https://peeragogy.org/roadmap][Roadmap]] (and perhaps also a [[http://scrumbook.org/value-stream/release-plan/product-roadmap.html][Product
Roadmap]]) for Hyperreal Enterprises, Ltd.  The Roadmap is being written
inside [[https://github.com/org-roam/org-roam][Org Roam]] (an [[https://www.gnu.org/software/emacs/][Emacs]] package), and displayed with [[https://github.com/theiceshelf/firn][Firn]].  The
document can be thought of as a [[id:f55bb496-6ce8-44fb-887f-a423972bfa73][Wiki]] (and edited inside Emacs).  From
these sources, other downstream formats can be derived.  A narrative
overview follows.

To skip it, browse ahead to [[id:420fa6ad-57b3-419e-869c-1655898e3260][Top]].

* TL;DR

We started thinking about how to create AI tools that would process
open source information and enable applications such as automated
computer programming.  Then [[https://www.youtube.com/watch?v=SGUCcjHTmGY][Open AI Codex]] and [[https://copilot.github.com/][Github Copilot]] came
along and slightly stole our thunder.  But actually, these tools still
leave plenty of open questions.

Focusing on the technical side of things: what would it take to build
an AI system for programming, with depth measured not in terms of
neural network layers but in terms of understanding?  And what about
other domains of inquiry, like science, mathematics, or collaborative
design?

Here’s a curious thought.  AI systems can beat the best human players
at the game of Go, but these systems don’t “know” the basic concepts
of Go that any amateur human player would recognise.  These AI systems
work with abstract patterns in data: in this case, patterns built out
of three-by-three grids.

What if AI systems worked, instead, at the conceptual level?  It’s
possible to represent and reason about [[https://en.wikipedia.org/wiki/Olog][concepts]] on computers in a way
that looks very different from word vectors.  But the infrastructure
for computing with concepts isn’t as well established as contemporary
neural methods, and isn’t yet connected with those methods in a
ready-to-use way.  If we were able to bridge this gap, we could apply
AI technology everywhere there are /patterns/.

* Other questions

- [[id:780f6d8c-ad15-402a-8f75-1efb86df7e8d][Is this interesting?]]
- [[id:c239828e-f153-403a-a6bb-7b687130911d][Is this realistic?]]
