#+TITLE: Hyperreal Enterprises: Roadmap
#+roam_tags: HL AN
#+CATEGORY: ROADMAP

* Preface
:PROPERTIES:
:ID:       0caba40b-2561-4143-b2b1-55f3ddc3201b
:END:

This document synthesises a [[http://www.peeragogy.org/pattern-roadmap.html][Roadmap]] (and perhaps also a [[http://scrumbook.org/value-stream/product-roadmap.html][Product
Roadmap]]) for Hyperreal Enterprises, Ltd.  The Roadmap is being written
inside [[https://github.com/org-roam/org-roam][Org Roam]] (an [[https://www.gnu.org/software/emacs/][Emacs]] package), and displayed with [[https://github.com/theiceshelf/firn][Firn]].  The
document can be thought of as a [[file:20200912223428-wiki.org][Wiki]] (and edited inside Emacs).  From
these sources, other downstream formats can be derived.  A narrative
introduction follows.

To skip it, browse ahead to [[file:20200810132653-top.org][Top]].

* Introduction

** Applying AI to technical fields is a huge opportunity.

It’s striking that in computer programming work, /collective
intelligence/ is used almost everywhere, but artificial intelligence is
used almost nowhere.  AI can kick butt at Chess and Go, but university
courses are still taught by human professors.  Surely, AI that could
write code at a human level would be a valuable thing...

** But where’s the human-level AI for coding?

A research agenda around “AI for programming” was already spelled out
by Alan Turing in the late 1940s.  It is only relatively recently that
we have massive amounts of relevant data to work with.  Code
completion and code generation tools are some of the “low hanging
fruit” of this domain.  We think that something much more substantial
is around the corner.

** We are looking at this problem as an informal open source R&D collective.

Our team brings together applied experience in Natural Language
Processing (NLP), computational modelling, online communities,
physics, biology, mathematics, and statistics.  We’ve been getting
together for daily coffee chats, and sharing information and skills
with each other in online seminars.  Sometimes we bring in guest
speakers.  We hope as time goes by our chats will coalesce into notes,
blog posts, papers, and working prototypes.  We aren’t promising a
schedule of deliverables — because we’re all volunteers — and we’re
doing this for fun and interest.  But we do plan to share what we’re
learning as we go along!

** Broadly, the steps we have in mind go from data, to models, to AI agents.

We plan to document our progress (or lack thereof) on this blog.  As a
very rough outline, this is what we expect to look at:

- We plan to use contemporary information extraction methods to derive computationally meaningful material from Stack Exchange Q&A, Github Issues, and programmers’ discussions, along with code. To do this, we will combine general purpose language models, like BERT, and a knowledge graph approach.

- We plan to use category theoretic methods as a glue that can hold together a range of computational models, including models of programs and the process of computer programming. [[https://arxiv.org/pdf/1807.05691][Monocl]] is an existing process modelling language that has been used to create an abstraction layer over a collection of [[https://www.datascienceontology.org/][data science programs]]. We plan to generalise this.

- Ultimately, we plan to install these models in computational agents who can then “converse with each other to sharpen their wits,” as Turing anticipated, mirroring contemporary developments in self-play.  However, the specific design of the agents remains an open issue at the moment!  We plan to explore techniques from Bayesian learning, logic programming, and reinforcement learning.

** Reflection is part of the process.

We’re interested in understanding human behaviour as well as technical
topics: that goes for our own behaviour in particular.  We plan to
post to our blog at least monthly — as long as we keep our discussion
running — using it as a place to reflect on how things are going.
Although we’re grappling with some weighty topics, success is not all
or nothing!  Writing here will mark our progress and be useful in
their own right (e.g., blog posts can feed into research papers or
tools).

** Progress so far
Alongside setting up a blog and drafting an initial anouncement
(voilà!), we’ve updated the website of our affiliated UK-based company
[[https://hyperreal.enterprises/][Hyperreal Enterprises]] to match the outlines of what we’ve described
here.  As mentioned above, are having regular meetings, which we’ll
record if they look likely to be interesting to a wider audience.
We’ve got nice internal documentation going, via [[https://github.com/org-roam/org-roam][Org Roam]], from wich
various derived formats are produced, including a public [[https://exp2exp.github.io/][wiki]]
generated by [[https://github.com/theiceshelf/firn][Firn]].  (We recently sent an abstract to EmacsConf 2020 to
talk about the various other Emacs-based tools we’re using!)

Some of our seminars so far have explored an Open Information
Extraction (with several demo notebooks), and looked at the early
parts of Michael Betancourt’s “Towards a principled Bayesian
workflow”.

Active channels on our Discord server include:
- #emacs-cloud-hypernotebooks
- #how-to-design-programs
- #text-analysis
- #model-construction
- #knowledge-graph

** TL;DR

We are creating AI tools that will process open source information and
build on these in applications such as automated programming.

