#+TITLE: Hyperreal Enterprises: Roadmap
#+roam_tags: HL AN
#+CATEGORY: ROADMAP

* Preface
:PROPERTIES:
:ID:       0caba40b-2561-4143-b2b1-55f3ddc3201b
:END:

This document synthesises a [[https://peeragogy.org/roadmap][Roadmap]] (and perhaps also a [[http://scrumbook.org/value-stream/release-plan/product-roadmap.html][Product
Roadmap]]) for Hyperreal Enterprises, Ltd.  The Roadmap is being written
inside [[https://github.com/org-roam/org-roam][Org Roam]] (an [[https://www.gnu.org/software/emacs/][Emacs]] package), and displayed with [[https://github.com/theiceshelf/firn][Firn]].  The
document can be thought of as a [[file:20200912223428-wiki.org][Wiki]] (and edited inside Emacs).  From
these sources, other downstream formats can be derived.  A narrative
overview follows.

To skip it, browse ahead to [[file:20200810132653-top.org][Top]].

* TL;DR

We started thinking about how to create AI tools that would process
open source information and enable applications such as automated
computer programming.  Then [[https://copilot.github.com/][Github Copilot]] came along and slightly
stole our thunder.  But actually, Copilot leaves a lot more open
questions than it solves.  Focusing on the technical side of things:
what would it take to build an AI system for programming, with depth
measured not in terms of neural network layers but in terms of
understanding?

A curious thought: AI systems can beat the best human players at the
game of Go, but the systems in question don’t “know” the basic
concepts of Go that any amateur human player would recognise.  The
systems don’t work in terms of concepts, but rather, in terms of
patterns in data: in this case, patterns built out of three-by-three
grids.

What if AI systems worked, instead, at the conceptual level?

* Other questions

- [[file:is_this_interesting.org][Is this interesting?]]
- [[file:is_this_realistic.org][Is this realistic?]]
