:PROPERTIES:
:ID:       1e950c7d-db6d-4082-80e2-c744c984c219
:END:
#+TITLE: BUSINESS DEVELOPMENT
#+filetags: :HL:

* Relationship to purpose

Understanding how the business activities relate to the purpose?  We
might do things that appear unrelated what we say at *Why not what* to
serve customer needs in the mean time.  However, if we do, we should
either come up with some reasoning about how this helps us address the
purpose, or revise our statement of purpose to reflect the current
reality.  This presumably isn’t hard to do, e.g., we could say “once
we have a successful business we will pour /x%/ into research,” but in
any case we should clarify this.

* Roughly B2C

- Launch some version of the Emacs Hyper Notebook as a cloud service. (Build it first and test it first.)
- *Visual Interfaces*: Develop a user interface on top of more advanced data analysis tools. (The focus is on the infrastructure that allows you to convert a graph into a neural network or whatever.)
- *Data course* (training format): Recruit people to take our course for a fee.
- *Paperspace DO NJ etc. Collaboratory* (Edtech SaaS): People would build their own courses/projects on our software and pay for licensing.
- *Teach arbitrary coding* (Edtech SaaS): People would use our tutoring system to improve their programming abilities.

* B2B

- *Agent model* (software as a service format): We can run our agent model to generate new code or other insights. People can pay for compute plus a premium for quality.
- *Probabilistic programming for scientific computing* (Consulting format): going around and creating customers by talking to businesses, saying “Using proababilistic programming — or other technologies — we can optimize this, this, this, and this, saving you this much money.”
 - Many companies hardly use any AI, let alone deep learning. If you can hustle and sell things, this can work.
 - However, we don’t want to sell AI snake oil, so if we are going to do consulting it should be around topics that we’re actually experts on. For example, plausibly, we could talk about modelling /documents/ and /workflows/.

* Different kinds of users

If we want to build a business, we should focus on who our target
users actually are, and what problems we can solve for them.
Typically we would build the business in a customer-centric way.  So,
for example, are the users/customers:

- Advanced STAN users, or,
- People who don't know how to do data analysis but who can make graphs.

Broad categories of users are surveyed in the *Downstream*.

* Related work

- Be wary of competing with things like Roam, though some level of competition is intrinsic in business.
- “Roam scratches my itches for document and graph aware note taking pretty well.”

* Read on

 - [[id:6058a324-285a-4d18-8d01-3801c7f9dab3][Upstream]]
 - [[id:e59e6fd9-df22-489a-accd-05860bd5307c][Grant development]]
 - [[id:e3864f2a-62d0-4203-951a-a54bce13a307][Action and Change in Peer Learning]]
 - [[id:c11bd25c-8abf-487b-9b37-912ade54cf85][Coaching and Mentoring]]

* Next steps :noexport:

- [[id:9b1e0c6b-6f56-42fb-a773-5c12735bd885][Bottom]]
