:PROPERTIES:
:ID:       f83051b3-95b5-4471-b03d-eeeccda51d6d
:END:
#+title: (Inter-)Personal Doughnut
#+filetags: :HL:BP:

* Problem

Informed by [[id:56ce8d31-d3d6-4493-bb41-b07d810afbcc][Causal Layered Analysis]], at the workshop we were ready to
work across levels — but did we have the correct set of levels for the
‘public space & public health’ setting front-of-mind?

* Solution Strategy

Something that came up in the discussions around the workshop and
PLACARD method was our prominent focus on the wellbeing of
participants.  We could frame this in a rough analogy with Doughnut
Economics, HOWEVER the framing would be different in this small-scale
format.

BECAUSE ‘health’ is inherently a complex topic — e.g., considering a
“bio-psycho-social” or “bio-psycho-social-eco” model — there are
multiple moving parts.  If we want to talk about health effectively in
future versions of the workshop, we might want to rethink aspects of
the workshop itself using these components, e.g., the "roles" that we
introduced could be rethought this way.

Since we cannot be guaranteed to have teams of participants evenly
divided along the bio/psycho/social/eco components of health,
THEREFORE, it could be useful to survey some of the other frameworks
that are out there that could be relevant to this reframing, so that
we could get creative about reconfiguring them.  Examples might
include [[https://en.wikipedia.org/wiki/Manfred_Max-Neef%27s_Fundamental_human_needs][Manfred Max-Neef's Fundamental human needs]], Schwartz’s [[https://en.wikipedia.org/wiki/Theory_of_Basic_Human_Values][Theory
of Basic Human Values]].

#+begin_quote
/According to Schwartz, individual values are responses to three
universal requirements of human existence, namely needs of people as
biological organisms, of agreement in social actions, and of survival
and well-being of groups./
#+end_quote

SPECIFICALLY, the axes and dimensions that were used to organise
scenarios (in-balance vs out-of-balance, scarcity, aliveness,
availability of knowledge commons, etc.) provide a very rough
framework that was generated by participants.  How would we analyse
our workshop’s framework in terms of the bio-psycho-social-eco model
of health?  Does it have natural ‘habitable zones’ similar to the Kate
Raworth doughnut?  One limiting factor that was drawn into the diagram
was based on language/access/education.  Since many of our solutions
were related to /communication/, these do seem to be relevant factors.
How do these limiting factors show up around active participation in
(both) [[id:57f06710-a96c-4cbc-bcc7-57d3d3e550c4][Public Space & Public Discourse]]?
