#+title: 29 April 2021 — Testament of Youf
#+FIRN_UNDER: Writing
#+FIRN_LAYOUT: typescript
#+DATE_CREATED: <2021-04-29>

I begin with a question linked with world-building and
then with arguments about differences of opinion
alongside scientific investigations of the nature of
the world.  I think consider why it is that some people
prefer to retreat from the world.  The title of this
piece is perhaps inspired by the pop adage “Recoiling
in disgust is not the same as apathy.”  I start to spin
it a bit relative to the notion of the Umwelt, but then
I turn it more in the direction of the death drive
(/Todestrieb/).  Then I start to beat on some Spinozistic
notions about choice as a continuous function of life
itself.  I introduce the title “Testament of Youf” only
on page two, in connection with the idea of a title or
a fictional character ‘squatting’ a possibility that
might otherwise live in reality.  I then develop a sort
of Acker-esque developmental line, thinking about how
people individuate in contemporary times, including the
development of interiority.  I consider how this
‘developmental trajectory’ is continuously replaying
(like a standing wave) and how this state of
being-informed is the forced choice we are always
making.  Lastly I think about how this relates to
language, and try to draw a line between Spinoza’s
determinism and Burroughs’s notion of control.
