#+TITLE: Emacs and Org Mode
#+roam_tags: TO

We have been looking at Emacs and Org Mode, along with other tools for
researchers and knowledge workers.  We gave a short talk at EmacsConf
about a preliminary design for an [[file:20200905125342-emacs_hyper_notebook.org][Emacs Hyper Notebook]].

Some of our subsequent discussions about Emacs and Research appear in
[[file:erg.org][Emacs Research Group meeting notes]].

This page attempts to create a summary of the themes and ideas we’ve
been surfacing.  Another form of high-level summary appears in our
experiments with Causal Layered Analysis ([[file:cla-20-february-2021.org][CLA 16 January 2021]], [[file:cla-20-february-2021.org][CLA 20
February 2021]]).

* Outtakes from our CLA notes, to turn into a narrative

- /Talking about actualizing what we’re doing/: This keeps popping up, so might be worth discussing tomorrow.
- Annotations and history
- “Bookdown” to create a book in Markdown?
- *Hypothes.is* to have access to WIP (https://via.hypothes.is/https://www.gnu.org/)
- Trying to structure my dissertation, which has many parts; and I have a committee that needs to comment on progress
  - How is the progress of an applicant/researcher measured?
    - Visible outputs of research; // quantifiable research
- We started off with PARs, then we started thinking through our past PARs, then observing /patterns/...
- https://arxiv.org/abs/2012.03736
- Seeing patterns require a high-level view.
- ‘Patterns’ as ‘projects’; parallels to LV’s workflow?
- How can we make our patterns work in a collaborative fashion?
  - e.g. having similar patterns with Qiantan; how do we share?
  - Linked to /common ground/?  How do we find common ground with people?  Technically speaking, but also methodologically/practice-oriented speaking
- It’s fine to do something that we’re enjoying, but there must be something about actualising.  Even if it were just fun; how can we make it so that even more fun.
- Top-down approach of method vs. the bottom-up approach of practice
- https://hbr.org/2005/07/learning-in-the-thick-of-it
- There’s a /link between method & practice/ that has to do with actualising what we’re doing

- RServer allows collaborative writing and editing, but is expensive ($5000 for 5 users). Compare also RStudio Cloud. For people who use R as their main language, they use this.
- We could schedule a person specialised on R-Studio to come present us the piece of software (à la Google Doc presentation)
- Learn from parallel projects; Mark had video introducing people to Spacemacs

- CLA is useful as a reflective tool but there are others as well!
- Requires a larger community of contributors for it to work.
- How do we differentiate authorship in those notes?
- Expectations might not be met, but we are practicing the things that we’ve learnt; it’s what makes it systematic (the machine that builds itself again).

- *Now* (30th January) we try to integrate *my* (Noorah’s) thoughts on a set of notes that we create together across time. How does this work? — But do we care about this in our workflow?  We could keep track of who created what with properties: do we want/need to persist these things? All the CRDT logs to file?
- Saving the buffer with the text properties could do it.
- What problem are we trying to solve?

- Decide on a few tangible activities/deliverables — but this can also take an ‘agile’ approach.

* Some coffee chat follow-up thoughts

** Actions, Patterns, Methods
- Actions are atomic
- Patterns are the relationships (molecules)
  - E.g, people show up at the protest, but the underlying issue is what the protest is about!
  - Cf. Tim Urban on the /instant gratification monkey/ and /dark playground/
  - E.g. piano, figure skating, swimming, meditation (moving to couples skating and ice-hockey)
  - Consider also the /discriminating mind/, maybe more actively deployed in programming?
  - Deploying collective agency with the body... then bringing things to the level of collected movement: ‘organism’
- Methods are the intention (in Buddhism, there’s /right intention/)
  - E.g., sensory mind and discriminating mind as kidney-shaped entities within the mind.
  - Method of how you practice
- Would need a 4th level to account for ‘end’
  - Red and yellow scores for skating
  - How well did you execute it in the case of a quasi-unexpected circumstance? (Compare also the use of data analysis in football.)
  - In Buddhism, putting an end to ‘fabrications’

** Concrete things
- Org-super-agenda
- Patterns
- Routine

* Some ERG seminar points for discussion
** BACK Figure out whether it’s possible to get another column in the default Org Agenda, showing the /directory/
- See Joe’s configuration file: [[file:~/.emacs.d/settings.org::*Org Roam: Library, Scrum board][Org Roam: Library, Scrum board]] → fontify-agenda
- ‘Breadcrumbs’, push everything back but
** BACK Debug the color-coding of lines
- Don’t do filtering before sorting... ask Leo for help with this
** BACK Getting tasks mapped into reasonable packets
** BACK Figure out how to handle tasks that are DONE
** BACK Figure out how to handle tasks that are FROZEN
** BACK Ask Leo how to handle tasks that are not actually discrete doable tasks but are instead projects
