:PROPERTIES:
:ID:       1e46e564-712d-4cd3-9287-37796a651acd
:END:
#+TITLE: 15 January 2022 — Emacs Research Group
#+Author: Noorah Alhasan, Joe Corneli, Leo Vivier
#+roam_tag: HI
#+FIRN_UNDER: erg
# Uncomment these lines and adjust the date to match
#+FIRN_LAYOUT: erg-update
#+DATE_CREATED: <2022-01-15 Sat>

* 15 January 2022  — Emacs Research Group

* Check-ins                                                             :20m:

** NA
- Still testing positive after 12 days of COVID symptoms (congestion, fatigue post-Vegas)
  - LV: In France, 7 days post-symptoms, assuming no positive test
- Mom also unwell
** JC
- Interested in [[https://www.imcl.online/2022-paris][https://www.imcl.online/2022-paris]] even if I can’t go!
  - "Architecture and the Edges of Public Space: Tools and Strategies for a New Urban Agenda"
- Had such a tragedy of errors about the pump-priming he was attempting to submit by Wednesday.
  - Actually, it was Wednesday the /previous/ week, and JC was issued a “too late” notice.
  - However, there was another deadline for another pot of money which would be made available in August; as a result, JC is attempting to prepare something for January 2023
- Feeling foolish but otherwise unphased
** LV
- This is supposed to be the wave that catches everyone
- New president coming in 4 months
- Previously was under the throes of tonsillitis, but has now mostly recovered.
- Had difficulty swallowing for 8 days after the injection, today’s the first day of no real impairments
- Has been focusing on inspiration and shoulder PT (with good progress)
- But, hasn’t done a lot of work; so has called this an extra week of holiday; and getting back to work on Monday. This will conclude the 1-month-break, feeling good to be back.
- Regarding inspiration: has been reflecting on the themes of mediocrity, conservatism, risk-taking: the less risks you take the more staid (not amusing, boring, old fashioned) you become.  How can I think about risks in a different fashion, and trust myself more?
  - NA: You’re not staid!
  - LV: Any person who likes working but doesn’t work will feel a sense of atrophy, and I’ve been sitting in this area out of a desire to rest
  - JC: Kinda harking back to a point NA had left us with at the end of our last session, especially a comment we’d made about creative work. [JC: The phrase was "Light creative ‘work’."]
- LV: I’d made a lot of progress on my own, and the changes were important and great!  Perhaps the time is great to see if this fire can come back into the professional endeavours: to link up the creative fire and desire for change w/ the professional career.

* Meta points

** Longer checkins this time because we had a longer break!
** DONE Don't forget to record the session!                             :LV:

* Agenda, Part 1                                                        :20m:

** Discuss mission and vision of the group
- Shared conclusion between LV, NA and JC: The CLA is great and all, but it doesn’t seem like we’ve appropriated the tools.
  - JC: Could we find a review method that is more shared?
  - JC: What is the review mechanism that works for all of us?
- NA: When we schedule the CLA, should we have a meta-session on how we prepare for them?
  - JC: It would be a way to harmonise the ways people think about the problems.
    - "Intercoder validity" is one term here

      - Litany, Systems, Worldviews, Metaphors+Myths

- JC: Could we use the last CLA to gather up materials (at least, tags or keyword)
  - JC: Reminds him of a book about noting/noticing thoughts and their nature

*** Theme of collaboration
- Need a balance between individual thinking and collaboration; how can we use this time so that we go deeper and aren’t affected by "groupthink"
  - Good reason to do some work individually, and coming in with that done
  - LV: Good to ensure that people are providing an amount of work, not for surveillance, but just to say "this is what we’ve done"
    - Last year, we generated notes: at least we could say "we did this work on Saturday".  It would be even more structuring by saying "I did this myself, I contributed this point to the discussion."  This would provide the wireframe to go from

- How can we gather up the interesting things we’ve done during the week?
- Sometimes we remove our shoes, and this other stuff fades into the background; if we’re moving to a 1 hour meeting, maybe we need to think about what we’re doing in a way that can be infused
*** ERG Mission
- collaborative thinking
- Light creative 'work'

*** ERG vision

*** Relationship with difficulties
- Absence
- Relaxed mood vs tension + fractiousness
- Previous efforts expended with reining in frustrations
- Individual benefits vs interpersonal angst


** Discuss norms and values of the group
- Clarity about what we want as a group!
- JC: In a sense, if someone else came along and started rubbing us the wrong way, this would be the sort of things to be brought into play.
  - If we want "light creative work" we need the feelings that go with it
- NA: Professional group therapy: everything is allowed to be discussed, people have feelings and reactions but it ends there: the commitment is that you show up the following week
- LV: Group/therapy, with some share-ability of what we discussed. The first thing we need to worry about with regard to a future, is to have feedback (which works!); in the spirit of lightness we shouldn’t outlaw feedback.  If we think something isn’t going the way we think it should be going, we should be voicing that.  And I like the group/therapy idea, or something that’s not just about problem-resolution.  We also want input-output, research, and delivery.  Perhaps the time would be now to consider the idea of outputs (both with light-creative work and healing that happens by sharing the way we’re working and what we’re doing in our individual endeavours).

  - NA: Not everything needs to be resolved (agree)

- NA: And still working within Emacs; maybe our mission could be to create systems or packages; "ways we can use Emacs to work collaboratively"

- JC: [Will have stuff to answer after the break.]

- JC: The trouble/pain we were feeling is a form of feedback, and ignoring it would have been at our own peril.

- Intensity: this is a good thing to look at.  If there are 3 well-crafted things to say, this can be intense.  If intensity is compounded with rawness or nervousness, your focus starts moving from the content and more to the mode in which it’s being delivered; and this detracts from the substance and gives more salience to the health and nervousness factors.

- NA: How about, coming into the meeting, we check out our personal baggage: what’s the emotional intention, creative work, easy going.

* BREAK (at quarter past)                                                :5m:

* Agenda, Part 2                                                        :20m:

** Discuss scope of the group

- JC: This same group of people could be delivering paid work[?]
- NA: Saturdays could be "what are we bringing into the next EmacsConf?"
- LV: This would be a nice way to address something we’ve been talking about, which is: what are we working on, how do we work as a group?  This was kind of kickstarted by presentation(s) we gave at EmacsConf
  - JC: Another elephant in the room: is writing paper something that we should strive towards?
  - NA: Maybe a website of or notes?
    - NA: Could use Org Roam to design the website and how things link to each other?
    - JC: Could this be linked to the proposal with Abby?
      - Right now, we have a heartbeat (i.e. weekly meetings), but we haven’t proved if it were a good thing yet?
      - What would be the next increment over the heartbeat?  Some degree of "validation", perhaps!
    - NA: We could use our ERG Saturday meetings to experiment with those ideas, which would work into presenting it at EmacsConf.

- NA: Moving away from papers as a way to communicate with the public; I don’t care about communicating with academics anymore
  - JC: Hence book-writing!  If you have to write 2–3 papers to academic to validate the idea, it detracts more than it helps.
  - NA: And it doesn’t necessarily have to be a published physical book, it can be something more interactive
  - JC: Could we go back to RP, suggest him to come check in with us on a monthly basis?
- How to bring an audience? (Or a public?)
  - JC: If we look like at our the presentations
- LV: We will have EmacsConf, that public!  Do we need a panopticon for checking on immediate progress?  Well, if we log on a website, people can check it if they really want to (having been recruited from EmacsConf etc)
- LV: We do have interested parties that we gathered from previous EmacsConf, who could be invited.  "Thinking about why we are meeting today" and simplifying; knowing we can work together, having 60% of the tools.
- Open to novelty with other members, and don’t want to start dealing again with problems from last year
  - JC: Perhaps we should think in it in terms of network: we’re doing this stuff here and now, us three, but people interested by what we’re doing would only be one or two hops away from hearing about what we’re doing.
  - Variant of the leader/member/observer ontology we talked about.
  - There’d still be "members", and we’d want to make all the people active in the way they can provide.  If people want to share things that they discovered, good!  If others want to share such things with us, great, they can share things with us.
  - So, this gets back to NA’s ideas about individual contributions; maybe Ray’s been sharing notes to this effect (and without stress)
- NA: The goal is to discuss ideas on how to utilise Emacs for the work that we do, and I like the soft goal of EmacsConf that keeps us a bit focus
- JC: If Emacs itself remains the focus of those sessions, then we’re good to go with EmacsConf or any other venue that talks about Emacs.

- LV: We’ve been striving for simplicity, even with some long points also tied to this purpose.  We’re highlighting one of the problems we had before.  Some people came to the meetings because they enjoyed our company and energy, and, yes, it’s energising!  But we did lose focus of what we’re trying to do.  And based on these things we ended up committing to PLoP and thinking about how we work as a group, not about Emacs.  So, the objective of "just nailing the EmacsConf next year" could be centralising.
  - That’s for ERG; more broadly we haven’t been meeting for coffee chats or workshops over the holiday.  If people were coming to ERG b/c it was giving them energy, or just to share their expectations of the week.  I’d say: I’m looking forward to modifying ERG to the above purpose; perhaps we should also be looking forward to other moments (e.g., 1-to-1 conversations or efforts on technology); can we use the time slots that we were using before for "actual work" more for some therapy aspects.  Let’s try to think in terms of therapy + generosity in the other times.

** Open forum

Meta:
- This section would be nice to cover, but only if time allows us to.

- Simplicity
- Context of UWE work (≈£10K to budget in detail and then spend down)
- Share information with open source work

- LV: Wondering how to place "something": the commse lot of things latel I’ve been equipping myself to jump.  And now is the time to mobilise this great stuff, regardless of interview-prep.  I’ve been in stasis, which people often associate with depression and powerlessness.  I’ve been preparing a bunch of soft skills and asides.  There’s an unquenchable fire to do stuff!  To mobilise the same amount of regularity and performance that I’ve been able to mobilise in sports back into programming.  I’m not starved for projects (e.g., fixing things in emacs or getting a job in programming).  As a result I’d like to have some focus on my fortés!  E.g. technical aspects of the meetings, design features we would like to have in Emacs.  Timers, TODO-moving, all that.  Bringing distance, designing stuff together.  So I’d appreciate it if these moments can also bring material that I can work on, and I’d like this to be the individual contribution that I bring to the Saturday meetings.
  - NA: Yes, part of this is about thinking about solutions that make our meetings better.  We’re prototyping ideas on Saturdays.  Nothing crazy.  Nothing too serious, let’s have fun creating.
  - LV: Yes, there’s the idea of casual progression; but I also want the goal to be great.  A great suite for meetings inside Emacs.  Casual rhythm of daily or weekly work is fine.
  - NA: Would an org mode suite for meetings be a reasonable goal to present?
  - LV: If last year was the year of collective work, I was spending more time in meetings, I’d like more time in solo experiences but also to connect it to the collective work wagon.  Not necessarily more meetings, but more about the "non-stress" dimensions (e.g., before Saturday); I don’t want to have to report on bullshit work for example.  I want to be able to do solo work that’s meaningful for ERG or other endeavours.  If we want to have other sessions about, say, slides.  We won’t do it on Saturdays; but with an ambiance that’s more stressful.

Points:
- Try to get org-tag-realign (not actual name) working for NA.

* PAR                                                                   :10m:

*** 1. Review the intention: what did we expect to learn or make together?
- Clarify how we 'work' together
- Scope of ERG
*** 2. Establish what is happening: what and how are we learning?
- We’d like a "Relationship with difficulties" that itself feels light fun and creative, not adding even more difficulty
*** 3. What are some different perspectives on what's happening?
- LV: We’re back after a month, but we’d been meeting weekly before then. We remember each others names but not that of their cats.  There’s some distance and asyncronicity.  And we’re all tired, each in their own ways and time zones.  If we met at a different time it might help!
*** 4. What did we learn or change?
- Chronos crash can cause propagating crashes
- Dormancy isn’t opposed to creativity, but I don’t want to bring saturnineness
- Idea to focus on Emacs, firstly, and EmacsConf, secondly; and a support group aspect, thirdly.
- Cf. "Feeling Good" book
*** 5. What else should we change going forward?
- JC: Let’s keep doing the things that support our work together (namely LV and Qiantan’s work on making crdt.el better; similarly Joe and the peeragogy folks, assuming that’s useful).
- Could make the time 1600 UK after some negotiation? Leo would really like that, and it should be possible for Joe’s family (maybe appreciated by the West Coast folks)
- NA: Create journaling prompts for every day?  Emacs could ask me a question, and it would ask me another question when I am done.


* Tentative agenda for next week

** Changing the time to 1600Z (not for [2022-01-22 Sat], but for later moments)
*** WAIT JC’s discussion about switching the meetings with his folks

** Explore LV's psychotherapy.el
- It won’t let you conclude until you walk through all the steps
** Joe to bring the text-analysis code (if it can be found)

* Check-out                                                              :5m:

** NA
- I had fun at this meeting.
- Going for a nap (maybe?)
** JC
- This was a good, effective meeting!
- Thanks for tech trouble shooting; Appreciate the extra work of chair and tech trouble shooting stuff
** LV
- Was happy about the meeting and not feeling stressed
- JC: Invite Monday 0815Z for a joint meeting with Alex? As a way to roll over swimming energy into programming energy.
