#+TITLE: 09 January 2021 — Emacs Research Group
#+Author: Noorah Alhasan, Joe Corneli, David O’Toole, Raymond Puzio, Cameron Ray Smith, Leo Vivier
#+roam_tag: HI
#+FIRN_UNDER: erg
#+FIRN_LAYOUT: update
#+DATE_CREATED: <2021-01-09 Saturday>

* 09 January 2021 — Emacs Research Group
** Hello/Checkins
- Dirk Gently
- Free software 2009
- 4PM UTC Unstandup — 20mins
- Wong — comedian
- CRS: have more free time in January! — December was lots of time working in Hospital
- NA: ‘Wednesday’ :-( ... other than that, working!  Big topics of talk in poli-Sci
 - We know this was coming! Came late in the 4 year term
- DOT: Doing fine, keeping busy, working on audio software, dog, nieces/nephews! Can be difficult to meet after they arrive
- JC: Exercise missing. £1250 to spend soon... maybe? Survey methods teaching maybe soon!
- LV: Was teaching middle school earlier in the year. Online teaching methods... ‘obviously teachers are prepared’ — Nope!  Now, still on break, relaxing some: enjoying the break & sense of rejuvenation/time to think. Retreat (w/o trying to think too much about things); coming back refreshed. Did think some about our project... 50/50 resting & preparing; after 1 week will be free to work our projects and/or find new employer!  Thinking about life!
- RSP: Sends apologies, had other things to do now.
** Collab slip box
*** Intro
- Ran into problems in general and w/ Org Roam
- Work started but...
- Ping pong between technology and methods
 - There are plenty of things we can develop!
- Do we need to separate complex & atomic notes?
- Does this disrupt our flow?
- When you try to think about the technological aspect, things get more and more complicated; whereas when you try to use the tools you want them to be as simple as possible
*** Summary
-  At first it is liberating, when I use this method I don’t have to think about what to do next
- I can freely write and it feels different from taking linear notes
- The question of how to do this collaboratively is somewhat unsolved
- Including collaboration as a feature... at the outset it will appear to add complexity
- We shouldn’t be too surprised/afraid: let the problems manifest themselves & address the problems as they go along
*** There are problems w/ the tools we have...
- OR has "one slipbox" principle
- LV: has a =.dir-locals.el= that sets things as appropriate
- Doesn’t merge w/ any ‘global’ file.  Needs absolute path to the dir.
- What’s frustrating is that the concept of ZK and method (atoms and links) is somewhat nebulous
- It helps you not have to think about structure right away
- At the same time, with the tech aspect of the software, it seems we need to implement tools that help you build structure across your notes
- You may have both ‘atomic notes’ and ‘complex notes’
 - E.g. "Challenges of async editing under version control"
  - ‘Creates conflicts’
  - ‘Obfuscates authorship’
** Technical
- Trying to follow *Andy Matuschak’s* way of writing titles w/ statements & questions
- E.g. ‘what are the actual benefits of using the slip-box method?’
- How to sync work across diferent ‘locales’ (topoi?)
** Methodology in general
*** This is key to solve today
- LV: Let’s review, based on your practices
 - Let’s try to crystalise something we can use /for the coming week/
 - We don’t need to solve methods for the entire project
- CRS: our proposed solution is mainly techinical
 - How to seamlessly transition between notes to self & notes I want to share?
 - We may have multiple groups that are partly overlapping
 - “How can I view my slip box as the /union/ of all of the different subsets of notes, while maintaining the ability to designate a subset of that union as notes that I want to be incorporated into ERG, some other group, etc.?”
 - How can I avoid losing the advantages of Zettlekasten method (inihibition)... but still have a little inhibition about ‘does note A contain something relevant to group X’... or is it something that only I would understand?
 - Can this be somewhat seamless so that I don’t have to exit the basic ZK mode?
*** "E pluribus unum"
 - Thinking about other notes to add
 - Slipboxes are deeply personal!
  - Luman: wrote papers based on what he had categorized
  - If you are trying to work together need a degree of exhaustiveness
  - So that people who read your text might be able to understand what you’re trying to say
 - If they are personal, we write everything that we think/discover
 - But, say, NA & LV are working together; they will have different notes and will need to work on different files.
- Every time I was adding a note, do I need to update my own note?
*** "Raison d’être"
- These are actually unsolved problems in general, not just for us
- Part of this: what would a collaborative adaptation of both the methods & tech look like?
- Can we shrink the /resultant complexity/ to a degree where it’s not overwhelming?
- The experience of some complexity is a good thing to go after to get a sense of engaging in novel research.
- Any type of collaborative/collective work is going to be complex
- We have both a great tool & a self-reflecting tool!
*** Meta: How to present these questions?
- Questions?
- DOT: I installed OR, task was to enter notes from sound project
 - Learning by immersion
 - ‘Hotori ... Wikimagate’ — write fragmentarily, read collectively
 - Hit up LV on IRC.
- NA: Compartmentalisation problem; textbook is huge collab problem
 - LV: Struggling w/ context-switching; Emacs Conf
 - Context-switching between acad & professional life will cost you presence in the topics you’re discussing
 - Wanting to take the serendipity you might get in multiple topics
 - Focus is good, but if we are advocating a sense of trans/inter
- Maybe keep in mind that we can try to anticipate problems but we won’t be able to solve all of them in advance
*** Example
- I have a note about /metaphor/: this helps physicalize the concepts
- How to I share elements of this with others?
 - Start working with transclusions?  Can we do this efficiently?
- Examples of metaphors:
 - Evergreen notes
 - Garden
 - Network

*** Possible experiment: put ourselves in the shoes of people who haven’t ‘drunk the Kool-Aid’ yet
- Many people will have a violent/frustrated response
- We’re reasonably willing to experiment b/c we’ve found values
- Another group would challenge our perspective, e.g.,
#+begin_quote
‘Why don’t you just take notes in a Google Doc?’
#+end_quote
- So, how about “Have a Google Doc, and use whatever alternative is reasonable...” and then another week to compare this *GDoc* experience to an OR experience
- This would help us empathise w/ others’ legitimate skepticism
- Then try to collaborate on the process of setting things up
- Then try to think in a detached way to analyse these experiences in a comparative way.  Use the fact that we were imagining doing such an experiment as many of the issues that will arise.
- What else can we offer?
- Maybe not so much to convince others but just figure out what’s usable ourselves?
** Example: NA I have to collaborate on a Google Doc w/ others and will make notes on that
- What are the pain points
- Yesterday I was exploring git & writing
- Magit: this does a cool thing where the diffing is at the word level. This is very helpful. GDoc does something a bit similar with versioning
- =auto-fill-mode= will automatically split your line; it will go back to the beginning after 78 characters
- Will need to work w/ David on this and git too
#+begin_quote
Here’s an example...?
#+end_quote
** Question: does Org-Roam allow you to ‘file’ things by tag?
- Multiple slip boxes are supported but they are hacky
** Envisioning what’s next beyond Regular Roam?
- JC: Serendipity paper as a potential case study (writing clinic?)
- Usefulness for members of the Open Global Mind and friends community (e.g., users of “TheBrain”)
- Try to support Logseq (which removes direct dependency on Emacs), and maybe could be nice to support work w/ devices that don’t have Emacs installed
- Knowing this will work for us and need to make it a reality... this little experience of trying to make a ‘collaborative slipbox’ has been simmering
- LV: Yes, there’s a vision! OR maybe a bit limiting understanding of what could be done w/ the method
 - At the core, OR is just backlinks in Org Mode.  We have the underpinnings of the ZK method, more or less forcing people to have a single slipbox, preventing people from creating multiple... this felt ‘dogmatic’ — /There’s so much myth surrounding the slipbox method!/
 - There was plenty of articles on ZK (some scientific, some sensationalistic) in 2020
 - In the process of popularising the method we ended up with a muddle
 - The veneer of simplicity (it’s just atoms and links)... lots of people said ‘that’s a good way to tackle the resistance I’m feeling’
 - But it’s actually a more complex!
- “How to take smart notes” book: not rigorous enough (either for self or how to make it collaborative)
- How does what we’re doing here relate to Wiki?  We’ve moved away from what ZK was.  
- Are we trying to create something that has a method to it — more than just notes and atoms (How to Design Research?)
- Maybe we ought to get started on working on /this method/
 - A machine that builds itself as it goes!
 - E.g., we don’t need to track authorship (b/c we can let Git do this)
 - It would be good if we could have collaborative editing... all this to say!
  - Do we need to redefine what this whitepaper is about?
  - Developing a /new method/...
  - vs covering both practical aspect of collaborative research & interesting complex aspects...
- Developing software that works for our research?
- Before org mode there was planner mode & remember mode. You could hook them up.  The thing that received the initial deposit of thoughts, w/o having to navigate into a structure to see where it fits.  Maybe you could put some meta structure on top. F12: I don’t have to choose where this note goes — one ZK or another — and use a separate package to capture pieces of inforamation...
- For the vast majority of problems, the technical stuff won’t be the major problem; e.g., transclusions &c., if we have good reasons to implement it and people motivated, we can do it. Nothing feels impossible, it’s just an investment of time. crdt... a little more complicated but it doesn’t feel like an intractable problem.  This is reassuring.
- If thinking about methods to do research is the only (major?) thing we need to spend time on, this feels like something a research group could tackle... For us, not only are we finding the lay of the research field, but we’d also be developing something at the end that ushers in a software that does everything that we wanted and missed w/ other software.  Vehiculate ideas of free software and what it’s good for; also allows rich research (incl. transdisciplinary research) to evolve
- LV: Deleuze’s concept of ‘rhizome’ — concepts have a life of their own & can move to another field (‘deterritorialization’)... I discovered this in my 2nd year at University, and have been striving to find tools & methods that allow my thinking to work like this
 - You can think nonlinearly w/ a sheet of paper!
 - But what tools encourage you to think like this?
 - To... have a second brain which invites you towards transdisciplinarity... this feels like a revolution!
 - The work can be informed both by cognitive science & philosophy!
- CRS: I like focusing (here) on the direction we’re really interested in, and not getting too caught up in technical detail
 - Wheeler: don’t proceed to calculate until you have a good sense of where the calculation is going to go (the answer)
 - There’s a risk of calculating w/o knowing what we’re trying to calculate!
- One of the questions: should we not allow there to be a straightjacket of producing a ‘whitepaper’?  What’s the collective interest?
- CRS: Learn more deeply w/ a broader purview... These prevent us from finding paths toward learning
 - How does one approach any new question?
 - Our ability to ask questions...! There’s a pure unadulterated perspective in a group to ask questions & revise the collection of questions... b/c we have sythesized information, e.g., 1000 questions into 10!
 - A certain genre of philosophy would push back and say this is just scientistic reductionism (it’s possible to engage in lossless compression? Not nec.). BUT there’s advantage from a practical perspective to be able to compress information.
 - Many mathematicians are fueled by ‘compression’ and it’s beauty as a motivator.
 - How to approach the wide range of possibilities? Be able to navigate communities focused on e.g., literature, while navigating physics, computing, and so on.
 - How would someone who has investigated these topics for a long time think about these things? If you’re willing to go through the laborious process of getting degrees and becoming card-carrying... BUT now the information is out there and we wouldn’t necessarily have to go this traditional route.  The problem is that we don’t seem to have the best representations of the questions so we can know what’s been learned in the past and we don’t know what the most important problems are.
 - This question of how can we learn collectively, taking advantage of interdisciplinary interests & backgrounds, and not just transmit but allow a process of communication to enable each & every one of us to learn & improve collectively...
- CRS: I have some intuition that attempting to coordinate on an OR... can make some progress on this grand vision & discover the extent to which each of our visions may be relevant; making communication between individuals just as fascile as building a personal wiki is for the individual. ZK preceded development of wikis; it’s one way to discover linking; Wiki discovered doing it collectively.
- The relationship between ZK and wikis...?  What if you built it with a smaller & more tight knit group
- Wikipedia editors usually aren’t in tight communication with each other
** Key take-aways
*** Reason why we got together: there was a diamond in the rough with the method
- The ‘panacea’ / ‘fad’
- Work is not finished when it comes to finding the best tool
- ZK: by essentalising note-taking, we have the best wireframe to develop a tool which is true to a method we can develop...
- OR: is a limiting factor, but it’s probably the best we have now for developing onto the wire frame
 - Maybe the design of OR simplified but not in the right way...?
 - So we can question some of the principles to contribute to a method... that we can connect w/ something glorious!
- LV: The process of ‘refinement’ seems key
 - we can access academic journals (often for free)
 - But: we also see people calling for ‘simplify, simplify’. If someone is overwhelmed by the choice of which book/person they should be learning from, having a system that says ‘you just need to find the atoms & link them together’ is alluring
 - What we’re looking at here is how to get information from as wide a sample as possible
 - Scraps of paper, Post-It notes; now it’s 4 keystrokes away!
 - With the technology we have in the context of HCI allows a wide surface that we can gather based on readings & serendipity & discussion... but also condense all of this information (carbon into diamond)
 - Tech plays a role of both cataloguing and refining knowledge
 - Yes, we have good tools for cataloguing things (Zotero, Evernote)
 - But when it comes to going from ‘raw carbon’ or ‘dirt’ to diamond... I’m not sure there are good methods!
 - Are computer & tech really being used to facilitate this process of refinement?  This seems like an essential process to tackle
 - Elaboration is an action word that means taking something and incrementing it so that it has more value at the end
  - JC: Cf. ‘Augmentation’
 - Trying both, to keep us open-minded about the process & to have some output at the end...
  - Meta-perspective: maybe the way we narrowed before wasn’t the best?
  - More food for thought...
  - We also need to think about the viability of the project & precarity of LV’s position (e.g., grants)
  - Could this project be presented to a research group?  Finding a methodology for research...?  Is this the gold we were looking for?
  - LV: As far as my interest concerns there seems to be a wealth to be exploited here.
** Review
*** 1. Review the intention: what do we expect to learn or make together?
**** Desire to work on methodology: address the many hurdles LV faced with collaborative slip box
*** 2. Establish what is happening: what and how are we learning?
**** Over the week, got a clearer notion of what’s going on here after looking at OR in action, will look at things after the call
**** We’re all getting to know each other better during the week
*** 3. What are some different perspectives on what’s happening?
**** LV & CRS had a lot to say today! (<5 mins each? Length of intervention was a result of the topics! There was some free association style.)
**** Taking a step back was helpful
**** exp2exp wiki does exist, paired with Tyler on Firn, we could go on w/ this
**** JC: Loved the reference to Deleuze
**** About these PARS... the method of ongoing review still needs improvement
**** We missed Ray... would be nice to pass him a link to the recording (later in the week)
*** 4. What did we learn or change?
**** Today w/o necessarily setting out to do this we took steps back to think about what we’re actually doing: more concerned with direction than outputs
**** Missing link in HCI: refinement! Another: the importance of collaboration! — Everyone is able to collect a lot of data, but if people can’t refine... collaborative writing based on refinement of drafts &c; is not a proper way to elaborate
*** 5. What else should we change going forward?
**** Awareness of the adversarial process in review of research
**** Seed the collaboration by collaborating on an OR instance
**** Maybe not call it a ‘white paper’ — we want to continue this exploration, including infrastructure
**** We could learn more from these if we start from a review next time: the distinction between skillful & unskillful (e.g., start w/ a 15 minute review next week where we use these as data); possibly bring this in as a monthly cycle (review method)
**** LV: Planning to go back over notes & improve current ZK to share
**** Same time next week 17:30 UTC next week!
