:PROPERTIES:
:ID:       76cf8572-ac39-4e98-976b-923e695d2469
:END:
#+TITLE: 22 January 2023 — Extra meeting with Abby before the workshop
#+Author: Noorah Alhasan, Joe Corneli, Leo Vivier
#+roam_tag: HI
#+FIRN_UNDER: erg
# Uncomment these lines and adjust the date to match
#+FIRN_LAYOUT: erg-update
#+DATE_CREATED: <2023-01-22 Sun>

* 22 January 2023  — Emacs Research Group


* Check-ins
:PROPERTIES:
:Effort:   0:15
:END:

** NA

** JC

** LV


* Meta points

** TODO Pre-PAR — Review the intention: what do we expect to learn or make together?
- Keep working on the workshop


* Agenda (Part 1)
:PROPERTIES:
:Effort:   0:20
:END:

** Run-through of what we are going to do today.
- 09﻿30-1000. Arrival, tea and coffee (Waterside 3)
- 1﻿000-1030. Media screening (Cinema 2)
  - Big scale aim:
    - Setting the scene: “These are the moving parts”
    - Presenting the concept of polyphonic documentaries
- 1﻿030-1230. Session 1: experts to citizens (Waterside 3).  This is about context, stripping expertise, going to the root myth.
  - 1030-1045: Introduce the workshop theme and core question using *slides* [AT]
  - 1045-1100: Placing people into groups and setting up the room
  - Introduce the workshop format using *slides* [JC] (up to 15′)
    - In short, if the problem could be solved by individuals using standard methods it probably would have been done already.
    - Phase I is going from the immediate observables to the shared values.
    - Phase II is going from the shared values to alternative futures.
  - _1145_: LV is available and we begin a process of condensing what was done in phase 1
  - Distil everything into one *overall map*
- 1200-1215: Groups come up with elevator speeches and use their boards to prepare the presentation
  - Ask the groups to come up with a 2′ elevator speech on the key points that they’ve discussed during phase 1.
- 1215-1230: Presentations of the elevator speeches
- 1﻿230-1330. Lunch (provided)
  - Working lunch for facilitators, so have a *premade lunch*
  - Finalise distillation of map
  - Walk through map with Noorah from _1300_
  - Ensure that we have people only as citizens, not as experts; they have reached a ‘centered point’ in which everyone is harmonized.
- 1﻿330-1500. Session 2: citizens to action (Waterside 3).  We want to generate patterns with some degree of mobility from the original context.
  - 1330-1345. LV and NA present the technological translation of the notes into org-roam, justify the use of technology (vs. pen & paper), and provide instructions for participants to connect to the chatboxes as a send-off to JC’s introduction.
  - 1345-1400. JC present phase 2: roles, rotations, context/problem/solution articulation, keywords
  - Old notes
    - Joe to provide some =HOWEVER= =BECAUSE= =THEREFORE= =SPECIFICALLY= *cards* and show how to use them
    - Participants continue to work in small groups to explore scenarios that explore the original problems, and come up with *coherent next steps*
    - Introduce *the Lounge* tool for Phase 2
    - Pictures of these can become *proto-patterns*, see example below; these are the prismatic reflections of the original problem AT presented
      - With given proto-patterns, ‘However’ means a bridge between contexts
    - Leo and Noorah work in the background to turn patterns into a *pattern language*
  - 1445-1500 (Okay to be used as overtime): “Have you fond anything you want to do after the workshop?” (link to next actions)
- 1﻿500-1530. Review and close (Waterslide 3 & Cinema 2)
  - 1500-1515
  - Old notes
    - Screenshare Org-Roam-UI with basic patterns in it; as a prototype, can we view the central problem as the apex of a double cone of problems?
    - We want them to understand that this problem is related to a whole *array of problems* (things this is not, but things it is adjacent to); this will contribute to motivating the participants because they’ll realise they have new superpowers.
      - Who else do they need to talk to?
    - Not only are they harmonized (from Phase I, they are also somewhat unblocked)
- 1﻿530-1700. Reception (Watershed bar)

** 

** Introduction of Phase 1 (15′ max)
Considerations:
- We can tell them about the whole workshop.
- The introduction should be a very high-level introduction to the workshop, but detailed about phase 1.  The goal is not to provide them with information that they might forget by the time we get to phase 2.
- How to introduce litanies, systems, worldviews, myths: a quick description, and a type of question.

** Introduction of Phase 2 (15′ max)
Things to bear in mind:
- Remember that it’s preceded by NA and LV’s presentation of the technological translation of their work in phase 1.

* BREAK                                                                 
:PROPERTIES:
:Effort:   0:05
:END:

* Agenda (Part 2)                                                                
:PROPERTIES:
:Effort:   0:20
:END:

* PAR                                                                   
:PROPERTIES:
:Effort:   0:10
:END:


*** 1. Establish what is happening: what and how are we learning?

*** 2. What are some different perspectives on what's happening?

*** 3. What did we learn or change?

*** 4. What else should we change going forward?


* Tentative agenda for next week


* Check-out                                                              
:PROPERTIES:
:Effort:   0:05
:END:

** NA

** JC

** LV
