#+TITLE: Information Epoch

* Introduction
  :PROPERTIES:
  :CUSTOM_ID: introduction
  :END:
Times are changing and people have lots of different suggestions about
what to do about it. Ben Casselman suggests via /FiveThirtyEight/ that
we may need to go back to a service economy [1]. Elisabeth Mason writes
in the /New York Times/ [2] about social applications of AI and big data
to education and job search. Richard Partington writing for /The
Guardian/ notes that technology stands to boost efficiency, while
raising questions about employment and worker's pay [3].

We have been working together on artificial intelligence research, one
application of which will be robust tutoring applications in mathematics
[4]. As such we could only agree with Mason that AI tutoring has
significant educational potential, while we note that much remains to be
done on the way to building serious user applications. It may be several
decades yet before mathematicians have to worry about job loss due to
automation.

In this paper we combine demographic data with AI-inspired thinking to
help understand the current situation and plot out some likely
trajectories for the future. For example, we were excited to consider
the prospects Mason pointed out, namely that somewhat similar
technologies could be applied---and probably much more rapidly than
mathematics tutoring---to help people find jobs. Why should a job seeker
apply for multiple jobs each week if all they need is one, and a
computer program can help make the match? In our view she is spot on
here. Naturally the themes of education and job search are related,
since in order to qualify for new jobs people may need further
re-training. But this does raise a rather difficult question: what makes
learning efficient?

Once, the answer might have been straightforward: apprenticeships.
Nowadays, someone entering the the job market finds something very
unlike the past of 100 or even 50 years ago. In another 50 it may be
recognizably different again. Jobs themselves are changing, and the ones
that are gone are not likely to come back again (how many lamplighters
do you know?). Nowadays, a computer and a reasonable understanding of
how to use it are a basic requirements for many jobs. Working often
involves learning new skills (as we know from our own work). Education,
too, is affected by technological change, indeed, this sector of the
economy is "rapidly evolving" [5]. Social inequality in the West still
has striking features, and global inequality even more-so. At the dawn
of the millennium, World Bank researcher Branko Milanovic wrote: "An
American having the average income of the bottom U.S. decile is
better-off than 2/3 of world population" [6]. To cope, entirely new
online and social infrastructures must be developed, along with
knowledge of how to use them. AI and big data will help but will not
directly solve these problems. People will have to be ready for change,
which these days does not simply mean moving across the country for a
job. We think that understanding the interactions between people, and
between people and systems, will in the long run be more important than
deploying new high-tech management techniques.

We expand upon these points in the following sections.

* Looking backward: 2015--1910
  :PROPERTIES:
  :CUSTOM_ID: looking-backward-20151910
  :END:
In order to get a long-term overview of employment trends, we will begin
with the tables of non-agricultural employment by industry at the
beginning of the twentieth century versus the beginning of the
twenty-first century which appears as Table 3 in the centennial issue of
the /Monthly Labor Review/ [7]. Looking at this table, we note that, in
2015, the two largest sources of employment were "Wholesale and Retail
Trade" and "Other Professional Services"; together, they accounted for
51.9% of the sample. Comparing the 1910 data against the 2015 data, we
see that the largest private sector growth has been in the following
areas:

1. "Other Professional Services" grew 863% from 3% to 28.9%.

2. "Finance and Real Estate" grew 185% from 2.0% to 5.7%.

3. "Educational Services" grew 177% from 3.5% to 9.8%.

4. "Wholesale and Retail Trade" grew 73% from 13.3% to 23.0%.

While "Wholesale and Retail Trade" is large and has grown, it may not
remain large much longer due to automation and e-commerce. According to
a recent report"Technology at Work" [8] 63% of sales jobs could be lost
to automation. This impending change would undo the growth in retail and
leave it significantly smaller than what it was in 1910.

While a large part of the decline in manufacturing is due to
outsourcing, this alone does not completely explain the trend. As
pointed out in a 2016 article in the /Washington Post/ [9], even when
industries which were outsourced return home, due to automation, they
hire far fewer people than they did previously. This has led to a
situation in which production is rising much faster than employment.

Looking at table B1 of the BLS report, we see that the heading "Other
Professional Services" includes subeadings such as "Computer systems
design and related service" which did nor exist in 1910. Furthermore, by
2015, office automation was rather complete --- filing cabinets,
typewriters, and the like had all been replaced by computers and the
corresponding job descriptions such as "typist" had gone away. In
addition to accountants, lawyers, analysts, brokers, etc.,the financial
and professional services sectors now hire a significant number of
programmers and data scientists and almost everyone working in that
field is expected to be proficient at using computer programs relevant
to their jobs.

The upshot is that, over the course of a century, jobs involving
physical, in-person work have declined without decreasing productivity
due to automation while jobs involving mental work, including those
which make automation possible, have increased. Projecting this trend
forward into the near future, we propose that we may soon arrive at a
state of affairs in which, say, 25% of the working population suffices
to staff the agricultural, manufacturing, sales, and transportation
sectors of the economy with the other 75% working in information-related
work such as education, research, programming, engineering, design, etc.

* Are we in a new historical epoch?
  :PROPERTIES:
  :CUSTOM_ID: are-we-in-a-new-historical-epoch
  :END:
We claim that the changes described above are the beginnings of a new
economic-technological epoch, the previous three having been the
hunter-gatherer epoch, the agricultural epoch, and the industrial epoch.
Hence, in order to understand these events properly, we need to note
that basic assumptions may have changed.

The names of these epochs refer to the predominant sector of the
economy. Predominant does not mean that the other sectors are uniformly
unimportant but rather that the predominant sector tends to be the
largest and is an important part of how value is generated in all
sectors of the economy. For instance, during the industrial epoch people
still needed to eat and hence depended upon agriculture for their
survival. However, the introduction of equipment such as tractors and
threshers turned agriculture into more of an industrial process and
choices of what to grow and how such as favoring monoculture were in
large part determined by technological considerations. As a result of
the efficencies of industrialization, a family in the Midwest and a few
hired helpers can nowadays cultivate 1500 acres, a plot of land as large
as the holdings of a manor lord which were cultivated by an army of
peasants, and the proportion of the labor force in agriculture has
dropped from 90% in 1790 to 30.9% in 1910 to 0.7% in 2015.

Likewise, in turn, a society of the information epoch will still depend
upon agriculture manufacturing and distribution but, the way in which
these activities will be carried out will be heavily dependent upon the
information sector and, as a consequence of the resulting efficiencies,
relatively fewer people will be needed to provide these vital services.
Returning to agriculture, one can expect that agricultural machinery
will get smarter and thus be able to do things which currently can only
be done by hand --- dreaming a bit, there might even be a swarm of
drones which pollinate flower-by-flower, though today's state of the art
farm robots would not have much chance of picking a tomato or strawberry
without crushing it [10]. Future technology could make it feasible to
replace monoculture with more ecological cropping patterns which take
advantage of micro-climates and symbioses while still retaining the
economic benefits of industrialized agriculture. However, doing this
well will require programs to analyze the sensor data, model the
environment, and coordinate the drones --- the costs of research and
development and the work needed to write and maintain this software
could easily dwarf the effort need to build and deploy.

* New business models
  :PROPERTIES:
  :CUSTOM_ID: new-business-models
  :END:
Much like farming is industrialized, industry is becoming increasingly
"infotized" and, as a result, begins to look a lot different from an
assembly line sweatshop. Changes in the publishing industry may provide
a preview of patterns which could spread to other industries.

Prior to 2000, the only practical way to produce books was in batches of
thousands and distribution took place through brick-and-mortar
bookshops, so the author of average means would require a publisher to
pay the costs of printing up front and handle distribution and
publicity. Nowadays, this is no longer the case. Firstly,
print-on-demand services like Lightning Source make small runs of a
hundred or so copies economically feasible. Secondly, a platform like
Amazon allows the author to set up a virtual store which sells printed
copies on top of infrastructure for payment and distribution. Thirdly,
the author can finance the enterprise through a crowdfunding platform
like Kickstarter and publicize it through targeted ads and posts on
social media like Facebook. In this way, a decentralized network
performs the roles previously done by the centralized publisher and
allows the author to set up a customized virtual publishing house. The
hard part is still writing the book, though with computational
creativity in the mix perhaps even that is changing.

Historically, the industrial revolution started with mechanization of
the textile industry. In order for factory production to be practical,
clothes were made in standardized sizes and styles rather than custom
tailored. However, now that there exist computer-controlled cutting and
sewing machines,[fn:1] this need no longer be the case---with the new
technology, it takes just as long to make each item in a custom size as
to produce multiple identical copies.

As a counterpart to the publishing example, consider the following
story: Suppose that somebody wanted a pair of bright green jeans, like
their favorite character from a Netflix show. He might start by typing
his measurements into a CAD program to design the jeans, then send the
resulting file to a web service which would convert them into a pattern
and a bill of materials and provide cost estimates. The price for bright
green denim would be high because that would need to be custom dyed, but
the minimum amount is, say, 39 yards, which is way more than is needed
for a single pair of jeans. Thus our protagonist might advertise on a
venue like Craiglist, Kickstarter, or Patreon and put together a package
that cuts things out of the cloth (handbags, skirts, etc.). Once the
deal has been negotiated, a bolt of white denim from the warehouse will
go to a custom dye shop and leave as a bright green bolt to the no-sweat
shop where it will be cut up and sewn into the pants, skirts, and a
jacket. These finished items then get sent off, pieces for the handbags
get forwarded to another specialized shop, and a constraint program
arranges the remaining offcuts of the bright green denim into a crazy
quilt. A more complicated version of this story would have several kinds
of cloths, management of offcuts, communication between designers and
producers and so on.

Indeed, by analogy with splicing offcuts into a quilt, computer programs
may actually be able to help create new jobs by splicing together
different available sources of skills, labor, and information. Any of
the examples above in farming, sewing, or publishing could turn out to
be relevant to job seekers and could lead to job creation.

* Organization of Production
  :PROPERTIES:
  :CUSTOM_ID: organization-of-production
  :END:
As the ways of doing business in the examples spread to other areas,
they could alter the structure of the economy.

The typical organizational structure of production from the industrial
era was something as follows: At the bottom of the structure, we have
the producers of various raw materials such as agriculture, forestry,
and mining. Next, there is an infrastructure layer which provides common
needs for the whole of the economy. One part of this is utilities which
provide basic resources such as water, gas, electricity, and telephone
service distributed through a network of pipes and cables. Another part
is a transportation network of railroads and highways. On top of this
infrastructure rested two more layers: manufacturing, which turned raw
materials into finished goods; and wholesale and retail trade, which
delivered these goods to their end users.

This organizational structure is changing as we enter the information
epoch. At the bottom, the raw producers and infrastructure serve the
same roles although the way in which they operate has been affected by
automation. The day-to-day running of utilities has become increasingly
computational in nature, and has expanded to include the communications
cables, routers, and cell phone towers which comprise the basis for the
Internet. At the top levels, as we have seen in the examples of
publishing and clothing---as well as in the "farm to table"
movement---alternatives are emerging to the
manufacturer-wholesaler-retail paradigm which divide industry into
different sectors and partition economic activity between companies
along different lines. As a new middle layer, we have companies like
Amazon, Etsy, and WeWork whose business is largely based on taking
resources such as warehouses, delivery networks, computing centers, real
estate and repackaging them into a form suitable for use by other
businesses and individuals. Alongside these, there are business such as
Lulu and Lightning Source for publishing, and numerous globalized
software and data services, fabrication shops, along with the
hypothetical no-sweat sewing shop which perform specific tasks on input
which they receive from the transport and information channels and
distribute their output through the same channels. Finally, on top there
are entrepreneurs and businesses which combine and structure the
services provided in the middle layer to produce virtual assembly lines
and custom businesses.

- In the old system, whether it was of a communist or capitalist
  persuasion, there was a lot of centralization, things had to be
  standardized to be optimized. Now we have constraint solvers that can
  optimize without standardizing and can route and schedule distribution
  and transportation to make decentralization practical.

- In the old system, standardization in the form of centralized wealth
  was important to the pan-industrialist J. P. Morgan, and to Samuel
  Insull's Commonwealth Edison in Chicago which replaced small-scale
  generation with integrated distribution, as well as others who made
  mega-assembly lines; now the challenges have to do with distribution
  more so than generation.

- The old systems managed mechanical "failure" at the cost of days lost
  waiting for interchangeable replacement parts, possibly covered under
  warranty. Mechanical systems where themselves managed by
  bureaucracies. In Open Source software, failure is managed in
  technical ways (bug reports, formal proof, version control, unit
  testing) that are an integrated part of the workflow.

Support services for the new sort of business are more subtle and
flexible. This is where technologies such as cryptocurrencies and block
chains could play an important role by making possible micropayments and
means for negotiating and implementing complex agreements between
multiple parties in different locations (like in the green jean
example). Similarly, the needs of this new sector likely will lead to
new forms of finance and insurance.

An important part of the emerging new economy is an information commons
consisting of software, data sets, and texts. Programmers and other
information workers draw on this as a resource which enhances their
productivity and, in turn, create new content which enriches the
commons. Interactions on the commons such as posts to Stack Exchange
could be used as input to a suitable computational process that would be
used to assemble new job teams. The old question about "who owns the
means of production?" is less broadly relevant now that most people can
do work with a personal computer that has access to the information
commons. Yes, there's a question of who owns the factory that makes the
PCs, but that only affects a small percent of the population.

As noted by Monbiot, "there are four major economic sectors: the market,
the state, the household and the commons" [11]. Whereas current
socio-economic thinking focuses on the first two, we suggest that, as
the information commons becomes more important as the dichotomies of
production versus consumption and workplace versus home decrease, the
other two sectors will need to be taken into account.

* Education and Development
  :PROPERTIES:
  :CUSTOM_ID: education-and-development
  :END:
In the hunter-gatherer and agricultural epochs, the main source of
energy was muscle power. Hence there were plenty of tasks such as
clearing fields, digging holes, and hauling stones which required no
education or training, only an able body. During the industrial epoch,
these tasks were mechanized but the machines were stupid. Hence there
appeared plenty of jobs operating machinery and working on the assembly
line which required a minimum of vocational training. Thus, for much of
history, a person with a minimal education owning no special equipment
and getting by on a bare minimum of food, clothing, and shelter could
nonetheless be economically productive and play an important role as
part of the hard-working bedrock upon which the edifice of production
rested. This circumstance explains why practices such as chattel slavery
and child labor, however ethically repugnant, were economically
sustainable for such a long time.

Looking at the 1910 data, we see that domestic and personal service
accounted for 14.5% of employment but that, by 2015, they shrunk to 1%
due to the widespread availability of home appliances. Furthermore, the
text states:

#+begin_quote
  "A century ago, most jobs required little formal schooling, and most
  of the population had not gone beyond elementary or grammar school. In
  fact, high school graduates were a rarity: in 1915, only an estimated
  18 percent of the population ages 25 and older had completed high
  school, and only about 14 percent of people ages 14-17 were in high
  school." [7]
#+end_quote

A century later, this is changing drastically---in 2010, 28.1% of the
population had graduated college and, of these, 10.4% had gone on to
graduate school. Due to the drying up of the service sector and the
automation of the agricultural, manufacturing, transportation and retail
sectors discussed above, we are approaching a situation where a person
with a high school education or less is likely to be unemployable and
hence a drain on the economy rather than an asset.

* Inequality, Mobility, Spaces
  :PROPERTIES:
  :CUSTOM_ID: inequality-mobility-spaces
  :END:
While the degree of equality or inequality in a particular society will
depend upon social, political, and historical circumstances, technology
and economics set boundaries within which a society can be economically
competitive. At the lower end, there is minimum amount which must be
spent on an individual in order for that individual to still be only
able to contribute productively. At the upper end, there is a danger
that excessive wealth will lead to rent-seeking rather than
reinvestment. As always, inefficiencies may spawn successful competition
using other modalities: e.g., some say that GNU/Linux was able get a
foothold because Microsoft was abusing their monopoly and not improving
their product (Windows XP) for a long time.[fn:2]

The boundaries of the "low" and "upper" class varied historically, as
have the permeability of these boundaries and the rates, and kinds,
mobility within and between classes. Such issues are linked to other
kinds of mobilities. Literally moving from place to place is one way to
address inequality, insofar as a mobile person can try to improve their
lot by claiming an opportunity that lies elsewhere.[fn:3] These days,
growing internet connectivity and capability allow people to work from
anywhere and telecommute to new opportunities. Geographic mobility may
be less important given connectivity across geography.

Learning can be seen as a virtual mobility that allows access to, and
use of, new kinds of information. As such, learning is fundamental for
the current era. In the industrial epoch, there was a sharp divide
between the factory and office as loci of productivity and the home as
the locus of consumption. For better or worse, schools often took on
attributes of the factory. Today the distinctions of home, workplace,
and university are blurring and the household is re-emerging as a locus
of productivity. Ubiquitous smart phones and social media reshuffle our
notions of space and make new forms of networking possible.

Whereas, in the past, the costs of obtaining and maintaining a building
would have been a sizable portion of most business's operating
costs---and, similarly, the cost of obtaining an education would be a
significant lifetime expense---nowadays a laptop just might do for both.
Coffee shops and libraries are potentially useful complements to such an
acquisition. Although libraries have been closing their doors or
restricting their hours for some time, coffee shops are increasingly
prevalent. Their near ubiquity shows the important role played by "third
places" [12], intermediate between public and private, in the
information epoch. In addition, new sorts of spaces such as flex space
and coworking space are seen with increasing frequency.

The classic idea of "third places" shades into a similarly-named but
more theoretically charged concept, "third spaces" [13], [14]. The
complex as a whole might be re-theorized as "Cyber spaces." They
function as connectors, though they are not merely conduits. Whereas a
highway largely exists to facilitate the exchange of one location for
another, the cafe, and its later-day descendant, the Internet, permit a
wide range of exchanges among people who may well be staying put.
Mixed-modal settings, like those arranged using Meetup.com, can help
groups of people assemble around common interests on a wide variety of
themes, including many that are learning-relevant. Flash mobs, online
dating, and barter sites highlight the further social relevance of new
notions of "community," as well as people's willingness to involve
technology in their social infrastructure.

In the past, the quantity of unexpected interactions could only scale in
cities with lots of people in them [15]. To have hope of modeling the
stochastic interactions in new Cyber spaces that connect across major
economic sectors and ecological niches will require a thorough analysis
of network-, and broader interaction-effects [16], involving multiple
"currencies" [17].

* Looking Forward
  :PROPERTIES:
  :CUSTOM_ID: sec:conclusions
  :END:
A time traveler explaining factories to the folks who lived during the
Renaissance might in principle make headway by talking with them about
clock shops. It would still be a difficult stretch of the imagination to
go from that to a factory, even if the old town square automata featured
simulacra of people sewing things. It may be similarly difficult for us
to imagine the future of education. But we can nevertheless notice a
trajectory. In the 1990s, library card catalogs had by and large been
transferred onto computer catalogs. In the 2010s, most if not all of the
library's contents are available online.

Scholarship is quickly outgrowing the university. The total number of
academic papers has exploded. Open Source software and online
collaboration are additional ways to generate and share knowledge.
Perhaps in light of the need for jobs, people will spend more time
contributing to open projects like Wikipedia. This would be a good way
for someone to prove they have the right skills for a given job: and
with sufficient analytics, this may also lead to further employment---we
can easily imagine a program that monitors wiki and Open Source
contributions and invites applications based on what it finds.

On the way to the more-automated future, AI successes will continue to
amaze us with increasing frequency. While the latest conquest, Go, is
something that people do for entertainment, applications of AI to
education and job search---and indeed to job creation---will be directly
economically useful.

Conversations with Aaron Krowne and Cameron Smith influenced the
direction of this paper.

<<refs>>

<<ref-fivethirtyeight>>
[1] B. Casselman, “Manufacturing Jobs Are Never Coming Back.”
/FiveThirtyEight/, 18 March 2016.

<<ref-ai-big-data>>
[2] E. A. Mason, “A.I. And Big Data Could Power a New War on Poverty.”
/New York Times/, 01 January 2018.

<<ref-theguardianproductivity>>
[3] R. Partington, “UK productivity jumps at fastest rate for six
years.” /The Guardian/, 5 January 2018.

<<ref-farm-2017>>
[4] J. Corneli, U. Martin, D. Murray-Rust, A. Pease, R. Puzio, and G.
Rino Nesin, “Modelling the way mathematics is actually done,” in /2017
international workshop on functional art, music, modelling and design
(FARM 2017)/, 2017, [Online]. Available: [[http://metameso.org/ar/farm-2017.pdf]].

<<ref-elearning-market>>
[5] S. S. Adkins, “The 2016--2021 Worldwide Self-paced eLearning
Market.” Ambient Insight, 2016.

<<ref-milanovic1999true>>
[6] B. Milanovic, /True World Income Distribution, 1988 and 1993: First
Calculations, Based on Household Surveys Alone/. World Bank, 1999.

<<ref-leon2016life>>
[7] C. B. Leon, “The life of American workers in 1915,” /Monthly Labor
Review/, 2016.

<<ref-tech-at-work>>
[8] Citigroup, “Technology at Work v3.0: Automating e-Commerce from
Click to Pick to Door.” 2017.

<<ref-factory-jobs>>
[9] A. Bhattarai, “Factory jobs trickle back to the U.S., Giving hope to
a once-booming mill town.” /Washington Post/, 16 March 2016.

<<ref-farm-robots>>
[10] J. Chaffin, “Farm robots ready to fill Britain's post-EU labour
shortage.” /Financial Times/, 25 April 2017.

<<ref-monbiot>>
[11] G. Monbiot, “Common wealth.” /The Guardian/ 27 September 2017.

<<ref-oldenburg1989great>>
[12] R. Oldenburg, /The Great Good Place: Cafés, Coffee Shops,
Bookstores, Bars, Hair Salons and Other Hangouts at the Heart of a
Community/, 3rd ed. Da Capo Press, [1989] 1999.

<<ref-bhabha1990third>>
[13] J. Rutherford, “The Third Space: Interview with Homi Bhabha,” D.
Identity: Community Culture, Ed. Lawrence; Wishart, 1990, pp. 207--221.

<<ref-soja1998thirdspace>>
[14] E. W. Soja, “Thirdspace: Journeys to Los Angeles and other
real-and-imagined places,” /Capital & Class/, vol. 22, no. 1, pp.
137--139, 1998.

<<ref-pan2013urban>>
[15] W. Pan, G. Ghoshal, C. Krumme, M. Cebrian, and A. Pentland, “Urban
characteristics attributable to density-driven tie formation,” /Nature
Communications/, vol. 4, 2013.

<<ref-moya2015calculus>>
[16] A. Moya, /The Calculus of Life: Towards a Theory of Life/.
Springer, 2015.

<<ref-joiito-currencies>>
[17] J. Ito, “Resisting Reduction: Designing our Complex Future with
Machines.” /pubpub.ito.com/, 14 November 2017.

[fn:1] Current hobbyist-grade appliances include the Cricut and the
       Brother Embroidery and Sewing Machine with USB Port; more
       industrial-grade machines include various offerings from Dematron
       and the Quilting Master IV.

[fn:2] Timothy Teravainen, p.c.

[fn:3] "To leave all we've ever known / For a place we've never seen,"
       Tom Waits "Chicago" (2011).
