:PROPERTIES:
:ID:       5b0926e2-7fb7-43a0-8a0d-112694452844
:END:
#+TITLE: Peeragogy in Action PAR, [2021-03-12 Fri]
#+authors: Joe Corneli, Leo Vivier, Charlotte Pierce, Jerry Michalski, Peter Kaminski

* Pete is sharing an image
We like /HackMD/ and the CRDT-ness of it
* Joe and Leo are co-typing something
- Hi Charlotte:
- Hi everyone else... from Joe — yay
- And I can type at the same time here (from Leo!)
* Leo goes for basic demo
Rebuilding the cache takes a while!
If you know this is an org mode file
- How links work
- Rather than working with a GUI we do it with text
- You can create links by hand in text — it’s not clever
- What org roam does is it allows you to ease up the process...
* Do you have to know the code?

Dashes — learning the key strokes — working in Emacs is a particular
paradigm...

- Pete isn’t shocked, he is an Emacs user
- Back in the day I was using vi

* Going in file Foo...

When I go into drawing mode I go into arborescence.

- Questions can’t be addressed now in real time!

* What is a backlink?
- There are no backlinks at first
- There’s a difference...

Foo is the door — The door is behind me...

The links that Leo made are ‘explicit’ links — made by Leo

The other ones are ‘implicit’ links — the computer makes these

* You could have up / down / left / right links

- As a convention in the file

... this is as opposed to a graphical user interface because...?

- This isn’t easier... but it’s much more powerful...?
- ZAMM 2021

Text allows us to abstruct so much stuff.

I do really like the notes in The Brain

* Could this talk to Mattermost / Zulip?

- This is inside of Leo’s repo for Peeragogy stuff
- As soon as he saves the file it’s available online

* How to optimize the database and stuff in 

400000 nodes
850000 links

32768 — ‘I just bumped into your namespace’

Later had free range for a long time...

Leo’s graph isn’t very organised... is there anything I can show

CP: I’m grateful to see shapes!

But I’m only generating these files thanks to plain text.

This is a rubber-bandy visualisation

There’s a little metadata that does ‘above’ or ‘below’

You’re inferring the links, but this could easily turn into
a brain like display with just a little more metadata.

What needs to be layered in?  Do we need to use SoLID?

The reason I’ve stuck with the brain is the particular orientation of
up/down/left/right of how the gates work...

I use it in 6 ways.  But this doesn’t look too far from the wish-list.

PK: Roam and Obsidian 
Free Jerry’s Brain will hook up with Obsidian in next month...

I think we’re all working with notes (nodes?) & links

But the idea of ‘expressivity’ feels like the most opinionated feature

It would be very interesting to map out how the expressivity
influenced the way the software was/is developed.  If we are going to
make an all-encompassing system.

If we are to have a software-agnostic way of describing links between nodes... the goal / onus becomes:

- How to transfer one model to the next to transfer the expressivity from one software to the next...

Clicking / left right up down

— The meaning is encoded in the brain?

I’ve come up through usage: Authors created the books Actors are acting in their movies Novels are based on the movies There’s a flowing through time up/down

It’s an expressive gesture that’s quirky to me that happens to work...

Some people have left-right orientations which seem a bit weak, but a loose tool with a lot of expressive capacity allowed me to invent these clichés myself.

Offering up tools that allow you to riff / alter the code ...

* Roam boom / Brain boom

- organicity - by doing away w/ hierarchy and letting structure arise
- This removes a lot of resistance to the act of notetaking and writing
I like the idea of creating a second brain in which you dump anything you can’t process...

- The connections happen serendipitously or ‘as and when’

The best thing we could do is reconsile what roam research is doing, theBrain is doing...

Because of the expressivity, some of the models are limited...

We are in the org ecosystem and there’s a lot we could do...

* If Roam Research were to turn off the server...

(or have a fire)

There’s no way to back it up properly...

The eventual system that lets us mingle our thoughts with each other would have to let us preserve our perspectives

- I don’t want to dump it into something like Wikipedia
- I want to also be able to go back to ‘what I co-entered’
- I don’t mind if things are co-mingled but I need to be able to come back to what I know is there for my work...
- AND THEN we could do it with the 6 of us or the 6000 of us

* Didn’t Dell Computing start working on this?

There have been 15 different major interoperability efforts
POSix and 19 more... 

Xanadu for some of us...

Jerry wrote about this long ago
(Relationship with ARXANA?)

Diversity of information/expression

If one thing gets hit by a bomb or whatever... there’s another part that will rebuild

FJB calls on Mondays — a good freefire zone for these things

* Figuring out the calendar

8am PDT / 4pm UTC

* Other links

Cf. Law.git
