#+title: Week 1 February 2021
#+FIRN_UNDER: Updates
#+FIRN_LAYOUT: update
#+DATE_CREATED: <2021-02-02 Tuesday>
#+AUTHOR: Joe Corneli

* Start of the week

I went over my two draft EPSRC proposals, using the standard reviewer
form to structure them further.  That improved them somewhat.  I also
sent a copy of the ‘1st proposal’ to internal Brookes colleagues Dev,
Jintao, and Ari.  I received some written feedback on previous drafts
from Brendan Fong and Valeria de Paiva of Topos.  Their criticisms
should improve the clarity of the presentation, and I’m also thinking
of delaying the second proposal on [[file:arxana.org][Arxana]] until it is more mature and
backed up by a current demo.  Hopefully my Brookes colleagues will
soon have some feedback on whether the proposal that I shared with
them is something they want to get involved with.

On Wednesday last week we had the initial AIDAN meeting.  Since then
we have set up a Google Group, Google Calendar, and Google Site, to
get started with some active networking.  People followed up with me
about various themes, e.g., I’m meant to introduce Rachel and
Hooshang, which I’ll do shortly!  Maybe this will lead to a research
project that my the students in my “Survey Fundamentals” class could
tackle (surveying Rachel’s students?).  On Wednesday I also had my
first weekly office hour with the “Survey Fundamentals” students.  I’m
glad I set that up.  It humanises the situation for everyone, and no
one told me to do it so it’s a matter of my own initiative to have
done so.

I seem to be reasonably well set with reading materials for the
course, and I’ve mostly figured out how to use Moodle.  During the
week, Deyan and Leo and I had some interesting chats about why some
people may have become especially overwhelmed with the move to online
teaching.  After a couple weeks, I’ve found that it definitely takes
some of the time I might have otherwise used for research and
accordingly seems to slow me down: but maybe this is a reason to
adjust my expectations rather than just to complain that my
expectations have not been met.  (Riffing on [[https://www.tandfonline.com/doi/pdf/10.1080/1360080022000013518?needAccess=true][Student Satisfaction: An
alternative approach to assessing this important concept]], which was
shared by one of the students.)

Looking ahead, I feel I need to re-emphasise *energy management* rather
than *time management*.  It seems like under the current circumstances I
would struggle to find /time/ to work on big monolithic projects.
However, if I can break down the projects a bit further I may find I
have the /energy/ to tackle something small.

Some of these prospective ideas follow.  Maybe the breakdown should
eventually be moved into [[https://github.com/zaeph/org-super-agenda][org-super-agenda]] rather than just living in
PostIt notes.  But, the PostIt notes are a decent start.

** Arxana

I made decent progress getting the earlier versions running, but
havent yet written up a report on what we would want the recent
version of the system to actually do, e.g., a real plan of work for
the ‘2nd’ EPSRC proposal.

** Serendipity

Here I have gotten off to a good start thanks to some correspondence
over the weekend with Thomas Baruzzi.  However, there are loads of
historical reviewer comments to get through, the rest of the ML Street
Talk video to watch, the actual slides to prepare, and if I get
through all of that, the paper rewrite to tackle.  It probably makes
sense to get all of these sub-tasks going in parallel.  (Interestingly
this might be a use case for Arxana, insofar as it involves various
views and transclusions within one corpus.)

** HCI Ethics

This project has been moving reasonably well, because Luís and I (and
sometimes others) have been having weekly meetings about it.  However,
if everything needs to be done in those meetings, the progress will be
at a snail’s pace.  What else can be done?  One of the points of
resistance is that there are lots of relevant books to read but I
haven’t been able to go to the library, and I’m not sure I can afford
to buy all of the relevant books!  That said, I have bought a
half-dozen books or so that would be relevant so I could try to read
or skim-read those.

** Peeragogy

Some of my intuitions about peeragogy could potentially go into an NSF
“Future of Work” proposal... though doing that as a volunteer rather
than as part of my job at Brookes could prove exhausting.  Meanwhile
it is super straightforward to go through the remaining comments on
the Pattern Catalogue chapters into concrete Next Steps.  I expect
something interesting can emerge from that.  Charlie Danoff (and maybe
some others) would be interested to join the Emacs Research Group on
February 13th for a practical session on Org Mode and Peeragogy.

* Postscript

That gives an initial breakdown of the main tasks that I had been
hoping to “find time” to work on.  Hopefully now, the game has shifted
somewhat.  That said, although I’m not feeling ‘burnt out’, I have
been feeling pretty tired today, so I may need a bit of time off to
recoup before digging into these things.
