:PROPERTIES:
:ID:       7550513a-ffc0-43c1-924a-02cb4670be67
:END:
#+TITLE: Forum
#+CATEGORY: OTS
#+filetags: :OTS:AN:TO:

We talked about using Wikum as a forum, because we liked the idea of a
workflow based on summarising discussions. There’s now a demo instance
set up that we can use, here:

http://wikum.org/visualization_flags?id=590&owner=holtzermann17

* Could we incorporate the ideas directly in Org or Org Roam?

Perhaps we could incorporate some Wikum ideas right into the wiki
here.  The idea would be to treat the top paragraph on each page as a
summary, and then add discussion threads below.  We’d want some system
of tags that indicated whether the summary was validated or now.
(Note the the original WikiWikiWeb did not have separate talk pages!
I don’t know if they practiced robust summarisation, either.)

*************** REMARK                                                  :joe:
This is an “inline task,” via =(require 'org-inlinetask)=.  There
doesn’t seem to be support for nested or threaded tasks, but maybe we
would have use for non-threaded forum discussions at the end of any
page in the Wiki.  Incidentally, for those curious, the formatting of
the \LaTeX\nbsp{}export is controlled by
=org-latex-format-inlinetask-function=.
*************** END

* Next steps

- [[file:stubs/develop_our_own_intention_based_workflow.org][Develop our own intention-based workflow]]

** BACK What might our summarisation workflow look like?
- [[id:6aa0104c-3cfb-4a2c-881a-bfd304abb1ba][What might our summarisation workflow look like?]]
Since we’re pretty actively updating our *Discord* and pretty happy
using it, maybe people who are working on Active Projects would be
willing to summarise on the wiki, say, weekly?  And contribute to a
monthly group blog post?
