:PROPERTIES:
:ID:       181d1cba-8d5d-4292-9357-9c59eaed7884
:END:
#+TITLE: Recommender System
#+CATEGORY: ML
#+filetags: :LRD:

We could consume various analyses of Stack Exchange data to make
recommendations.

* Possible implementation strategy: build on a version of GPT fine-tuned on SO Q&A tasks

Could we set up a simple version of *GPT* trained on Stack Overflow
data, just to get it working? Then think about how to get a learning
loop set up to improve the results...

** Ideas

- Could this at least help a human navigate the questions on Stack Exchange?
- Rather than just answering the question, generate the answer and use
  that to guide search (by combining generation with document similarity)
- Use a distance to set up a margin of tolerance

** Precedents

- [[https://stackroboflow.com/about/index.html][Stack Roboflow]] creates ersatz Q&A using =AWD_LTSM=.  Surely we can do better?
- In Google Books, they use crappy OCR which is good enough for search, but you wouldn't want to read the output.  For search, they use something like rewrite distance, finding something ‘within 5 errors’.

** Analogue

In parsing, it's not just edit distance but has to involve the grammar

** Case against going too deep:

- Code generation is hard

** Case against worrying about that:

- Worry instead about applications like generating learning packets
 - E.g., learn everything there is to know about =git= from Stack Overflow in a nicely organised way.
 - E.g., compare the Schuam’s Outline series: could we reassemble open source clones of Schuam’s Outlines by retrieving contents from Math.Stack Exchange?

** Application of the model: Display SO with similarity graph
E.g., use generated answers to help identify ‘similarity’.

** Related work

- https://github.com/stared/tag-graph-map-of-stackexchange/wiki presents a nice-looking map of the relationship between tags.

* Feature: Initial import of SO for training                           :tim:
* Contributes to :noexport:

- [[id:58cdda7a-da0f-41bf-9387-fe474a945ca4][Advances in tutoring systems for programming]]
- [[id:fb5b11a8-9567-47d5-b5d4-8d8abb32351b][Agent model]]
- [[id:3c55cf7c-1dbe-4e33-b49a-6ff583db67e5][Teach arbitrary coding]]

