:PROPERTIES:
:ID:       3d812f5d-32eb-4ff7-a07d-8b5db73b217c
:END:
#+title: Hyperreal CLA #1 01 November 2021
#+LATEX_HEADER: \hypersetup{frenchlinks=true}.
#+filetags: :HL:

Using the principle of ‘adapting wholes’ from Christopher Alexander,
I’ll start with [[id:732219c0-9784-4593-b781-b82e54e948ce][CLA 16 October 2021]] from ERG.  There are plenty of
overlaps in terms of people and processes.  However, this will need
considerable adaptation to take into account the data we’ve been
gathering in our Discord (incluing PARs by Joe and Alex).

I did some sketching in =/home/joe/new-cla=.

* Litany

#+begin_comment
We’ve made progress since we started with the raw themes of [[file:./research_on_in_with_emacs.org][Research
on/in/with Emacs]] back in October 2020.
#+end_comment

Hyperreal Enterprises Limited was [[https://hyperreal.enterprises/][incorporated]] on June 25th 2019,
initially around a call for proposals that was circulated by [[https://conexus.com/company/about/][Conexus]].
*However*, in the end we didn’t submit [[https://exp2exp.github.io/conexus_proposal][our proposal]], because we felt
that Conexus wanted projects that were further along.

#+begin_comment
We’ve met [[file:./almost_every_week.org][almost every week]] since then, and interviewed some
interesting and varied [[file:./guests.org][guests]].
#+end_comment

During the early months of the Covid-19 pandemic, Joe was enrolled at
Entrepreneur First and tried out a range of business ideas related to
the themes we’ve been talking about.  *However*, none of these turned
into a pitchable business, despite some progress on product
development.

Also during this time, a group of friends started to meet on Fridays
for informal discussion around some of the developing ideas.  Since
then, these discussions morphed into brief daily calls, and eventually
into longer daily calls.  These calls broadly focus on “peer support”
rather than strictly focusing on business or product development (for
example).  Our culture is a bit like that of the [[https://en.wikipedia.org/wiki/Algonquin_Round_Table][Algonquin Round Table]].

#+begin_comment
We have a clearer idea of what [[file:./what_we_want_to_talk_about.org][what we want to talk about]] at the next
EmacsConf, and how we can be of service to researchers and Emacs
users.
#+end_comment

Many of the involved persons have been involved in [[https://exp2exp.github.io/erg][collaborative research on Emacs]]
and in [[https://arxiv.org/abs/2107.10497][research on collaboration]] per se.  One of the early unifying themes around Hyperreal
was to keep track of how we were learning things, and try to make what we were learning
“reproducible” for others.

#+begin_comment
We have been using a [[file:./workflow.org][workflow]] that helps us carefully review progress,
diagnose issues, and manage our energy.
#+end_comment

Alongside our peer support calls, we’ve also experimented with reading
and study groups that help us study topics of mutual interest.  Topics
covered include: clojure programming, basic algorithms, logic
programming, startup culture, real-time collaborative editing, futures
methods and distributed problem solving, and as well as the
Emacs-related work mentioned above.  These are at various stages of
development.  We also brought some Master’s supervision work into the
shared practice space.

With these projects we’ve experimented with different ways of
reviewing progress, diagnosing issues, and managing our energy.  One
asynchronous feature is an “intention-based” chat that sprawls across
various virtual locations in our virtual office park.

#+begin_comment
We’re understanding [[file:./how_research_is_done.org][how research is done]] by doing it, and keeping
careful track of the process.
#+end_comment

We’ve focused a lot of energy on developing a shared ‘mindfulness’
practice, insofar as we are always working to listen well and
communicate clearly around topics of shared interest.  We’ve been
relationship- and person-centred.  Inspiring cultures of collaboration
range from the Sangha that grew up around Gotama to the beanbag-based
feedback circle at Xerox PARC, as well as our experience with other
earlier and ongoing online collaborations.  By maintaining different
‘rhythms’ of collaboration and different subgroups, we have been able
to experiment with different ways of working.

#+begin_comment
If [[file:./a_session_doesn_t_go_as_well_as_hoped.org][a session doesn’t go as well as hoped]], we think about why
(especially Leo as chair).  You know what the bomb is, so you can at
least hope to defuse it later.
#+end_comment

We have typically been able to defuse “co-founder risk” by tabling
emotions and practicing sincere and respectful communication.
Naturally, some of the early participants have had other priorities
and have not stuck around.  Presently we’re in a position where the
ongoing daily calls can help to support other circa-weekly activities
and vice versa.

#+begin_comment
We try to adapt gracefully to circumstances as they evolve, without
being reactive because we know [[file:./we_will_be_back_again_next_week.org][we will be back again next week]] and the
week after, etc.
#+end_comment

Because we’ve so far been committing to show up just every day and to
stay reasonably productive while also supporting one anothers’
thriving, we’ve built (or deepened) our rapport.

** Projects

- PLACARD paper
- Emacs conf lunch presentation
- Cool flaws workshop
- Peeragogy mini-handbooklet
- Reasoned schemer read
- Ob-servant and hypernotebook
- CRDT


* System

#+BEGIN_COMMENT
If we tackle big enough projects, it will bring with it the need for
[[file:./collaboration.org][collaboration]].
#+END_COMMENT

Thanks in part to the Peeragogical way of working, we find ourselves
collaborating in a loose network.  Typically, each of the participants
in Hyperreal brings some of their own collaborations, e.g., in
research (whether linked to formal employment or other informal
collaborations) or Free/Libre/Open Source Software: or even in
personal life.  We’ve also been aware of the need to be well grounded
in our individual lives through sport, meditation, diligence in work,
or other forms of deliberate (etc.).  The regular meeting times and
attention to quality of discourse therein have helped to support this.

#+BEGIN_COMMENT
(And we need to [[file:./respect_these_other_parties.org][respect these other parties]].)
#+END_COMMENT

With the various meeting topics mentioned above, sometimes the topics
drift (cf. [[http://scansitu.antipool.org/6004.html][Open Creation and its Enemies]] by Asger Jorn and [[https://monoskop.org/images/6/6b/Eco_Umberto_The_Open_Work.pdf][The Open
Work]] by Umberto Eco).  Since we don’t want everything to dissolve into
a mishmash, we’ve been trying to keep the main focus relatively
clearly delineated in the various sub-projects and sub-fora.  Such
clarification is still ongoing work-in-progress (with the
‘intention-based’ chats mentioned above being one of the pilots).

#+BEGIN_COMMENT
We like to create [[file:./tangible_deliverables.org][tangible deliverables]] (e.g., journal articles).
#+END_COMMENT

Our shared [[https://exp2exp.github.io/][wiki]] touches on some of the ideas and motivations that have
occurred to us.  We have managed to generate some joint outputs for
EmacsConf 2020 and 2021, as well as PLoP 2021.

#+BEGIN_COMMENT
However, “If we knew what the outcome was it wouldn’t be research” —
therefore, we’re [[file:./focusing_initially_on_research_methods.org][focusing initially on research methods]] and [[file:./design_documents.org][design
documents]].
#+END_COMMENT

We haven’t focused so much on product or business development since
the Entrepreneur First days.  In principle we could get back to that,
but presently our joint activities seem to be focused more on learning
and research, with peer support for individual activities also taking
high priority.  That said, some product or service development ideas
may emerge from these research directions, e.g., work on [[http://arxana.net/][Arxana]] is
likely to be revitalised by our work with logic programming.
Similarly, the [[https://exp2exp.github.io/report_on_first_placard_workshop][PLACARD workshop]] is something that we think we could
run (with adaptations) with in various settings to benefit a variety
of initiatives.

#+BEGIN_COMMENT
So far many of the stakeholders have to do with free software, open
communities, peer learning: all of this is part of a broader
initiative.  All of them will need some degree of systematised
activities and documents.  This is what we’re experimenting with; in
principle, we can provide meta-management workflows, and making sure
to take account of emotions, not just a time table.
#+END_COMMENT

If we had some money, we almost certainly would have the technical
talent around to soak some of it up.  However, we’re not yet ready to
pitch to investors, and the product/service development isn’t yet at a
point where we can put things in front of paying customers.  One
strategy for getting money would be to have one of our [[https://hyperreal.enterprises/history.html][research
projects]] funded (as a research project) and then to build a product
around it later.  In this regard, modelling open source knowledge
bases continues to be a likely bet (as in the Conexus proposal, in
fact).  We’ve also seen that some stakeholders in “wikis” and
“knowledge management tools” may be interested in the kinds of things
we could offer on a software consultancy basis.

#+BEGIN_COMMENT
We’ve been experimenting with futures methods that help us using the
future intelligently (neither trying to do everything ‘live’, nor
overburdening the future with a bunch of plans that can’t be
realised).
#+END_COMMENT

Presently, this CLA—which is based loosely on one developed by the
Emacs Research Group—is helping provide an anchor point for our
developing plans.  The [[https://exp2exp.github.io/][wiki]] provides another quite different
perspective.  In fact we’ve been writing together on wikis and
elsewhere for a while and have some other [[https://github.com/holtzermann17/AsteroidMetaArchive][related notes]] in [[https://github.com/holtzermann17/planetmath-docs/labels/PREVIEW][various
places]] that we could get some value from by collating here.

As we keep working, we will presumably adopt the PLACARD method from
our PLoP paper to keep refining the CLA.  Presently, we have some PARs
that can be used to round out the initial perspectives here.  This way
of working could be supported with some lightweight tools (e.g., an
email address for logging PARs, or an easy way to tag TODO items with
design patterns held in a shared repository).

* Worldview

#+begin_comment
We have looked at RStudio and Roam Research as models of (some of) the
kinds of things we think [[file:./emacs_can_eventually_improve_upon.org][Emacs can eventually improve upon]].  Actually
getting there requires thinking about the specificity of what Emacs
can do.  At least nominally, it is a system for editing.  For example,
currently we can edit a wiki using Org Roam and Git.  What about
editing distributed knowledge graphs?  This would allow people to
reference ongoing research processes.  Or we could go further and
contribute to the development of a new distributed read-write Web!
Alongside such software products could come various services, such as
a matchmaking service for academics, or a set of 24/7 virtual
conferences.  To make such thing really useful, we need to get
coherence out of various long-running, diverse, and hetereogeneous
thought processes: and make sure we help people address real problems.
We can start small, working with the members of ERG and their
networks.  We’re certainly not the only people who are struggling with
some [[file:./unexpected_commitments.org][unexpected commitments]].
#+end_comment

We noticed that by using the curvature of the earth it would be
possible to provide continuous global coverage with an ongoing
neverending “Jazz night”.  For example, if proponents of Hyperreal
were located at 5 equidistant Longitudes around Earth, we would have
complete coverage in daily five-hour shifts, though it would be rather
lonely without people in nearby timezones to talk to.

It can’t be too hard to create such a service; simply getting it up
and running would be one approach to addressing the chicken-and-egg
problem of “capacity building”.

There are, of course, other approaches, and since we are currently
distributed between the Central Europe and Pacific time zones, a daily
or weekly “pulse” makes sense for now.

We’re also working on getting our technical tooling into the best
shape, e.g., with Git, Org Mode, and CRDT tools for collaboration in
the short run, and things Arxana possibly starting to become useful
later on.

#+begin_comment
Successful adaptation requires the articulation of an entire system.
Thinking again about Emacs: its current documentation is certainly
useful, but it leaves many gaps, some of which are filled in other
ways (e.g., by mailing lists).  As we work we are paying attention to
the growth not only of knowledge, but also of capability.  For this,
we often rely on our feelings (getting it, not getting it,
accomplishing something or not, etc.).
#+end_comment

Broadly we’re only as effective as the sum (or perhaps, the
completion) of the individuals involved.  As such, our shared
worldview seems to put “practice” at the centre.

* Myth

#+begin_comment
In our concrete methods, we have aligned ourselves with the ‘[[https://longtermist.substack.com/][long-term
perspective]]’.  This includes both retrospective and prospective
thinking.  For example, the things that were timely 7 years ago might
now; in many cases the relevance of a given innovation goes down over
time.  That said, Emacs has an evolutionary character that has allowed
it to keep up with the times — apparently becoming increasingly
relevant and useful ever since Steele and Stallman started to
systematise [[https://www.oreilly.com/openbook/freedom/ch06.  html][Editor MACroS]] for the Text Editor and Corrector (TECO)
program.  Not only has the technology evolved, but so has the social
setting in which this work is done. After nearly a year of working
together, we’re now prepared to argue that other people should
consider getting together to create their own communities similar to
ours!  The concepts underlying the free software movement were based
on “[[http://www.gnu.org/software/emacs/emacs-paper.html][communal sharing]]” of source code: now we’re working on developing
and sharing other methods as well.  Just like free software has
legitimately expanded the range of what’s humanly possible, so too may
further efforts expand frontier of possibility.  As above, this takes
careful articulation, and a willingness to do truly original research
(without relying on fixed assumptions about what research is meant to
be, or where we will find value).
#+end_comment

Hyperreal Enterprises derives some of its mythos from a [[https://exp2exp.github.io/time_capsule][Time Capsule]]
created Fri, 01 Apr 2005.  At a deeper level it draws on the idea of
‘hyperreality’ as developed by Jean Baudrillard.  As per the
[[https://plato.stanford.edu/entries/baudrillard/][Baudrillard]] page in the Stanford Encyclopedia of Philosophy,

#+begin_quote
‘people live in the “hyperreality” of simulations in which images,
spectacles, and the play of signs replace the concepts of production
and class conflict as key constituents of contemporary societies’.
#+end_quote

If we embrace this idea and take it forward further, we’re led to the
view that we could build informational systems that can shift
mainstream reality.  There have been clear proof-of-concepts in the
Web and Wikipedia.  The sense that these are only some of the early
examples of in a genre is one of the tenets of Hyperreal Enterprises.
In-house, our Coffee Chats are overlayed on our ‘real’ lives and seem
to provide a sense of meaning that isn’t readily found elsewhere.  As
Baudrillard says elsewhere:

#+begin_quote
‘Excluded from the game, their revolt henceforth aims at the rules of
the game. This revolt can remain ambiguous if it is experienced as
anomie and as defeat, if it occupies by default the marginal position
assigned to it by the system or if it is institutionalized as
marginal. But it is enough that it radically adopts this forced
exteriority to the system in order to call the system into question,
no longer as functioning in the interior but from the exterior, as a
fundamental structure of the society, as a code, as a culture, as an
interiorized social space.’
#+end_quote

A meaningful symbol is the crow, a social tool-using bird, and the
idea of a “fake fake” from Philip K. Dick.

#+begin_quote
‘Imagine the horror the Disneyland officials would feel when they
discovered the cruel hoax. Real birds! And perhaps someday even real
hippos and lions.’
#+end_quote
